$axure.loadCurrentPage({
  "url":"创建.html",
  "generationDate":new Date(1554888125550.45),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"d82025d9ca734a9294a2b31e311f6727",
    "type":"Axure:Page",
    "name":"创建",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e79f0b613850425092f0114374ca61b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "size":{
              "width":950,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47d3faee6a5b4b57a7c3e180887daeca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "size":{
                  "width":950,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库信息/u144.png"}},
{
          "id":"1d7bd4dbcd3f46af80335ee856e8dbab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":6,
              "y":5},
            "size":{
              "width":122,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a592a832e9a4ce7894c5beb8e18454e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":6,
                  "y":5},
                "size":{
                  "width":122,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6adddb5792964909af127342b26c8962",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":111,
              "y":7},
            "size":{
              "width":62,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa73fa3cf1d74b419aadb9a86db92e2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":111,
                  "y":7},
                "size":{
                  "width":62,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cfa3e8116ab7491d94d28e2289a19cc2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":173,
              "y":7},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbae77c26904491b82b7182e548fb012",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":173,
                  "y":7},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ffd59565734e4b5c9e66b2f6b70903ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":287,
              "y":7},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4d7d20ba4534342a9047af7d902432a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":287,
                  "y":7},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bebba4bc42004efdb1740e3da856cfff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":403,
              "y":7},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77086ac617f043fb95178df9e9ad1dee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":403,
                  "y":7},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe5a9e406a6547149be98b9646c53278",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":513,
              "y":7},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d5861af28514b5db586419b28993b0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":513,
                  "y":7},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0b81cc6b1d84f51bf4612e7752cad59",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":624,
              "y":7},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3c7d25e5e50404492798d0726cddb08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":624,
                  "y":7},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd80d845f8414d13bac0295d48fb5e43",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":722,
              "y":7},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8027137a22a34cfa9695f501120f128f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":722,
                  "y":7},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3120992abc2c4d93a148d47d26458822",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":816,
              "y":7},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"746306503ce04bfa9e930b959254e877",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":816,
                  "y":7},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0e2834d3f3140aaae2b7b3d624a4e85",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":5,
              "y":451},
            "size":{
              "width":957,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cc2153707f34e548aab6ee27617d348",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":5,
                  "y":451},
                "size":{
                  "width":957,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库信息/u164.png"}},
{
          "id":"33c8d48293174c50b670774984e8b436",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":819,
              "y":457},
            "size":{
              "width":134,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"645ac76ea3af40efa27ca6202773a4aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":819,
                  "y":457},
                "size":{
                  "width":134,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"283c840d0b934c2c8b41a21e9c9f0be9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":90},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20025a61d2ef436e8251225f5855772f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":13,
                  "y":90},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"67b8729c702749c59b6c554373d49032",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":76,
              "y":85},
            "size":{
              "width":104,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2a83e20a0a384fba9dfb0e5e91caae38",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":40},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5c76da9b13894a7c8c3d89d2133f4704",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":131},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d915090ad5bb4a9f9c9c189bb5706f7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":13,
                  "y":131},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5e84e55ea134d00b4193ae04f8ec346",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":76,
              "y":131},
            "size":{
              "width":527,
              "height":95}},
          "adaptiveStyles":{
}},
{
          "id":"88d664b678444a25be7a5c5fb9c648f7",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":40},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"25f48cb7d70a474780541244ea3fa472",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":215,
              "y":88},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf8afda96d0e4bc7be19d507015638e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":215,
                  "y":88},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e9658286294f40a4b2d1c614136f1083",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":296,
              "y":84},
            "size":{
              "width":87,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3946e16693d6493f8d9c4f9b5d178556",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":415,
              "y":88},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6455b66daa5f4920b041c17e22bd9a5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":415,
                  "y":88},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff719e55b2f0420d97a58f57dbfec1bd",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":496,
              "y":84},
            "size":{
              "width":87,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "e79f0b613850425092f0114374ca61b2":{
      "scriptId":"u0"},
    "47d3faee6a5b4b57a7c3e180887daeca":{
      "scriptId":"u1"},
    "1d7bd4dbcd3f46af80335ee856e8dbab":{
      "scriptId":"u2"},
    "2a592a832e9a4ce7894c5beb8e18454e":{
      "scriptId":"u3"},
    "6adddb5792964909af127342b26c8962":{
      "scriptId":"u4"},
    "fa73fa3cf1d74b419aadb9a86db92e2a":{
      "scriptId":"u5"},
    "cfa3e8116ab7491d94d28e2289a19cc2":{
      "scriptId":"u6"},
    "cbae77c26904491b82b7182e548fb012":{
      "scriptId":"u7"},
    "ffd59565734e4b5c9e66b2f6b70903ce":{
      "scriptId":"u8"},
    "f4d7d20ba4534342a9047af7d902432a":{
      "scriptId":"u9"},
    "bebba4bc42004efdb1740e3da856cfff":{
      "scriptId":"u10"},
    "77086ac617f043fb95178df9e9ad1dee":{
      "scriptId":"u11"},
    "fe5a9e406a6547149be98b9646c53278":{
      "scriptId":"u12"},
    "2d5861af28514b5db586419b28993b0e":{
      "scriptId":"u13"},
    "b0b81cc6b1d84f51bf4612e7752cad59":{
      "scriptId":"u14"},
    "b3c7d25e5e50404492798d0726cddb08":{
      "scriptId":"u15"},
    "cd80d845f8414d13bac0295d48fb5e43":{
      "scriptId":"u16"},
    "8027137a22a34cfa9695f501120f128f":{
      "scriptId":"u17"},
    "3120992abc2c4d93a148d47d26458822":{
      "scriptId":"u18"},
    "746306503ce04bfa9e930b959254e877":{
      "scriptId":"u19"},
    "c0e2834d3f3140aaae2b7b3d624a4e85":{
      "scriptId":"u20"},
    "5cc2153707f34e548aab6ee27617d348":{
      "scriptId":"u21"},
    "33c8d48293174c50b670774984e8b436":{
      "scriptId":"u22"},
    "645ac76ea3af40efa27ca6202773a4aa":{
      "scriptId":"u23"},
    "283c840d0b934c2c8b41a21e9c9f0be9":{
      "scriptId":"u24"},
    "20025a61d2ef436e8251225f5855772f":{
      "scriptId":"u25"},
    "67b8729c702749c59b6c554373d49032":{
      "scriptId":"u26"},
    "2a83e20a0a384fba9dfb0e5e91caae38":{
      "scriptId":"u27"},
    "5c76da9b13894a7c8c3d89d2133f4704":{
      "scriptId":"u28"},
    "d915090ad5bb4a9f9c9c189bb5706f7f":{
      "scriptId":"u29"},
    "f5e84e55ea134d00b4193ae04f8ec346":{
      "scriptId":"u30"},
    "88d664b678444a25be7a5c5fb9c648f7":{
      "scriptId":"u31"},
    "25f48cb7d70a474780541244ea3fa472":{
      "scriptId":"u32"},
    "cf8afda96d0e4bc7be19d507015638e2":{
      "scriptId":"u33"},
    "e9658286294f40a4b2d1c614136f1083":{
      "scriptId":"u34"},
    "3946e16693d6493f8d9c4f9b5d178556":{
      "scriptId":"u35"},
    "6455b66daa5f4920b041c17e22bd9a5e":{
      "scriptId":"u36"},
    "ff719e55b2f0420d97a58f57dbfec1bd":{
      "scriptId":"u37"}}});