$axure.loadCurrentPage({
  "url":"标准盘点_1.html",
  "generationDate":new Date(1554888136724.58),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"08f1c15dbeaf4e859e8f4fc869d4d82c",
    "type":"Axure:Page",
    "name":"标准盘点",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"57ae4f7c96d14011bcdd50903474d5e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":125},
            "size":{
              "width":92,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9857a3eb59f340a19d858c8e9dddfb97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":125},
                "size":{
                  "width":92,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"723185102367412982e2bec1c82c5b99",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":125},
            "size":{
              "width":180,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"abd1798d70574a41b41311e4c0d5996f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "size":{
              "width":305,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46404bd236a04e179052bdd24966b738",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "size":{
                  "width":305,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u6.png"}},
{
          "id":"932988044dd74023bfb81cb2ceaf8941",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":4,
              "y":5},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4e2e1cc706948708a6707e45ff41574",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":4,
                  "y":5},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f27b532b589d482aa1a2910520004135",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":124,
              "y":7},
            "size":{
              "width":181,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b48d6ac6cbfa43f8b92640db4a0598b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":124,
                  "y":7},
                "size":{
                  "width":181,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5f6d1c4caf14c8fae9d4404791d4969",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":1,
              "y":451},
            "size":{
              "width":308,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91db1d65afd54099862c3e14d29c19b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":1,
                  "y":451},
                "size":{
                  "width":308,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u12.png"}},
{
          "id":"81a763db29954935a207693e94e53f56",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":144,
              "y":457},
            "size":{
              "width":162,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89011725b5f7498a91442b5abacd667e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":144,
                  "y":457},
                "size":{
                  "width":162,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"474a9a5539a2470abe96f7ed817b9f83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":49},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"379d6c4c74f94ff287dd790a73cf8bc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":49},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8b9b2e840c345bc9399c0598c3913ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCCC},
            "location":{
              "x":335,
              "y":24},
            "size":{
              "width":415,
              "height":416}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3476483e67404e2eba47b45de2dbfcdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCCC},
                "location":{
                  "x":335,
                  "y":24},
                "size":{
                  "width":415,
                  "height":416}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pod盘点_1/u15.png"}},
{
          "id":"3836fe91872b40459a0dbc2a455caa17",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":170},
            "size":{
              "width":92,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95bbddb7ef0b404d9a79581afaa87b9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":170},
                "size":{
                  "width":92,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61a09fca91854d4aa2f8f1812789e3bf",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":182},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"268f1203682745b2aa8c832a83e0f719",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":16,
              "y":220},
            "size":{
              "width":92,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"602a8ded858f4c079584732a37e58c29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":16,
                  "y":220},
                "size":{
                  "width":92,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a8a9bd28d7e4034a6b6d168fb626707",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":219},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c2f8fda7b7c54ef5b5178c3020116cef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":18,
              "y":380},
            "size":{
              "width":112,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb224a5658fa4ca2816088209abed9bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":18,
                  "y":380},
                "size":{
                  "width":112,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pod盘点_1/u23.png"}},
{
          "id":"bc81dfb8c4264050b63837df3f0d5895",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":49},
            "size":{
              "width":182,
              "height":26}},
          "adaptiveStyles":{
}},
{
          "id":"e1993a9fcf3c457ca903136353d493d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":20,
              "y":266},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec7688d468224719938a8630e48ff499",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":20,
                  "y":266},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d60aa80f6a64d1fbc5044b79ef7c425",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":262},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8b16cd81a98542f7bbe828e5a4c2dbca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":301},
            "size":{
              "width":92,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"688f54929c9e47bfaa7e073512c63417",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":301},
                "size":{
                  "width":92,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a66a65626cd44e2a5e6c28d8897d397",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":299},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"bfdb562492614f16b83549daeefaf4c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":20,
              "y":89},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcfc5d0304664c9f80bcb5efe580944f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":20,
                  "y":89},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"753b6d4777fe404bba2a48ac277bdb32",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":85},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3e39536b38d04d2a9c6d69496ab8a8ed",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":377.5},
            "size":{
              "width":91,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 弹出窗口 打开 标准盘点扫描",
                      "target":{
                        "targetType":"page",
                        "url":"标准盘点扫描.html",
                        "includeVariables":true},
                      "linkType":"popup",
                      "popup":{
                        "left":100,
                        "top":100,
                        "width":300,
                        "height":500,
                        "toolbar":false,
                        "scrollbars":false,
                        "location":false,
                        "status":false,
                        "menubar":false,
                        "directories":false,
                        "resizable":false,
                        "centerwindow":true}}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "57ae4f7c96d14011bcdd50903474d5e8":{
      "scriptId":"u0"},
    "9857a3eb59f340a19d858c8e9dddfb97":{
      "scriptId":"u1"},
    "723185102367412982e2bec1c82c5b99":{
      "scriptId":"u2"},
    "abd1798d70574a41b41311e4c0d5996f":{
      "scriptId":"u3"},
    "46404bd236a04e179052bdd24966b738":{
      "scriptId":"u4"},
    "932988044dd74023bfb81cb2ceaf8941":{
      "scriptId":"u5"},
    "b4e2e1cc706948708a6707e45ff41574":{
      "scriptId":"u6"},
    "f27b532b589d482aa1a2910520004135":{
      "scriptId":"u7"},
    "b48d6ac6cbfa43f8b92640db4a0598b8":{
      "scriptId":"u8"},
    "a5f6d1c4caf14c8fae9d4404791d4969":{
      "scriptId":"u9"},
    "91db1d65afd54099862c3e14d29c19b8":{
      "scriptId":"u10"},
    "81a763db29954935a207693e94e53f56":{
      "scriptId":"u11"},
    "89011725b5f7498a91442b5abacd667e":{
      "scriptId":"u12"},
    "474a9a5539a2470abe96f7ed817b9f83":{
      "scriptId":"u13"},
    "379d6c4c74f94ff287dd790a73cf8bc5":{
      "scriptId":"u14"},
    "d8b9b2e840c345bc9399c0598c3913ee":{
      "scriptId":"u15"},
    "3476483e67404e2eba47b45de2dbfcdf":{
      "scriptId":"u16"},
    "3836fe91872b40459a0dbc2a455caa17":{
      "scriptId":"u17"},
    "95bbddb7ef0b404d9a79581afaa87b9c":{
      "scriptId":"u18"},
    "61a09fca91854d4aa2f8f1812789e3bf":{
      "scriptId":"u19"},
    "268f1203682745b2aa8c832a83e0f719":{
      "scriptId":"u20"},
    "602a8ded858f4c079584732a37e58c29":{
      "scriptId":"u21"},
    "9a8a9bd28d7e4034a6b6d168fb626707":{
      "scriptId":"u22"},
    "c2f8fda7b7c54ef5b5178c3020116cef":{
      "scriptId":"u23"},
    "bb224a5658fa4ca2816088209abed9bb":{
      "scriptId":"u24"},
    "bc81dfb8c4264050b63837df3f0d5895":{
      "scriptId":"u25"},
    "e1993a9fcf3c457ca903136353d493d5":{
      "scriptId":"u26"},
    "ec7688d468224719938a8630e48ff499":{
      "scriptId":"u27"},
    "9d60aa80f6a64d1fbc5044b79ef7c425":{
      "scriptId":"u28"},
    "8b16cd81a98542f7bbe828e5a4c2dbca":{
      "scriptId":"u29"},
    "688f54929c9e47bfaa7e073512c63417":{
      "scriptId":"u30"},
    "7a66a65626cd44e2a5e6c28d8897d397":{
      "scriptId":"u31"},
    "bfdb562492614f16b83549daeefaf4c9":{
      "scriptId":"u32"},
    "dcfc5d0304664c9f80bcb5efe580944f":{
      "scriptId":"u33"},
    "753b6d4777fe404bba2a48ac277bdb32":{
      "scriptId":"u34"},
    "3e39536b38d04d2a9c6d69496ab8a8ed":{
      "scriptId":"u35"}}});