$axure.loadCurrentPage({
  "url":"pod盘点_1.html",
  "generationDate":new Date(1554888136584.95),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"a704e8314ed6417a8ab4eeb6a0f23567",
    "type":"Axure:Page",
    "name":"POD盘点",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"75fe507097a746b8af8f5173f0a6a5ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":125},
            "size":{
              "width":92,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd6c5d5dbec54d5685ad70e07432d118",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":125},
                "size":{
                  "width":92,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"042dd2e526ca4f4ba372de0e7b5df8dd",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":125},
            "size":{
              "width":180,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"2ad9204b97a841189795c4ee8accc01e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "size":{
              "width":305,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a767f3b673f4a6490154748166a373e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "size":{
                  "width":305,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u6.png"}},
{
          "id":"9db0867ab0c049ad8fc7ff93a66aa3c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":4,
              "y":5},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d8ee6dd870048e5a3614d852bb9d6a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":4,
                  "y":5},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"73ea90dc493c42ea9486339832b8d955",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":124,
              "y":7},
            "size":{
              "width":181,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2e117c4d18f4991bb7526b586a37e86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":124,
                  "y":7},
                "size":{
                  "width":181,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b72bac2aa8d742328712c819f7aa9f28",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":1,
              "y":451},
            "size":{
              "width":308,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efe21db035dd491ca0397ccc151d10e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":1,
                  "y":451},
                "size":{
                  "width":308,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u12.png"}},
{
          "id":"4d2c63bd5a1d4e989d7d7441caf46fe6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":144,
              "y":457},
            "size":{
              "width":162,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0501c80546d34ac0bb4b1562bfbdcb66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":144,
                  "y":457},
                "size":{
                  "width":162,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3dbccbd0f2f44cb97241a03b11ce03f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":49},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31d0be54fe924c07a7fd83285475f559",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":49},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a46de3c461541fb998e22ef8452feca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCCC},
            "location":{
              "x":330,
              "y":24},
            "size":{
              "width":415,
              "height":416}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"639d81e97ca1470ca9f3ce30ab84b166",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCCC},
                "location":{
                  "x":330,
                  "y":24},
                "size":{
                  "width":415,
                  "height":416}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pod盘点_1/u15.png"}},
{
          "id":"5c257e45aa4542349691a3d2d40d7e04",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":170},
            "size":{
              "width":92,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cdd0fef4f91455688da1004ad15618f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":170},
                "size":{
                  "width":92,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70bc09f056cf4a1ba94f3f385a212e32",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":182},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"fb8bd188139449be94bc3c7164973713",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":16,
              "y":220},
            "size":{
              "width":92,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"719a020c5e984c468f960b17b01b9409",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":16,
                  "y":220},
                "size":{
                  "width":92,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e851922beab423487697a00f21ef024",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":219},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"579f9850356d457dacfdee773d6d3e05",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":18,
              "y":380},
            "size":{
              "width":112,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dddc02c7f4934d3299da4737afbb79c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":18,
                  "y":380},
                "size":{
                  "width":112,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pod盘点_1/u23.png"}},
{
          "id":"2fb77a5e875747b1bbc334e022b6005b",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":49},
            "size":{
              "width":182,
              "height":26}},
          "adaptiveStyles":{
}},
{
          "id":"547575e1536b4cd98df87bdc935b7201",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":20,
              "y":266},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac224a1be7b6401492b31dc6251f9a7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":20,
                  "y":266},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f965c9be3d8e43db9990023853d6891b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":262},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"cf05fdb1bc1644e7a005553982211ff5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":301},
            "size":{
              "width":92,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90e48546e31a440288fc45e92313d210",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":301},
                "size":{
                  "width":92,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f719b6e9a934665ba8331e240b57727",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":299},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"bbfcf3ef4c034af88b44dcd78c8e9456",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":20,
              "y":89},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f23d3df2cb9341af9aca211e19703181",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":20,
                  "y":89},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"657a7c4c2ad840eda37e0ea53e154562",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":85},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"59e8ff894d7a4b5b9b317d03abd2da4d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":377.5},
            "size":{
              "width":91,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 弹出窗口 打开 POD盘点扫描",
                      "target":{
                        "targetType":"page",
                        "url":"pod盘点扫描.html",
                        "includeVariables":true},
                      "linkType":"popup",
                      "popup":{
                        "left":100,
                        "top":100,
                        "width":500,
                        "height":500,
                        "toolbar":false,
                        "scrollbars":false,
                        "location":false,
                        "status":false,
                        "menubar":false,
                        "directories":false,
                        "resizable":false,
                        "centerwindow":true}}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "75fe507097a746b8af8f5173f0a6a5ee":{
      "scriptId":"u0"},
    "cd6c5d5dbec54d5685ad70e07432d118":{
      "scriptId":"u1"},
    "042dd2e526ca4f4ba372de0e7b5df8dd":{
      "scriptId":"u2"},
    "2ad9204b97a841189795c4ee8accc01e":{
      "scriptId":"u3"},
    "3a767f3b673f4a6490154748166a373e":{
      "scriptId":"u4"},
    "9db0867ab0c049ad8fc7ff93a66aa3c0":{
      "scriptId":"u5"},
    "0d8ee6dd870048e5a3614d852bb9d6a2":{
      "scriptId":"u6"},
    "73ea90dc493c42ea9486339832b8d955":{
      "scriptId":"u7"},
    "c2e117c4d18f4991bb7526b586a37e86":{
      "scriptId":"u8"},
    "b72bac2aa8d742328712c819f7aa9f28":{
      "scriptId":"u9"},
    "efe21db035dd491ca0397ccc151d10e8":{
      "scriptId":"u10"},
    "4d2c63bd5a1d4e989d7d7441caf46fe6":{
      "scriptId":"u11"},
    "0501c80546d34ac0bb4b1562bfbdcb66":{
      "scriptId":"u12"},
    "e3dbccbd0f2f44cb97241a03b11ce03f":{
      "scriptId":"u13"},
    "31d0be54fe924c07a7fd83285475f559":{
      "scriptId":"u14"},
    "3a46de3c461541fb998e22ef8452feca":{
      "scriptId":"u15"},
    "639d81e97ca1470ca9f3ce30ab84b166":{
      "scriptId":"u16"},
    "5c257e45aa4542349691a3d2d40d7e04":{
      "scriptId":"u17"},
    "4cdd0fef4f91455688da1004ad15618f":{
      "scriptId":"u18"},
    "70bc09f056cf4a1ba94f3f385a212e32":{
      "scriptId":"u19"},
    "fb8bd188139449be94bc3c7164973713":{
      "scriptId":"u20"},
    "719a020c5e984c468f960b17b01b9409":{
      "scriptId":"u21"},
    "8e851922beab423487697a00f21ef024":{
      "scriptId":"u22"},
    "579f9850356d457dacfdee773d6d3e05":{
      "scriptId":"u23"},
    "dddc02c7f4934d3299da4737afbb79c6":{
      "scriptId":"u24"},
    "2fb77a5e875747b1bbc334e022b6005b":{
      "scriptId":"u25"},
    "547575e1536b4cd98df87bdc935b7201":{
      "scriptId":"u26"},
    "ac224a1be7b6401492b31dc6251f9a7c":{
      "scriptId":"u27"},
    "f965c9be3d8e43db9990023853d6891b":{
      "scriptId":"u28"},
    "cf05fdb1bc1644e7a005553982211ff5":{
      "scriptId":"u29"},
    "90e48546e31a440288fc45e92313d210":{
      "scriptId":"u30"},
    "1f719b6e9a934665ba8331e240b57727":{
      "scriptId":"u31"},
    "bbfcf3ef4c034af88b44dcd78c8e9456":{
      "scriptId":"u32"},
    "f23d3df2cb9341af9aca211e19703181":{
      "scriptId":"u33"},
    "657a7c4c2ad840eda37e0ea53e154562":{
      "scriptId":"u34"},
    "59e8ff894d7a4b5b9b317d03abd2da4d":{
      "scriptId":"u35"}}});