$axure.loadCurrentPage({
  "url":"制单员-货物类型.html",
  "generationDate":new Date(1554888122020.89),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"cbe2272ebbfe49899e0a212b0caf7769",
    "type":"Axure:Page",
    "name":"制单员-货物类型",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"521d33d64c6e41adbd6a26534fba3786",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":51},
            "size":{
              "width":74,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6cf57adea71a4ab28f2fe0b1065f4579",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":94,
              "y":51},
            "size":{
              "width":74,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 弹出窗口 打开 添加",
                      "target":{
                        "targetType":"page",
                        "url":"添加_7.html",
                        "includeVariables":true},
                      "linkType":"popup",
                      "popup":{
                        "left":100,
                        "top":100,
                        "width":1000,
                        "height":800,
                        "toolbar":false,
                        "scrollbars":false,
                        "location":false,
                        "status":false,
                        "menubar":false,
                        "directories":false,
                        "resizable":false,
                        "centerwindow":true}}]}]}},
          "tabbable":true},
{
          "id":"bb681115a1964782aa83613e4c7cf74b",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":167},
            "size":{
              "width":704,
              "height":193}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d92f02f585d54377895deb18b9a7143f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "size":{
                  "width":69,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dbc2724bfc5240bcbc6f83a31048051a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":69,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/仓库信息/u19.png"}},
{
              "id":"c7ebaf67272f45a3886f00041c56659f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":36},
                "size":{
                  "width":69,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dfd0343b2daf46bebc33560c5820e5d1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":36},
                    "size":{
                      "width":69,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/仓库信息/u45.png"}},
{
              "id":"4622ed4198cb4701a736defd21f12f49",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":65},
                "size":{
                  "width":69,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1fc66bc213204ae09253e07d2bdeb0e6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":65},
                    "size":{
                      "width":69,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/仓库信息/u71.png"}},
{
              "id":"ed38e3e036184821945c1e8828049d94",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":69,
                  "y":0},
                "size":{
                  "width":71,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dcf8f7f15fe84b41b831e95a36ce509d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":69,
                      "y":0},
                    "size":{
                      "width":71,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u5.png"}},
{
              "id":"accc4c1003aa4586a80b17967cf3b099",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":69,
                  "y":36},
                "size":{
                  "width":71,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"44cf94437b9c40c5bae6b5a4e3a7c1fe",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":69,
                      "y":36},
                    "size":{
                      "width":71,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u31.png"}},
{
              "id":"60fe7e9aa8ce4275998887e0cb83ed49",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":69,
                  "y":65},
                "size":{
                  "width":71,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ef290064d6f6423aaae3d8340c410405",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":69,
                      "y":65},
                    "size":{
                      "width":71,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u57.png"}},
{
              "id":"543b5d67dc86450c845c041155d62c30",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":417,
                  "y":0},
                "size":{
                  "width":80,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8800594671d84723a978e64e6a7d5bbb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":417,
                      "y":0},
                    "size":{
                      "width":80,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/仓库信息/u23.png"}},
{
              "id":"0332331d245342cabd3abc35e866bbb5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":417,
                  "y":36},
                "size":{
                  "width":80,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ac30f36713a64752bab4264900ca9a8d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":417,
                      "y":36},
                    "size":{
                      "width":80,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/仓库信息/u49.png"}},
{
              "id":"fee46fb3e22a4dd6a106cf326c176e45",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":417,
                  "y":65},
                "size":{
                  "width":80,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a801bb7b548b4119b93c0f3c700f2723",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":417,
                      "y":65},
                    "size":{
                      "width":80,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/仓库信息/u75.png"}},
{
              "id":"fbf61af783ef4201aa2742ffb331ebc5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":140,
                  "y":0},
                "size":{
                  "width":70,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9bf7b52e50114395971353da8a92536f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":140,
                      "y":0},
                    "size":{
                      "width":70,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u13.png"}},
{
              "id":"0ee36bf30c1d45f2a5bdd2a62d4c3a6c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":140,
                  "y":36},
                "size":{
                  "width":70,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a73d01faa4cd43dab78193c4644444ca",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":140,
                      "y":36},
                    "size":{
                      "width":70,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u39.png"}},
{
              "id":"798e88e85af247a5a7cac2c7a69b2111",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":140,
                  "y":65},
                "size":{
                  "width":70,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a404ad85383446f2ab5e4aeb7397e922",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":140,
                      "y":65},
                    "size":{
                      "width":70,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u65.png"}},
{
              "id":"c63a317a80fb4a9e8a6cad783ac2b71c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":210,
                  "y":0},
                "size":{
                  "width":57,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a83f1e8f187e4bebaa256721982a69af",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":210,
                      "y":0},
                    "size":{
                      "width":57,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u15.png"}},
{
              "id":"1f0733b7edfa4292a47c9fad1d1c608e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":210,
                  "y":36},
                "size":{
                  "width":57,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"95231bf9a3104b05bc2f75ce181646b5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":210,
                      "y":36},
                    "size":{
                      "width":57,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u41.png"}},
{
              "id":"5f7ce8b397a1444790ef6f25cccc5992",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":210,
                  "y":65},
                "size":{
                  "width":57,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0f7315d7bc6849dd9ee2c5a36bfc57d5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":210,
                      "y":65},
                    "size":{
                      "width":57,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u67.png"}},
{
              "id":"271861146eb044bfb8b6898fac84f609",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":267,
                  "y":0},
                "size":{
                  "width":68,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b64275809a9c49649fa6fabd3fab1fdd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":267,
                      "y":0},
                    "size":{
                      "width":68,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u17.png"}},
{
              "id":"9209c1950dcd48d28b09a08c89ec03b5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":267,
                  "y":36},
                "size":{
                  "width":68,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5bfdef9a823547ec81e7e21ac7516a5d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":267,
                      "y":36},
                    "size":{
                      "width":68,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u43.png"}},
{
              "id":"0005a43b35a44e03ba1eafba1586e2d1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":267,
                  "y":65},
                "size":{
                  "width":68,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"06e452948ac943f4b5774dcdb2eb0290",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":267,
                      "y":65},
                    "size":{
                      "width":68,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u69.png"}},
{
              "id":"6345804cea1d4d228e31055ab62ab0f4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":335,
                  "y":0},
                "size":{
                  "width":82,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9dfe0bef9a004373a823b54542406373",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":335,
                      "y":0},
                    "size":{
                      "width":82,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u19.png"}},
{
              "id":"4d4ad961307f485ba9497afe0e4206df",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":335,
                  "y":36},
                "size":{
                  "width":82,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b1d8b75ea4e9466fb6147b889da23943",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":335,
                      "y":36},
                    "size":{
                      "width":82,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u45.png"}},
{
              "id":"569b81ed17734ace8f9ba314605d2a12",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":335,
                  "y":65},
                "size":{
                  "width":82,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"599cffc4af01446abbaf74cfc37e0d3d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":335,
                      "y":65},
                    "size":{
                      "width":82,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u71.png"}},
{
              "id":"892ee8875e934ca5b817bd379e43dbc3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":497,
                  "y":0},
                "size":{
                  "width":69,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a1844f690f1641eeb15b74e15eeaebd7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":497,
                      "y":0},
                    "size":{
                      "width":69,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/仓库信息/u19.png"}},
{
              "id":"fabafeb73a5d4fc999bf404a4da24971",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":497,
                  "y":36},
                "size":{
                  "width":69,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"75130c774a6b43238e3020fd3fd2dac8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":497,
                      "y":36},
                    "size":{
                      "width":69,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/仓库信息/u45.png"}},
{
              "id":"a745b7469d2e44528677fcca1bd3f4e2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":497,
                  "y":65},
                "size":{
                  "width":69,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5c32d603f96549eb9c5ea291c5e4be8a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":497,
                      "y":65},
                    "size":{
                      "width":69,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/仓库信息/u71.png"}},
{
              "id":"6b57799b2bf74fe78a768ebe36b93f39",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":566,
                  "y":0},
                "size":{
                  "width":69,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4c1c9279ff7b435490412d6890c7325a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":566,
                      "y":0},
                    "size":{
                      "width":69,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/仓库信息/u19.png"}},
{
              "id":"9d50a4b711594f2f954e93fb24f43347",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":566,
                  "y":36},
                "size":{
                  "width":69,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d569a8bb035c40e9b2f226eedd685daa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":566,
                      "y":36},
                    "size":{
                      "width":69,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/仓库信息/u45.png"}},
{
              "id":"d1bc41688a364a4f95bcb16818f81b67",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":566,
                  "y":65},
                "size":{
                  "width":69,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"88232289f41e4f6a94dc260886d77d90",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":566,
                      "y":65},
                    "size":{
                      "width":69,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/仓库信息/u71.png"}},
{
              "id":"77ffb073d59a46f3945d1cc9f9da0dee",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":635,
                  "y":0},
                "size":{
                  "width":69,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4b0ea517900b47c88c7ffb4f7324b223",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":635,
                      "y":0},
                    "size":{
                      "width":69,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u27.png"}},
{
              "id":"0e1517a35870403db0fb275ecd75f4c9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":635,
                  "y":36},
                "size":{
                  "width":69,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"174d5c6ad9c64ca6a816b0c5d082067f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":635,
                      "y":36},
                    "size":{
                      "width":69,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u53.png"}},
{
              "id":"4f37a7a1e66146ac8b71bcabaaf6911d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":635,
                  "y":65},
                "size":{
                  "width":69,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8bfb146f36054a689801180537931b6f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":635,
                      "y":65},
                    "size":{
                      "width":69,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u79.png"}},
{
              "id":"c8bf0c9a7c254e2f84f32a923fca648b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":105},
                "size":{
                  "width":69,
                  "height":44}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2094441e8eb14d7fb76a5b76cdbc3e4a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":105},
                    "size":{
                      "width":69,
                      "height":44}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/仓库信息/u97.png"}},
{
              "id":"e53a91ac5c0048f8b4c4e8bb39d7fd43",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":69,
                  "y":105},
                "size":{
                  "width":71,
                  "height":44}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"272c5319ea2f4746b27c92225fa04134",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":69,
                      "y":105},
                    "size":{
                      "width":71,
                      "height":44}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u83.png"}},
{
              "id":"835761a3ad9e421bb087a9fa315a8066",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":140,
                  "y":105},
                "size":{
                  "width":70,
                  "height":44}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"032ae7740a294a23a92678b7cbf33a7c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":140,
                      "y":105},
                    "size":{
                      "width":70,
                      "height":44}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u91.png"}},
{
              "id":"e2f5660162734d13851dbba98c20953d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":210,
                  "y":105},
                "size":{
                  "width":57,
                  "height":44}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2c17439b36b34ba498864ba5175eeca5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":210,
                      "y":105},
                    "size":{
                      "width":57,
                      "height":44}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u93.png"}},
{
              "id":"bf4365621bdc425fb82d59f612deaf94",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":267,
                  "y":105},
                "size":{
                  "width":68,
                  "height":44}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d33c2595b9984ef78fde6a2f57d68ccb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":267,
                      "y":105},
                    "size":{
                      "width":68,
                      "height":44}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u95.png"}},
{
              "id":"b5ea73a9a11b4ac8b6da47914c7365dd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":335,
                  "y":105},
                "size":{
                  "width":82,
                  "height":44}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8f178070201f4ecdb2912d573a2ee77d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":335,
                      "y":105},
                    "size":{
                      "width":82,
                      "height":44}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u97.png"}},
{
              "id":"5a019a3249cb4ab5b0c200f6d31311ce",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":417,
                  "y":105},
                "size":{
                  "width":80,
                  "height":44}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e21f801b858e4311bd259de82ba58deb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":417,
                      "y":105},
                    "size":{
                      "width":80,
                      "height":44}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/仓库信息/u101.png"}},
{
              "id":"63adf7df405448dcb4e48b5f79c17a20",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":497,
                  "y":105},
                "size":{
                  "width":69,
                  "height":44}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c0cd403b3b664df8a931005eb8e03854",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":497,
                      "y":105},
                    "size":{
                      "width":69,
                      "height":44}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/仓库信息/u97.png"}},
{
              "id":"da3c8a2f1ad04505bd4edb5703a51658",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":566,
                  "y":105},
                "size":{
                  "width":69,
                  "height":44}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4c62639386f64d5a989ccf9f6b804e8f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":566,
                      "y":105},
                    "size":{
                      "width":69,
                      "height":44}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/仓库信息/u97.png"}},
{
              "id":"98022b02fb0a46ec8f3e6d5409c4480f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":635,
                  "y":105},
                "size":{
                  "width":69,
                  "height":44}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c7a9fe3a51094ba2a08afbbddec7bad6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":635,
                      "y":105},
                    "size":{
                      "width":69,
                      "height":44}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u105.png"}},
{
              "id":"403a9d4ab3794ed5874f2a75590ac206",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":149},
                "size":{
                  "width":69,
                  "height":44}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c4d82b89167944b08c046eac3546a45d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":149},
                    "size":{
                      "width":69,
                      "height":44}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/仓库信息/u123.png"}},
{
              "id":"8e6ca908e95541e08be4c3a04f134356",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":69,
                  "y":149},
                "size":{
                  "width":71,
                  "height":44}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1935008348fd4c37a2a690c08a1545c4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":69,
                      "y":149},
                    "size":{
                      "width":71,
                      "height":44}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u109.png"}},
{
              "id":"1fe4da5aa83f4877a9ecfc29b74306e9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":140,
                  "y":149},
                "size":{
                  "width":70,
                  "height":44}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"97b0ca2e1a80423693d52744a328bf97",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":140,
                      "y":149},
                    "size":{
                      "width":70,
                      "height":44}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u117.png"}},
{
              "id":"bd2cde9101f445e083d777c9b4cd9814",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":210,
                  "y":149},
                "size":{
                  "width":57,
                  "height":44}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cde0643e2b3b4b48b6096164cc403764",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":210,
                      "y":149},
                    "size":{
                      "width":57,
                      "height":44}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u119.png"}},
{
              "id":"91d442a641b348caa6b7eb00020f4721",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":267,
                  "y":149},
                "size":{
                  "width":68,
                  "height":44}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0f6d9a9c757a4b709247ba7c271f86b2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":267,
                      "y":149},
                    "size":{
                      "width":68,
                      "height":44}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u121.png"}},
{
              "id":"0a370c9f558d44ee837ad38911b2fd95",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":335,
                  "y":149},
                "size":{
                  "width":82,
                  "height":44}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d0348a1680564698a4782d5a81ca1af3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":335,
                      "y":149},
                    "size":{
                      "width":82,
                      "height":44}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u123.png"}},
{
              "id":"d10a1705c0414b56ae4303885c808ad7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":417,
                  "y":149},
                "size":{
                  "width":80,
                  "height":44}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"75c25028bc1f4084a7e790e97c2e3c05",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":417,
                      "y":149},
                    "size":{
                      "width":80,
                      "height":44}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/仓库信息/u127.png"}},
{
              "id":"7e875a54236142008ceb05221d037944",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":497,
                  "y":149},
                "size":{
                  "width":69,
                  "height":44}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a789140632e748178be9f979e31f355b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":497,
                      "y":149},
                    "size":{
                      "width":69,
                      "height":44}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/仓库信息/u123.png"}},
{
              "id":"86644b49aeda4b8394ba5377ab6c4cd8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":566,
                  "y":149},
                "size":{
                  "width":69,
                  "height":44}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c83eb7ba88b44a57930ac9de71de0d24",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":566,
                      "y":149},
                    "size":{
                      "width":69,
                      "height":44}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/仓库信息/u123.png"}},
{
              "id":"56c543018ca84917be6f4517a3a27eac",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":635,
                  "y":149},
                "size":{
                  "width":69,
                  "height":44}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"035a7750d5e7416c888714bb69e57ad0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":635,
                      "y":149},
                    "size":{
                      "width":69,
                      "height":44}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库区维护/u131.png"}}]},
{
          "id":"ea2447452ad64ac1a951facf3450a3f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":101},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc7e7977964641cfb08f1f471bc7f5bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":101},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e1aecd22f344c6192cfcc1662343e9e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":99},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"65f1efaca39742a8ab9f5785a3c32b01",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":105},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"879e28fc108a478eba11661f4e7af064",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":105},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f8e29cbe3b644328ea3f5a249491719",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":101},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"0e74b82a08ea4fe9971583c69a057fbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":17,
              "y":19},
            "size":{
              "width":950,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29455abf687447728e4089a93046778d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":17,
                  "y":19},
                "size":{
                  "width":950,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库信息/u144.png"}},
{
          "id":"d06eaf3b0a9d4be1b23b39e0661dd730",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":23,
              "y":24},
            "size":{
              "width":122,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d80fcc1455664cbc8893c67f8a930f7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":23,
                  "y":24},
                "size":{
                  "width":122,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a423090085c45b883b16ca68a3cd6f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":128,
              "y":26},
            "size":{
              "width":62,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"113d939dd5254b8b871099d29c94012c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":128,
                  "y":26},
                "size":{
                  "width":62,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"933fbfcfbad64daea5d7920667c0fae1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":190,
              "y":26},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78feca239060472f97405ad1f714476e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":26},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e181c470546746e89ba6ee9a3720b2cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":304,
              "y":26},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c0e607f34014f57a3b3f7987e0dfc42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":304,
                  "y":26},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68878420b8c240e8ac76de80117921a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":420,
              "y":26},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13443f64a4644920a257174a743004a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":420,
                  "y":26},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6cf4552293941d6bdb576ffd91fbf92",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":530,
              "y":26},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3952bebb11b4547affe5bdb85db6eec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":530,
                  "y":26},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bdba9a3abc8643d2a869cc3294b3cac1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":641,
              "y":26},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34bb5a94da474416b852656d923b04a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":641,
                  "y":26},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c13f0913e61943a09d08fef1f6517ee4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":739,
              "y":26},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84eefb7fe3154a6c96f2e01991bf48d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":739,
                  "y":26},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fbc2824bd2fe4f37b1837ddab788eda9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":833,
              "y":26},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a34bfe2823604abeac9c711b47f0b15d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":833,
                  "y":26},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d7767f4a007348968d307612a6a49cab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":22,
              "y":470},
            "size":{
              "width":957,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61450ffdc3d240ab950ed6478b71a460",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":22,
                  "y":470},
                "size":{
                  "width":957,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库信息/u164.png"}},
{
          "id":"85153ef432034da2a2b0746ea7396766",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":836,
              "y":476},
            "size":{
              "width":134,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1dc05c78bc94dad956102bd618e0cf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":836,
                  "y":476},
                "size":{
                  "width":134,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b23386d3c1954bc59a8f5758a76758dc",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":51},
            "size":{
              "width":74,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c46e83c0d36f4c0c8f864f35491a29e0",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":242,
              "y":51},
            "size":{
              "width":74,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1ff96ad0d8ed4df3a445540aed0c3e55",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":315,
              "y":51},
            "size":{
              "width":74,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"bca151f6cc2647419a0881dc4335b017",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":388,
              "y":51},
            "size":{
              "width":74,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "521d33d64c6e41adbd6a26534fba3786":{
      "scriptId":"u0"},
    "6cf57adea71a4ab28f2fe0b1065f4579":{
      "scriptId":"u1"},
    "bb681115a1964782aa83613e4c7cf74b":{
      "scriptId":"u2"},
    "d92f02f585d54377895deb18b9a7143f":{
      "scriptId":"u3"},
    "dbc2724bfc5240bcbc6f83a31048051a":{
      "scriptId":"u4"},
    "ed38e3e036184821945c1e8828049d94":{
      "scriptId":"u5"},
    "dcf8f7f15fe84b41b831e95a36ce509d":{
      "scriptId":"u6"},
    "fbf61af783ef4201aa2742ffb331ebc5":{
      "scriptId":"u7"},
    "9bf7b52e50114395971353da8a92536f":{
      "scriptId":"u8"},
    "c63a317a80fb4a9e8a6cad783ac2b71c":{
      "scriptId":"u9"},
    "a83f1e8f187e4bebaa256721982a69af":{
      "scriptId":"u10"},
    "271861146eb044bfb8b6898fac84f609":{
      "scriptId":"u11"},
    "b64275809a9c49649fa6fabd3fab1fdd":{
      "scriptId":"u12"},
    "6345804cea1d4d228e31055ab62ab0f4":{
      "scriptId":"u13"},
    "9dfe0bef9a004373a823b54542406373":{
      "scriptId":"u14"},
    "543b5d67dc86450c845c041155d62c30":{
      "scriptId":"u15"},
    "8800594671d84723a978e64e6a7d5bbb":{
      "scriptId":"u16"},
    "892ee8875e934ca5b817bd379e43dbc3":{
      "scriptId":"u17"},
    "a1844f690f1641eeb15b74e15eeaebd7":{
      "scriptId":"u18"},
    "6b57799b2bf74fe78a768ebe36b93f39":{
      "scriptId":"u19"},
    "4c1c9279ff7b435490412d6890c7325a":{
      "scriptId":"u20"},
    "77ffb073d59a46f3945d1cc9f9da0dee":{
      "scriptId":"u21"},
    "4b0ea517900b47c88c7ffb4f7324b223":{
      "scriptId":"u22"},
    "c7ebaf67272f45a3886f00041c56659f":{
      "scriptId":"u23"},
    "dfd0343b2daf46bebc33560c5820e5d1":{
      "scriptId":"u24"},
    "accc4c1003aa4586a80b17967cf3b099":{
      "scriptId":"u25"},
    "44cf94437b9c40c5bae6b5a4e3a7c1fe":{
      "scriptId":"u26"},
    "0ee36bf30c1d45f2a5bdd2a62d4c3a6c":{
      "scriptId":"u27"},
    "a73d01faa4cd43dab78193c4644444ca":{
      "scriptId":"u28"},
    "1f0733b7edfa4292a47c9fad1d1c608e":{
      "scriptId":"u29"},
    "95231bf9a3104b05bc2f75ce181646b5":{
      "scriptId":"u30"},
    "9209c1950dcd48d28b09a08c89ec03b5":{
      "scriptId":"u31"},
    "5bfdef9a823547ec81e7e21ac7516a5d":{
      "scriptId":"u32"},
    "4d4ad961307f485ba9497afe0e4206df":{
      "scriptId":"u33"},
    "b1d8b75ea4e9466fb6147b889da23943":{
      "scriptId":"u34"},
    "0332331d245342cabd3abc35e866bbb5":{
      "scriptId":"u35"},
    "ac30f36713a64752bab4264900ca9a8d":{
      "scriptId":"u36"},
    "fabafeb73a5d4fc999bf404a4da24971":{
      "scriptId":"u37"},
    "75130c774a6b43238e3020fd3fd2dac8":{
      "scriptId":"u38"},
    "9d50a4b711594f2f954e93fb24f43347":{
      "scriptId":"u39"},
    "d569a8bb035c40e9b2f226eedd685daa":{
      "scriptId":"u40"},
    "0e1517a35870403db0fb275ecd75f4c9":{
      "scriptId":"u41"},
    "174d5c6ad9c64ca6a816b0c5d082067f":{
      "scriptId":"u42"},
    "4622ed4198cb4701a736defd21f12f49":{
      "scriptId":"u43"},
    "1fc66bc213204ae09253e07d2bdeb0e6":{
      "scriptId":"u44"},
    "60fe7e9aa8ce4275998887e0cb83ed49":{
      "scriptId":"u45"},
    "ef290064d6f6423aaae3d8340c410405":{
      "scriptId":"u46"},
    "798e88e85af247a5a7cac2c7a69b2111":{
      "scriptId":"u47"},
    "a404ad85383446f2ab5e4aeb7397e922":{
      "scriptId":"u48"},
    "5f7ce8b397a1444790ef6f25cccc5992":{
      "scriptId":"u49"},
    "0f7315d7bc6849dd9ee2c5a36bfc57d5":{
      "scriptId":"u50"},
    "0005a43b35a44e03ba1eafba1586e2d1":{
      "scriptId":"u51"},
    "06e452948ac943f4b5774dcdb2eb0290":{
      "scriptId":"u52"},
    "569b81ed17734ace8f9ba314605d2a12":{
      "scriptId":"u53"},
    "599cffc4af01446abbaf74cfc37e0d3d":{
      "scriptId":"u54"},
    "fee46fb3e22a4dd6a106cf326c176e45":{
      "scriptId":"u55"},
    "a801bb7b548b4119b93c0f3c700f2723":{
      "scriptId":"u56"},
    "a745b7469d2e44528677fcca1bd3f4e2":{
      "scriptId":"u57"},
    "5c32d603f96549eb9c5ea291c5e4be8a":{
      "scriptId":"u58"},
    "d1bc41688a364a4f95bcb16818f81b67":{
      "scriptId":"u59"},
    "88232289f41e4f6a94dc260886d77d90":{
      "scriptId":"u60"},
    "4f37a7a1e66146ac8b71bcabaaf6911d":{
      "scriptId":"u61"},
    "8bfb146f36054a689801180537931b6f":{
      "scriptId":"u62"},
    "c8bf0c9a7c254e2f84f32a923fca648b":{
      "scriptId":"u63"},
    "2094441e8eb14d7fb76a5b76cdbc3e4a":{
      "scriptId":"u64"},
    "e53a91ac5c0048f8b4c4e8bb39d7fd43":{
      "scriptId":"u65"},
    "272c5319ea2f4746b27c92225fa04134":{
      "scriptId":"u66"},
    "835761a3ad9e421bb087a9fa315a8066":{
      "scriptId":"u67"},
    "032ae7740a294a23a92678b7cbf33a7c":{
      "scriptId":"u68"},
    "e2f5660162734d13851dbba98c20953d":{
      "scriptId":"u69"},
    "2c17439b36b34ba498864ba5175eeca5":{
      "scriptId":"u70"},
    "bf4365621bdc425fb82d59f612deaf94":{
      "scriptId":"u71"},
    "d33c2595b9984ef78fde6a2f57d68ccb":{
      "scriptId":"u72"},
    "b5ea73a9a11b4ac8b6da47914c7365dd":{
      "scriptId":"u73"},
    "8f178070201f4ecdb2912d573a2ee77d":{
      "scriptId":"u74"},
    "5a019a3249cb4ab5b0c200f6d31311ce":{
      "scriptId":"u75"},
    "e21f801b858e4311bd259de82ba58deb":{
      "scriptId":"u76"},
    "63adf7df405448dcb4e48b5f79c17a20":{
      "scriptId":"u77"},
    "c0cd403b3b664df8a931005eb8e03854":{
      "scriptId":"u78"},
    "da3c8a2f1ad04505bd4edb5703a51658":{
      "scriptId":"u79"},
    "4c62639386f64d5a989ccf9f6b804e8f":{
      "scriptId":"u80"},
    "98022b02fb0a46ec8f3e6d5409c4480f":{
      "scriptId":"u81"},
    "c7a9fe3a51094ba2a08afbbddec7bad6":{
      "scriptId":"u82"},
    "403a9d4ab3794ed5874f2a75590ac206":{
      "scriptId":"u83"},
    "c4d82b89167944b08c046eac3546a45d":{
      "scriptId":"u84"},
    "8e6ca908e95541e08be4c3a04f134356":{
      "scriptId":"u85"},
    "1935008348fd4c37a2a690c08a1545c4":{
      "scriptId":"u86"},
    "1fe4da5aa83f4877a9ecfc29b74306e9":{
      "scriptId":"u87"},
    "97b0ca2e1a80423693d52744a328bf97":{
      "scriptId":"u88"},
    "bd2cde9101f445e083d777c9b4cd9814":{
      "scriptId":"u89"},
    "cde0643e2b3b4b48b6096164cc403764":{
      "scriptId":"u90"},
    "91d442a641b348caa6b7eb00020f4721":{
      "scriptId":"u91"},
    "0f6d9a9c757a4b709247ba7c271f86b2":{
      "scriptId":"u92"},
    "0a370c9f558d44ee837ad38911b2fd95":{
      "scriptId":"u93"},
    "d0348a1680564698a4782d5a81ca1af3":{
      "scriptId":"u94"},
    "d10a1705c0414b56ae4303885c808ad7":{
      "scriptId":"u95"},
    "75c25028bc1f4084a7e790e97c2e3c05":{
      "scriptId":"u96"},
    "7e875a54236142008ceb05221d037944":{
      "scriptId":"u97"},
    "a789140632e748178be9f979e31f355b":{
      "scriptId":"u98"},
    "86644b49aeda4b8394ba5377ab6c4cd8":{
      "scriptId":"u99"},
    "c83eb7ba88b44a57930ac9de71de0d24":{
      "scriptId":"u100"},
    "56c543018ca84917be6f4517a3a27eac":{
      "scriptId":"u101"},
    "035a7750d5e7416c888714bb69e57ad0":{
      "scriptId":"u102"},
    "ea2447452ad64ac1a951facf3450a3f6":{
      "scriptId":"u103"},
    "cc7e7977964641cfb08f1f471bc7f5bf":{
      "scriptId":"u104"},
    "5e1aecd22f344c6192cfcc1662343e9e":{
      "scriptId":"u105"},
    "65f1efaca39742a8ab9f5785a3c32b01":{
      "scriptId":"u106"},
    "879e28fc108a478eba11661f4e7af064":{
      "scriptId":"u107"},
    "7f8e29cbe3b644328ea3f5a249491719":{
      "scriptId":"u108"},
    "0e74b82a08ea4fe9971583c69a057fbe":{
      "scriptId":"u109"},
    "29455abf687447728e4089a93046778d":{
      "scriptId":"u110"},
    "d06eaf3b0a9d4be1b23b39e0661dd730":{
      "scriptId":"u111"},
    "d80fcc1455664cbc8893c67f8a930f7d":{
      "scriptId":"u112"},
    "8a423090085c45b883b16ca68a3cd6f1":{
      "scriptId":"u113"},
    "113d939dd5254b8b871099d29c94012c":{
      "scriptId":"u114"},
    "933fbfcfbad64daea5d7920667c0fae1":{
      "scriptId":"u115"},
    "78feca239060472f97405ad1f714476e":{
      "scriptId":"u116"},
    "e181c470546746e89ba6ee9a3720b2cc":{
      "scriptId":"u117"},
    "2c0e607f34014f57a3b3f7987e0dfc42":{
      "scriptId":"u118"},
    "68878420b8c240e8ac76de80117921a5":{
      "scriptId":"u119"},
    "13443f64a4644920a257174a743004a2":{
      "scriptId":"u120"},
    "d6cf4552293941d6bdb576ffd91fbf92":{
      "scriptId":"u121"},
    "a3952bebb11b4547affe5bdb85db6eec":{
      "scriptId":"u122"},
    "bdba9a3abc8643d2a869cc3294b3cac1":{
      "scriptId":"u123"},
    "34bb5a94da474416b852656d923b04a6":{
      "scriptId":"u124"},
    "c13f0913e61943a09d08fef1f6517ee4":{
      "scriptId":"u125"},
    "84eefb7fe3154a6c96f2e01991bf48d3":{
      "scriptId":"u126"},
    "fbc2824bd2fe4f37b1837ddab788eda9":{
      "scriptId":"u127"},
    "a34bfe2823604abeac9c711b47f0b15d":{
      "scriptId":"u128"},
    "d7767f4a007348968d307612a6a49cab":{
      "scriptId":"u129"},
    "61450ffdc3d240ab950ed6478b71a460":{
      "scriptId":"u130"},
    "85153ef432034da2a2b0746ea7396766":{
      "scriptId":"u131"},
    "e1dc05c78bc94dad956102bd618e0cf8":{
      "scriptId":"u132"},
    "b23386d3c1954bc59a8f5758a76758dc":{
      "scriptId":"u133"},
    "c46e83c0d36f4c0c8f864f35491a29e0":{
      "scriptId":"u134"},
    "1ff96ad0d8ed4df3a445540aed0c3e55":{
      "scriptId":"u135"},
    "bca151f6cc2647419a0881dc4335b017":{
      "scriptId":"u136"}}});