$axure.loadCurrentPage({
  "url":"__-icdc.html",
  "generationDate":new Date(1554888135225.59),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"1fc696b1b424443ea3ae63beed5dc22b",
    "type":"Axure:Page",
    "name":"收货-ICDC",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bf7a0056e90440739af5167d35755af4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":35,
              "y":94},
            "size":{
              "width":72,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25657b4e691249d7811702935e22ec86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":35,
                  "y":94},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e780849cbaf64cc2aff0d6104731ed3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":35,
              "y":167},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd129a61ab1540b693518abb2a1026a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":35,
                  "y":167},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e137c79056a4680a0dc82f8226843c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":35,
              "y":207},
            "size":{
              "width":80,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd2d78f2deda4085a1407f78f23c2b92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":35,
                  "y":207},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"901ca92d083c4e1098310cbba024b6bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":35,
              "y":248},
            "size":{
              "width":80,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28785feed7b246bb932ad126497c76dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":35,
                  "y":248},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe39aeec604a43dc86fe32ae077b9e1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":35,
              "y":128},
            "size":{
              "width":80,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd76133a1679438396f1fabf43837762",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":35,
                  "y":128},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ed7804e6e1745739c640f380d24b659",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3300},
            "location":{
              "x":125,
              "y":296},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"bf24cbd8ce234a84884de32434e73c5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "size":{
              "width":305,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d718a9a487534c6a931af6cf11ffa5b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "size":{
                  "width":305,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u6.png"}},
{
          "id":"ad5c749134db420e9920321357898dba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":4,
              "y":5},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b08564bf5834ff7ab2cf44a3cf3bd4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":4,
                  "y":5},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e46477c2b1c747839697362938291b1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":136,
              "y":7},
            "size":{
              "width":138,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bde6750811c74b6b921f9fa78943e894",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":136,
                  "y":7},
                "size":{
                  "width":138,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40c23ca584ea41f9a959438c038d1f3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":1,
              "y":451},
            "size":{
              "width":308,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e531f248a28a426d90847bc646298b59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":1,
                  "y":451},
                "size":{
                  "width":308,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u12.png"}},
{
          "id":"a9e99bfe325f403ebc65538792e27839",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":144,
              "y":457},
            "size":{
              "width":162,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd38af1cec3440b081da20a7d49231f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":144,
                  "y":457},
                "size":{
                  "width":162,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99ff816dd1e949e387d640c12723a76d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":169,
              "y":365},
            "size":{
              "width":92,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"a2c69ff014584dea8d6d4b9aaec5c1cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":55,
              "y":365},
            "size":{
              "width":80,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"feb6f059aebe450fb764efda85a90e57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":55,
                  "y":365},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57c4e850508f45758d3918e63c1e6d34",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":369},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e7ab485419d4fb1a70921d3ab793d53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":35,
                  "y":369},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"fce58fd2b3784ae9bd0e3e0739a2d425",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":35,
              "y":58},
            "size":{
              "width":59,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d493ec30285642a087adb1514f5c4c1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":35,
                  "y":58},
                "size":{
                  "width":59,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f1cf50223c7d44a685749cc23bb8ce7d",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":125,
              "y":59},
            "size":{
              "width":180,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"f268b900f0774f06847a1facd9ef39b7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":125,
              "y":93},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"344bab2bc6cb49a2a6fb95db0eb0f913",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":125,
              "y":130},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4484388aa411436383a4f681785a3bed",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":125,
              "y":168},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onTextChange":{
              "description":"OnTextChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"scrollToWidget",
                      "description":"滚动到 (下拉列表框) (仅垂直)",
                      "objectPath":["f1cf50223c7d44a685749cc23bb8ce7d"],
                      "options":{
                        "direction":"vertical"}},
{
                      "action":"fadeWidget",
                      "description":"显示 (下拉列表框)",
                      "objectsToFades":[{
                          "objectPath":["f1cf50223c7d44a685749cc23bb8ce7d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"scrollToWidget",
                      "description":"滚动到 (文本框) (仅垂直)",
                      "objectPath":["f268b900f0774f06847a1facd9ef39b7"],
                      "options":{
                        "direction":"vertical"}},
{
                      "action":"fadeWidget",
                      "description":"显示 (文本框)",
                      "objectsToFades":[{
                          "objectPath":["f268b900f0774f06847a1facd9ef39b7"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"scrollToWidget",
                      "description":"滚动到 (文本框) (仅垂直)",
                      "objectPath":["19c7b69f4a0144299a41fffc31d713a9"],
                      "options":{
                        "direction":"vertical"}},
{
                      "action":"fadeWidget",
                      "description":"显示 (文本框)",
                      "objectsToFades":[{
                          "objectPath":["19c7b69f4a0144299a41fffc31d713a9"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"scrollToWidget",
                      "description":"滚动到 (文本框) (仅垂直)",
                      "objectPath":["44fb33bee2324386b44f1daaf5536dd4"],
                      "options":{
                        "direction":"vertical"}},
{
                      "action":"fadeWidget",
                      "description":"显示 (文本框)",
                      "objectsToFades":[{
                          "objectPath":["44fb33bee2324386b44f1daaf5536dd4"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}}},
{
          "id":"19c7b69f4a0144299a41fffc31d713a9",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":125,
              "y":206},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"44fb33bee2324386b44f1daaf5536dd4",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":125,
              "y":248},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4e0efacdf43047a6913520ab62e6e71f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCCC},
            "location":{
              "x":450,
              "y":600},
            "size":{
              "width":165,
              "height":105}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b15679d6d29d4b659b7bc89272165953",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCCC},
                "location":{
                  "x":450,
                  "y":600},
                "size":{
                  "width":165,
                  "height":105}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__-icdc/u34.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "bf7a0056e90440739af5167d35755af4":{
      "scriptId":"u0"},
    "25657b4e691249d7811702935e22ec86":{
      "scriptId":"u1"},
    "e780849cbaf64cc2aff0d6104731ed3d":{
      "scriptId":"u2"},
    "bd129a61ab1540b693518abb2a1026a5":{
      "scriptId":"u3"},
    "7e137c79056a4680a0dc82f8226843c4":{
      "scriptId":"u4"},
    "dd2d78f2deda4085a1407f78f23c2b92":{
      "scriptId":"u5"},
    "901ca92d083c4e1098310cbba024b6bf":{
      "scriptId":"u6"},
    "28785feed7b246bb932ad126497c76dd":{
      "scriptId":"u7"},
    "fe39aeec604a43dc86fe32ae077b9e1e":{
      "scriptId":"u8"},
    "fd76133a1679438396f1fabf43837762":{
      "scriptId":"u9"},
    "2ed7804e6e1745739c640f380d24b659":{
      "scriptId":"u10"},
    "bf24cbd8ce234a84884de32434e73c5f":{
      "scriptId":"u11"},
    "d718a9a487534c6a931af6cf11ffa5b9":{
      "scriptId":"u12"},
    "ad5c749134db420e9920321357898dba":{
      "scriptId":"u13"},
    "9b08564bf5834ff7ab2cf44a3cf3bd4e":{
      "scriptId":"u14"},
    "e46477c2b1c747839697362938291b1a":{
      "scriptId":"u15"},
    "bde6750811c74b6b921f9fa78943e894":{
      "scriptId":"u16"},
    "40c23ca584ea41f9a959438c038d1f3a":{
      "scriptId":"u17"},
    "e531f248a28a426d90847bc646298b59":{
      "scriptId":"u18"},
    "a9e99bfe325f403ebc65538792e27839":{
      "scriptId":"u19"},
    "bd38af1cec3440b081da20a7d49231f0":{
      "scriptId":"u20"},
    "99ff816dd1e949e387d640c12723a76d":{
      "scriptId":"u21"},
    "a2c69ff014584dea8d6d4b9aaec5c1cf":{
      "scriptId":"u22"},
    "feb6f059aebe450fb764efda85a90e57":{
      "scriptId":"u23"},
    "57c4e850508f45758d3918e63c1e6d34":{
      "scriptId":"u24"},
    "5e7ab485419d4fb1a70921d3ab793d53":{
      "scriptId":"u25"},
    "fce58fd2b3784ae9bd0e3e0739a2d425":{
      "scriptId":"u26"},
    "d493ec30285642a087adb1514f5c4c1c":{
      "scriptId":"u27"},
    "f1cf50223c7d44a685749cc23bb8ce7d":{
      "scriptId":"u28"},
    "f268b900f0774f06847a1facd9ef39b7":{
      "scriptId":"u29"},
    "344bab2bc6cb49a2a6fb95db0eb0f913":{
      "scriptId":"u30"},
    "4484388aa411436383a4f681785a3bed":{
      "scriptId":"u31"},
    "19c7b69f4a0144299a41fffc31d713a9":{
      "scriptId":"u32"},
    "44fb33bee2324386b44f1daaf5536dd4":{
      "scriptId":"u33"},
    "4e0efacdf43047a6913520ab62e6e71f":{
      "scriptId":"u34"},
    "b15679d6d29d4b659b7bc89272165953":{
      "scriptId":"u35"}}});