$axure.loadCurrentPage({
  "url":"循环盘点_1.html",
  "generationDate":new Date(1554888136871.19),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"8fc84dc90e5d4b1c8bfb258f3dad3fb1",
    "type":"Axure:Page",
    "name":"循环盘点",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1036376db8234ebd9b7a3758ec5a6736",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":125},
            "size":{
              "width":92,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc0784c848a54698a7c9d40c6fe914b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":125},
                "size":{
                  "width":92,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a80684ad4a51430d9e3a6190b886c6bb",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":125},
            "size":{
              "width":180,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"448ec614171141fbba47e6236ac21a70",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "size":{
              "width":305,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95c83ec844f44aa1b21abcc85a896f85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "size":{
                  "width":305,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u6.png"}},
{
          "id":"6ffdbe64f3b84fabafdd89021097219a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":4,
              "y":5},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f26d322fb0e74a6ab3ef68fcef9cf4a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":4,
                  "y":5},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b115e9e5d8774007939e2c017e13472e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":124,
              "y":7},
            "size":{
              "width":181,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db97159c58764331bc4edcc621d21249",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":124,
                  "y":7},
                "size":{
                  "width":181,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04943119def14b52921098968e92499a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":1,
              "y":451},
            "size":{
              "width":308,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9a4c79f04334606ae5db3a03364a046",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":1,
                  "y":451},
                "size":{
                  "width":308,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u12.png"}},
{
          "id":"4daafcebfb084af09f6f2eaddf8da564",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":144,
              "y":457},
            "size":{
              "width":162,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"581a04fd6ab842188df5ece8d51c4767",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":144,
                  "y":457},
                "size":{
                  "width":162,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"026f1cafe4874cd4b00b86fadc14c94f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":49},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6e974bd4e5a4e3b8644a04473cb0b86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":49},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a4b2e46931be4043bde0910895d5be05",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCCC},
            "location":{
              "x":355,
              "y":24},
            "size":{
              "width":475,
              "height":416}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb468335715a49b7a60cd58e6b64e136",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCCC},
                "location":{
                  "x":355,
                  "y":24},
                "size":{
                  "width":475,
                  "height":416}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/循环盘点_1/u15.png"}},
{
          "id":"0cbec80f3c4a48fea3ee1c9b0edc6e0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":170},
            "size":{
              "width":92,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b65352f4d204f3d9f2e267abce5f0dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":170},
                "size":{
                  "width":92,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7dbadd829a35482a97751e6c814a1b34",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":182},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1ad3f3b1b0c549efa4ae1448427c0f9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":16,
              "y":220},
            "size":{
              "width":92,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d2dd4cf4b90404aade21b43dfbc1e01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":16,
                  "y":220},
                "size":{
                  "width":92,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a8ee39fb2db4933941d8248289ccfdc",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":219},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"63425043add140888b65a2425d544234",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":18,
              "y":380},
            "size":{
              "width":112,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42f2354e69e34c279cfd2dd421e49c0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":18,
                  "y":380},
                "size":{
                  "width":112,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pod盘点_1/u23.png"}},
{
          "id":"c1e009f7da0a4bd0864e58255f5e5d40",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":49},
            "size":{
              "width":182,
              "height":26}},
          "adaptiveStyles":{
}},
{
          "id":"7498e95dcf5948efb61ca2adfb006302",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":20,
              "y":266},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7de1af381173441c8c8bc28875ec1fa2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":20,
                  "y":266},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e85289c9dad249078b5242e4dbf536f3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":262},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ae54c8e40d344855ae749dde21997102",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":301},
            "size":{
              "width":92,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f301133d96f48c49b616adb6f0f27b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":301},
                "size":{
                  "width":92,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e531cba0aecc48a28a50ee9def4f802e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":299},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b380711c5d854e92924a9597f4b8e3aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":20,
              "y":89},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"011bfd8ef21c4905a41a8ac2104fe284",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":20,
                  "y":89},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c00356fbf22844dc82f6c1bf5f295596",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":85},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"89cd9f24a9ad4b09bd21be55affd38fa",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":377.5},
            "size":{
              "width":91,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 弹出窗口 打开 循环盘点扫描",
                      "target":{
                        "targetType":"page",
                        "url":"循环盘点扫描.html",
                        "includeVariables":true},
                      "linkType":"popup",
                      "popup":{
                        "left":100,
                        "top":100,
                        "width":500,
                        "height":500,
                        "toolbar":false,
                        "scrollbars":false,
                        "location":false,
                        "status":false,
                        "menubar":false,
                        "directories":false,
                        "resizable":false,
                        "centerwindow":true}}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "1036376db8234ebd9b7a3758ec5a6736":{
      "scriptId":"u0"},
    "cc0784c848a54698a7c9d40c6fe914b6":{
      "scriptId":"u1"},
    "a80684ad4a51430d9e3a6190b886c6bb":{
      "scriptId":"u2"},
    "448ec614171141fbba47e6236ac21a70":{
      "scriptId":"u3"},
    "95c83ec844f44aa1b21abcc85a896f85":{
      "scriptId":"u4"},
    "6ffdbe64f3b84fabafdd89021097219a":{
      "scriptId":"u5"},
    "f26d322fb0e74a6ab3ef68fcef9cf4a1":{
      "scriptId":"u6"},
    "b115e9e5d8774007939e2c017e13472e":{
      "scriptId":"u7"},
    "db97159c58764331bc4edcc621d21249":{
      "scriptId":"u8"},
    "04943119def14b52921098968e92499a":{
      "scriptId":"u9"},
    "f9a4c79f04334606ae5db3a03364a046":{
      "scriptId":"u10"},
    "4daafcebfb084af09f6f2eaddf8da564":{
      "scriptId":"u11"},
    "581a04fd6ab842188df5ece8d51c4767":{
      "scriptId":"u12"},
    "026f1cafe4874cd4b00b86fadc14c94f":{
      "scriptId":"u13"},
    "f6e974bd4e5a4e3b8644a04473cb0b86":{
      "scriptId":"u14"},
    "a4b2e46931be4043bde0910895d5be05":{
      "scriptId":"u15"},
    "bb468335715a49b7a60cd58e6b64e136":{
      "scriptId":"u16"},
    "0cbec80f3c4a48fea3ee1c9b0edc6e0b":{
      "scriptId":"u17"},
    "3b65352f4d204f3d9f2e267abce5f0dd":{
      "scriptId":"u18"},
    "7dbadd829a35482a97751e6c814a1b34":{
      "scriptId":"u19"},
    "1ad3f3b1b0c549efa4ae1448427c0f9d":{
      "scriptId":"u20"},
    "0d2dd4cf4b90404aade21b43dfbc1e01":{
      "scriptId":"u21"},
    "1a8ee39fb2db4933941d8248289ccfdc":{
      "scriptId":"u22"},
    "63425043add140888b65a2425d544234":{
      "scriptId":"u23"},
    "42f2354e69e34c279cfd2dd421e49c0c":{
      "scriptId":"u24"},
    "c1e009f7da0a4bd0864e58255f5e5d40":{
      "scriptId":"u25"},
    "7498e95dcf5948efb61ca2adfb006302":{
      "scriptId":"u26"},
    "7de1af381173441c8c8bc28875ec1fa2":{
      "scriptId":"u27"},
    "e85289c9dad249078b5242e4dbf536f3":{
      "scriptId":"u28"},
    "ae54c8e40d344855ae749dde21997102":{
      "scriptId":"u29"},
    "0f301133d96f48c49b616adb6f0f27b0":{
      "scriptId":"u30"},
    "e531cba0aecc48a28a50ee9def4f802e":{
      "scriptId":"u31"},
    "b380711c5d854e92924a9597f4b8e3aa":{
      "scriptId":"u32"},
    "011bfd8ef21c4905a41a8ac2104fe284":{
      "scriptId":"u33"},
    "c00356fbf22844dc82f6c1bf5f295596":{
      "scriptId":"u34"},
    "89cd9f24a9ad4b09bd21be55affd38fa":{
      "scriptId":"u35"}}});