$axure.loadCurrentPage({
  "url":"new_page_2.html",
  "generationDate":new Date(1554888137825.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"a4211904c2c94f37bb17933f71140719",
    "type":"Axure:Page",
    "name":"New Page 2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"03d061f28f1d44dea47e89bcbefd8b1d",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":112},
            "size":{
              "width":290,
              "height":280}},
          "adaptiveStyles":{
}},
{
          "id":"4bbb14a796c04e528ca5bbc86a676066",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":22,
              "y":14},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"392b6d7547dc481f84e07dcfe84d1962",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":14},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18b5e31089fd495d987a3494bfeb185f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":166,
              "y":16},
            "size":{
              "width":164,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80bfff5e789c495f85965fa223471215",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":166,
                  "y":16},
                "size":{
                  "width":164,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b0690dd4c504a56a4231b8615227d6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":40,
              "y":64},
            "size":{
              "width":83,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42c6d08b91fd4ba4911539857a412dc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":40,
                  "y":64},
                "size":{
                  "width":83,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"508d45a077ca42bb930c002b5db59ddd",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":63},
            "size":{
              "width":178,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"07adea2f9bbf4cd29ab4ce654727ec87",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":121,
              "y":409},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f3001911bd1e49dea9642c7d4ff8b0da",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":112},
            "size":{
              "width":275,
              "height":252}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b60c89b381bb49e9a9e5f36a777af9fb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":43,
                  "y":0},
                "size":{
                  "width":81,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7113888f6c564624892394404a667887",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":43,
                      "y":0},
                    "size":{
                      "width":81,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平库拣货/u20.png"}},
{
              "id":"03a07403abee469dbbbf6bead7438275",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":124,
                  "y":0},
                "size":{
                  "width":71,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fb541d4c26b748c38580b0bf8c26bd47",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":124,
                      "y":0},
                    "size":{
                      "width":71,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平库拣货/u22.png"}},
{
              "id":"e67919e5a7c44be8ae3e6702565a5460",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":195,
                  "y":0},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3e0e00b51d6e45eab5d23376ad5a476d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":195,
                      "y":0},
                    "size":{
                      "width":80,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平库拣货/u24.png"}},
{
              "id":"bcedc962f1604d97b7d871093fd838f3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":43,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"355cd4b458764edf88963b59d6e274c8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":43,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平库拣货/u18.png"}},
{
              "id":"9235ac091e8140b1b08e7e40387f1262",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":232},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0c437210b14040b18c5f26a37c5af59b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":232},
                    "size":{
                      "width":43,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库存交易查询/u301.png"}},
{
              "id":"4243086ff4274e8ba8d85d9f786a2a4d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":43,
                  "y":232},
                "size":{
                  "width":81,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"775a80ae268740b98c1b1cf830050a9d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":43,
                      "y":232},
                    "size":{
                      "width":81,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/cdc收货汇总/u61.png"}},
{
              "id":"a80ef40ac09e437498d83ba82c2a0081",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":124,
                  "y":232},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d2cb1136dc7440bba7572531dc72234c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":124,
                      "y":232},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/月台维护/u125.png"}},
{
              "id":"5a4b6d5fd7de4583b9b2d31b56c35c0c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":195,
                  "y":232},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d019b2965636473881b8f1ed8bb9e594",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":195,
                      "y":232},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平库拣货/u112.png"}},
{
              "id":"3b04539701f14806844626f5282c7ffb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":192},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"044fafa0900e4ac191482bfe3a597038",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":192},
                    "size":{
                      "width":43,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库存交易查询/u261.png"}},
{
              "id":"333d24fea00e47e79b25e53b417f01ac",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":43,
                  "y":192},
                "size":{
                  "width":81,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a527d5a0de6a4875911bc91b386e9ecc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":43,
                      "y":192},
                    "size":{
                      "width":81,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/cdc收货汇总/u31.png"}},
{
              "id":"14c2e53fae4947748f61c66a0d447b55",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":124,
                  "y":192},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a4caef54993b4e38a854cd38fe369aeb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":124,
                      "y":192},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/月台维护/u35.png"}},
{
              "id":"50e4bea4e3c640128f00ae5556353cdb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":195,
                  "y":192},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a3077cc648954318a8262f0bbe7ed937",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":195,
                      "y":192},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平库拣货/u40.png"}},
{
              "id":"275d1a53cade4aaa8e88c1ece48f6a48",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":172},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a63db3ff088b46849888c4008135c0e6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":172},
                    "size":{
                      "width":43,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库存交易查询/u261.png"}},
{
              "id":"7d9c758cac554d18a36ebca3a2efa720",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":43,
                  "y":172},
                "size":{
                  "width":81,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c2655808360840c9ae75da608ec58325",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":43,
                      "y":172},
                    "size":{
                      "width":81,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/cdc收货汇总/u31.png"}},
{
              "id":"1d880682dd2b470a9b26a28c21fd25ed",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":124,
                  "y":172},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8ed26bfa333544e49a46ee10e771f29b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":124,
                      "y":172},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/月台维护/u35.png"}},
{
              "id":"26f22123729a45f1b26e980d623fddc6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":195,
                  "y":172},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"351ada4cb6ef4000af047b65eca9cfd6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":195,
                      "y":172},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平库拣货/u40.png"}},
{
              "id":"8ba5f7d560f64865884d7494bd0d516c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":152},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3d77fd01a34c496e82819e0c00bb5382",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":152},
                    "size":{
                      "width":43,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库存交易查询/u261.png"}},
{
              "id":"8ad2c93381e743a3b4c23a3a2c53df68",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":43,
                  "y":152},
                "size":{
                  "width":81,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"699ec50709a24bc5a6632c6b0fe79ad8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":43,
                      "y":152},
                    "size":{
                      "width":81,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/cdc收货汇总/u31.png"}},
{
              "id":"4ae587949c8147988d245da3780053c7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":124,
                  "y":152},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"43cbe774a59f4271b6ae28a47c18b326",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":124,
                      "y":152},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/月台维护/u35.png"}},
{
              "id":"409edf0d454d4a3db7253e4e35c0282e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":195,
                  "y":152},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"17ef998afe4146a5bfd0e5e9fb2872fd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":195,
                      "y":152},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平库拣货/u40.png"}},
{
              "id":"89df3215bbaf4157bfc9d13beaec8d76",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":132},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dc936177a79347ff9fa5f1394531cbdc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":132},
                    "size":{
                      "width":43,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库存交易查询/u261.png"}},
{
              "id":"02da781599c348fdaee31c1a8a85c17e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":43,
                  "y":132},
                "size":{
                  "width":81,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"75ffac1798374bf391aae4d9600389a9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":43,
                      "y":132},
                    "size":{
                      "width":81,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/cdc收货汇总/u31.png"}},
{
              "id":"142a425cbc9246e2a0d3ac7e5c9b9226",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":124,
                  "y":132},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"853e1824aee641979cebc9470cabef56",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":124,
                      "y":132},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/月台维护/u35.png"}},
{
              "id":"0f9cd751767940098ef86510ff5fb538",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":195,
                  "y":132},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"560cd5351bd54f21894d453f9b4466dd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":195,
                      "y":132},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平库拣货/u40.png"}},
{
              "id":"3c9cbd2c774447c7b5c60e7a9a3d8d12",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":112},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b917576612fe4c999caf250de7bffe58",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":112},
                    "size":{
                      "width":43,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库存交易查询/u261.png"}},
{
              "id":"36952f0edcc841948f448b5b3920442a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":43,
                  "y":112},
                "size":{
                  "width":81,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b365f245ebbd4c64828c2eeb1129e5c1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":43,
                      "y":112},
                    "size":{
                      "width":81,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/cdc收货汇总/u31.png"}},
{
              "id":"3caac988967c4f1e8e88640b6945e183",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":124,
                  "y":112},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e0c003fbc70442589e37c883450a471a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":124,
                      "y":112},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/月台维护/u35.png"}},
{
              "id":"3082d4ac45cf4596a4f96a722f3c397b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":195,
                  "y":112},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1c6ab98289724740adb680173c6e6830",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":195,
                      "y":112},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平库拣货/u40.png"}},
{
              "id":"8895445d43d7451594d3c76326427ecc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":212},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"049c1f3ce8ed41f0872db73dc376aa71",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":212},
                    "size":{
                      "width":43,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库存交易查询/u261.png"}},
{
              "id":"b15d5a2df5804527b94053fd519a199f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":43,
                  "y":212},
                "size":{
                  "width":81,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5c804042e18043a490977dbe48a29c7d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":43,
                      "y":212},
                    "size":{
                      "width":81,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/cdc收货汇总/u31.png"}},
{
              "id":"54674f1bde0f478489d04b685a4e76a7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":124,
                  "y":212},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7fb5be8fd4704027990f6008ed805957",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":124,
                      "y":212},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/月台维护/u35.png"}},
{
              "id":"ac384c1aac6c4eee85be180df0f3a376",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":195,
                  "y":212},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4046199d6c20495a80b5aa1184d39239",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":195,
                      "y":212},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平库拣货/u40.png"}},
{
              "id":"7930d5c140a047819cedbe19ad852d39",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":43,
                  "height":22}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b96518e57bbb4b0a8cf4eaef3fdbfc99",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":43,
                      "height":22}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平库拣货/u26.png"}},
{
              "id":"810fc48e109a4a338b2528ed865ddc09",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":43,
                  "y":30},
                "size":{
                  "width":81,
                  "height":22}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"92f728b595e7402ba9fdd596a59e44c3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":43,
                      "y":30},
                    "size":{
                      "width":81,
                      "height":22}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平库拣货/u28.png"}},
{
              "id":"03e012a5dcf4470e9c75ac0a27f5d1d5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":124,
                  "y":30},
                "size":{
                  "width":71,
                  "height":22}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fcb453aeef3b4a6db291c71353c1dc0c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":124,
                      "y":30},
                    "size":{
                      "width":71,
                      "height":22}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平库拣货/u30.png"}},
{
              "id":"f01f9f6adf944991882d765e1d6cd996",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":195,
                  "y":30},
                "size":{
                  "width":80,
                  "height":22}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f007f63539a54019834ecf59138c450a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":195,
                      "y":30},
                    "size":{
                      "width":80,
                      "height":22}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平库拣货/u32.png"}},
{
              "id":"3b32720c473247939cea0e16b86358e5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":52},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bb2b235d0e924b618a2ea1daa284705f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":52},
                    "size":{
                      "width":43,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库存交易查询/u261.png"}},
{
              "id":"47731d77d77f4211b235df82659fa7fe",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":43,
                  "y":52},
                "size":{
                  "width":81,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9115729b57f44653b42f1bb69fa8e9aa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":43,
                      "y":52},
                    "size":{
                      "width":81,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/cdc收货汇总/u31.png"}},
{
              "id":"a07a8ec3612f4594a65fc50bf643f292",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":124,
                  "y":52},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"aa12ce61f50d4c94975604f0071a7c66",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":124,
                      "y":52},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/月台维护/u35.png"}},
{
              "id":"766b8a4114e948d48c40214ddc3beb67",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":195,
                  "y":52},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a85889d4a783495f90a5319dd62ee870",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":195,
                      "y":52},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平库拣货/u40.png"}},
{
              "id":"c581dfe50cbe4c0b9c876bde1eeb98c0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":72},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f000fa2b186345bf83b8c98c2a0cec74",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":72},
                    "size":{
                      "width":43,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库存交易查询/u261.png"}},
{
              "id":"681b8e07c73e427d9ee07aba53a7f7c1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":43,
                  "y":72},
                "size":{
                  "width":81,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"622365ab383043b796a27469f2bbd178",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":43,
                      "y":72},
                    "size":{
                      "width":81,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/cdc收货汇总/u31.png"}},
{
              "id":"2fcfe79c17dc4c70ac0bf2bec7f56cfc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":124,
                  "y":72},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6aeb20e72b5744abbeb280caaeab730f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":124,
                      "y":72},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/月台维护/u35.png"}},
{
              "id":"7e3aa76e23d249a09bd2f8bbee00db97",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":195,
                  "y":72},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8d95629428cc47938e65d8ac70bc8733",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":195,
                      "y":72},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平库拣货/u40.png"}},
{
              "id":"65646d369df145ed99fca876ed446796",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":92},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"856742938a964a9682ec89a600ea22b0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":92},
                    "size":{
                      "width":43,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库存交易查询/u261.png"}},
{
              "id":"e56999baa9854a238ee56cb64c42972d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":43,
                  "y":92},
                "size":{
                  "width":81,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"df3eb788c99c4e8393e288cb5dc9860e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":43,
                      "y":92},
                    "size":{
                      "width":81,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/cdc收货汇总/u31.png"}},
{
              "id":"70247b697f51494abe9032865b2a43f6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":124,
                  "y":92},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6f7431ff2e7741f7b9b93d932f72af85",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":124,
                      "y":92},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/月台维护/u35.png"}},
{
              "id":"33d67864e4bb44b8bde01cb9d4aeed93",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":195,
                  "y":92},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5b15f66a46e843f0b45c4f89bfa7d9d8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":195,
                      "y":92},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平库拣货/u40.png"}}]},
{
          "id":"84b8b12f1cb74eeebd3fcb086a20d9ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":412,
              "y":10},
            "size":{
              "width":305,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5bbc901d675482db507cc951c8a66e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":412,
                  "y":10},
                "size":{
                  "width":305,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u6.png"}},
{
          "id":"794f92ae537c43709bf7112b555ebddd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":416,
              "y":15},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"774e99752c4f4bf385f46cf02001ff4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":416,
                  "y":15},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f5eb1fe5b78420da3100108ae1178a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":566,
              "y":17},
            "size":{
              "width":164,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53f0337d51564dd499bbd63e59e877b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":566,
                  "y":17},
                "size":{
                  "width":164,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d845d86723cc4b32b172940e1345dd4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":413,
              "y":461},
            "size":{
              "width":308,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3586371981c1484788d42f81e0aca321",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":413,
                  "y":461},
                "size":{
                  "width":308,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u12.png"}},
{
          "id":"b1bfda2e418741f28f6098beb35e48a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":556,
              "y":467},
            "size":{
              "width":162,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81da9230844644e6b0151638c5f4289c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":556,
                  "y":467},
                "size":{
                  "width":162,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e3f01f7c8844d93b097e9d72a72b6a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":427,
              "y":69},
            "size":{
              "width":78,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd9a9f3ecdf847d980e81240da638b4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":427,
                  "y":69},
                "size":{
                  "width":78,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25664c51023a4acda1f4f9015e0983bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":427,
              "y":152},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cd0f348afdf4aad9b65a09301a019ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":427,
                  "y":152},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23e50c1871d84b539ab2ea904fdf67df",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":517,
              "y":153},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"33e32d719c304718a914f8c33b4a212c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":427,
              "y":109},
            "size":{
              "width":78,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"362d50eedde74f7c9788f3be57bdc3c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":427,
                  "y":109},
                "size":{
                  "width":78,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84a6274468394f85a8f9a2dab0e5adf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":427,
              "y":299},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e27afc76e1f94cef8c33fc4ebda03711",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":427,
                  "y":299},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18bf2cd3644f42e8886a952471edbf7c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":517,
              "y":111},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ba189fb886f34e8dbdb5a0837cbedf74",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":517,
              "y":69},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2d3cc125ee46417b9182170917fb71ae",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":517,
              "y":296},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"37e4532dcb9a444b86f494016323436b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":427,
              "y":343},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d1a81697d3a404ca008987529a17a07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":427,
                  "y":343},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a2663aaf836440dd888a987102b09338",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":517,
              "y":340},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d79593f9cbf54b248d520aef0ac4e4e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":427,
              "y":196},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b84bbd5aed494801a594d950a8ba7933",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":427,
                  "y":196},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be5d344936984d969c4e8a0d2e2ee66a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":517,
              "y":196},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8a96e4a5d7394c66a80422003d922696",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":427,
              "y":261},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b0d54c207ce404081d83c2022e65621",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":427,
                  "y":261},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0ec561b223f47f5989ba73d66d2cd0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":12,
              "y":10},
            "size":{
              "width":305,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92b45675e5294fbeac766484f9f91875",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":12,
                  "y":10},
                "size":{
                  "width":305,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u6.png"}},
{
          "id":"0e8d860b475643db9718465d14d0149b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":16,
              "y":15},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aeff3bda102b41be975b869b501ff35f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":16,
                  "y":15},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"923dec70a11844428218613a81d19347",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":166,
              "y":17},
            "size":{
              "width":164,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cf1f224193a47f299cffc9ad9e254e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":166,
                  "y":17},
                "size":{
                  "width":164,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1efc662dfb644ca9b7523e97920219af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":12,
              "y":461},
            "size":{
              "width":308,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebd171caa05f4cb8bb19b8f3cd3d3525",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":12,
                  "y":461},
                "size":{
                  "width":308,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u12.png"}},
{
          "id":"debbaa2c96e548cb8171ec0b576a0b73",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":155,
              "y":467},
            "size":{
              "width":162,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6b4e2112c2540c7a81f7e61b9e54a4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":155,
                  "y":467},
                "size":{
                  "width":162,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "03d061f28f1d44dea47e89bcbefd8b1d":{
      "scriptId":"u0"},
    "4bbb14a796c04e528ca5bbc86a676066":{
      "scriptId":"u1"},
    "392b6d7547dc481f84e07dcfe84d1962":{
      "scriptId":"u2"},
    "18b5e31089fd495d987a3494bfeb185f":{
      "scriptId":"u3"},
    "80bfff5e789c495f85965fa223471215":{
      "scriptId":"u4"},
    "0b0690dd4c504a56a4231b8615227d6d":{
      "scriptId":"u5"},
    "42c6d08b91fd4ba4911539857a412dc3":{
      "scriptId":"u6"},
    "508d45a077ca42bb930c002b5db59ddd":{
      "scriptId":"u7"},
    "07adea2f9bbf4cd29ab4ce654727ec87":{
      "scriptId":"u8"},
    "f3001911bd1e49dea9642c7d4ff8b0da":{
      "scriptId":"u9"},
    "bcedc962f1604d97b7d871093fd838f3":{
      "scriptId":"u10"},
    "355cd4b458764edf88963b59d6e274c8":{
      "scriptId":"u11"},
    "b60c89b381bb49e9a9e5f36a777af9fb":{
      "scriptId":"u12"},
    "7113888f6c564624892394404a667887":{
      "scriptId":"u13"},
    "03a07403abee469dbbbf6bead7438275":{
      "scriptId":"u14"},
    "fb541d4c26b748c38580b0bf8c26bd47":{
      "scriptId":"u15"},
    "e67919e5a7c44be8ae3e6702565a5460":{
      "scriptId":"u16"},
    "3e0e00b51d6e45eab5d23376ad5a476d":{
      "scriptId":"u17"},
    "7930d5c140a047819cedbe19ad852d39":{
      "scriptId":"u18"},
    "b96518e57bbb4b0a8cf4eaef3fdbfc99":{
      "scriptId":"u19"},
    "810fc48e109a4a338b2528ed865ddc09":{
      "scriptId":"u20"},
    "92f728b595e7402ba9fdd596a59e44c3":{
      "scriptId":"u21"},
    "03e012a5dcf4470e9c75ac0a27f5d1d5":{
      "scriptId":"u22"},
    "fcb453aeef3b4a6db291c71353c1dc0c":{
      "scriptId":"u23"},
    "f01f9f6adf944991882d765e1d6cd996":{
      "scriptId":"u24"},
    "f007f63539a54019834ecf59138c450a":{
      "scriptId":"u25"},
    "3b32720c473247939cea0e16b86358e5":{
      "scriptId":"u26"},
    "bb2b235d0e924b618a2ea1daa284705f":{
      "scriptId":"u27"},
    "47731d77d77f4211b235df82659fa7fe":{
      "scriptId":"u28"},
    "9115729b57f44653b42f1bb69fa8e9aa":{
      "scriptId":"u29"},
    "a07a8ec3612f4594a65fc50bf643f292":{
      "scriptId":"u30"},
    "aa12ce61f50d4c94975604f0071a7c66":{
      "scriptId":"u31"},
    "766b8a4114e948d48c40214ddc3beb67":{
      "scriptId":"u32"},
    "a85889d4a783495f90a5319dd62ee870":{
      "scriptId":"u33"},
    "c581dfe50cbe4c0b9c876bde1eeb98c0":{
      "scriptId":"u34"},
    "f000fa2b186345bf83b8c98c2a0cec74":{
      "scriptId":"u35"},
    "681b8e07c73e427d9ee07aba53a7f7c1":{
      "scriptId":"u36"},
    "622365ab383043b796a27469f2bbd178":{
      "scriptId":"u37"},
    "2fcfe79c17dc4c70ac0bf2bec7f56cfc":{
      "scriptId":"u38"},
    "6aeb20e72b5744abbeb280caaeab730f":{
      "scriptId":"u39"},
    "7e3aa76e23d249a09bd2f8bbee00db97":{
      "scriptId":"u40"},
    "8d95629428cc47938e65d8ac70bc8733":{
      "scriptId":"u41"},
    "65646d369df145ed99fca876ed446796":{
      "scriptId":"u42"},
    "856742938a964a9682ec89a600ea22b0":{
      "scriptId":"u43"},
    "e56999baa9854a238ee56cb64c42972d":{
      "scriptId":"u44"},
    "df3eb788c99c4e8393e288cb5dc9860e":{
      "scriptId":"u45"},
    "70247b697f51494abe9032865b2a43f6":{
      "scriptId":"u46"},
    "6f7431ff2e7741f7b9b93d932f72af85":{
      "scriptId":"u47"},
    "33d67864e4bb44b8bde01cb9d4aeed93":{
      "scriptId":"u48"},
    "5b15f66a46e843f0b45c4f89bfa7d9d8":{
      "scriptId":"u49"},
    "3c9cbd2c774447c7b5c60e7a9a3d8d12":{
      "scriptId":"u50"},
    "b917576612fe4c999caf250de7bffe58":{
      "scriptId":"u51"},
    "36952f0edcc841948f448b5b3920442a":{
      "scriptId":"u52"},
    "b365f245ebbd4c64828c2eeb1129e5c1":{
      "scriptId":"u53"},
    "3caac988967c4f1e8e88640b6945e183":{
      "scriptId":"u54"},
    "e0c003fbc70442589e37c883450a471a":{
      "scriptId":"u55"},
    "3082d4ac45cf4596a4f96a722f3c397b":{
      "scriptId":"u56"},
    "1c6ab98289724740adb680173c6e6830":{
      "scriptId":"u57"},
    "89df3215bbaf4157bfc9d13beaec8d76":{
      "scriptId":"u58"},
    "dc936177a79347ff9fa5f1394531cbdc":{
      "scriptId":"u59"},
    "02da781599c348fdaee31c1a8a85c17e":{
      "scriptId":"u60"},
    "75ffac1798374bf391aae4d9600389a9":{
      "scriptId":"u61"},
    "142a425cbc9246e2a0d3ac7e5c9b9226":{
      "scriptId":"u62"},
    "853e1824aee641979cebc9470cabef56":{
      "scriptId":"u63"},
    "0f9cd751767940098ef86510ff5fb538":{
      "scriptId":"u64"},
    "560cd5351bd54f21894d453f9b4466dd":{
      "scriptId":"u65"},
    "8ba5f7d560f64865884d7494bd0d516c":{
      "scriptId":"u66"},
    "3d77fd01a34c496e82819e0c00bb5382":{
      "scriptId":"u67"},
    "8ad2c93381e743a3b4c23a3a2c53df68":{
      "scriptId":"u68"},
    "699ec50709a24bc5a6632c6b0fe79ad8":{
      "scriptId":"u69"},
    "4ae587949c8147988d245da3780053c7":{
      "scriptId":"u70"},
    "43cbe774a59f4271b6ae28a47c18b326":{
      "scriptId":"u71"},
    "409edf0d454d4a3db7253e4e35c0282e":{
      "scriptId":"u72"},
    "17ef998afe4146a5bfd0e5e9fb2872fd":{
      "scriptId":"u73"},
    "275d1a53cade4aaa8e88c1ece48f6a48":{
      "scriptId":"u74"},
    "a63db3ff088b46849888c4008135c0e6":{
      "scriptId":"u75"},
    "7d9c758cac554d18a36ebca3a2efa720":{
      "scriptId":"u76"},
    "c2655808360840c9ae75da608ec58325":{
      "scriptId":"u77"},
    "1d880682dd2b470a9b26a28c21fd25ed":{
      "scriptId":"u78"},
    "8ed26bfa333544e49a46ee10e771f29b":{
      "scriptId":"u79"},
    "26f22123729a45f1b26e980d623fddc6":{
      "scriptId":"u80"},
    "351ada4cb6ef4000af047b65eca9cfd6":{
      "scriptId":"u81"},
    "3b04539701f14806844626f5282c7ffb":{
      "scriptId":"u82"},
    "044fafa0900e4ac191482bfe3a597038":{
      "scriptId":"u83"},
    "333d24fea00e47e79b25e53b417f01ac":{
      "scriptId":"u84"},
    "a527d5a0de6a4875911bc91b386e9ecc":{
      "scriptId":"u85"},
    "14c2e53fae4947748f61c66a0d447b55":{
      "scriptId":"u86"},
    "a4caef54993b4e38a854cd38fe369aeb":{
      "scriptId":"u87"},
    "50e4bea4e3c640128f00ae5556353cdb":{
      "scriptId":"u88"},
    "a3077cc648954318a8262f0bbe7ed937":{
      "scriptId":"u89"},
    "8895445d43d7451594d3c76326427ecc":{
      "scriptId":"u90"},
    "049c1f3ce8ed41f0872db73dc376aa71":{
      "scriptId":"u91"},
    "b15d5a2df5804527b94053fd519a199f":{
      "scriptId":"u92"},
    "5c804042e18043a490977dbe48a29c7d":{
      "scriptId":"u93"},
    "54674f1bde0f478489d04b685a4e76a7":{
      "scriptId":"u94"},
    "7fb5be8fd4704027990f6008ed805957":{
      "scriptId":"u95"},
    "ac384c1aac6c4eee85be180df0f3a376":{
      "scriptId":"u96"},
    "4046199d6c20495a80b5aa1184d39239":{
      "scriptId":"u97"},
    "9235ac091e8140b1b08e7e40387f1262":{
      "scriptId":"u98"},
    "0c437210b14040b18c5f26a37c5af59b":{
      "scriptId":"u99"},
    "4243086ff4274e8ba8d85d9f786a2a4d":{
      "scriptId":"u100"},
    "775a80ae268740b98c1b1cf830050a9d":{
      "scriptId":"u101"},
    "a80ef40ac09e437498d83ba82c2a0081":{
      "scriptId":"u102"},
    "d2cb1136dc7440bba7572531dc72234c":{
      "scriptId":"u103"},
    "5a4b6d5fd7de4583b9b2d31b56c35c0c":{
      "scriptId":"u104"},
    "d019b2965636473881b8f1ed8bb9e594":{
      "scriptId":"u105"},
    "84b8b12f1cb74eeebd3fcb086a20d9ae":{
      "scriptId":"u106"},
    "a5bbc901d675482db507cc951c8a66e4":{
      "scriptId":"u107"},
    "794f92ae537c43709bf7112b555ebddd":{
      "scriptId":"u108"},
    "774e99752c4f4bf385f46cf02001ff4d":{
      "scriptId":"u109"},
    "0f5eb1fe5b78420da3100108ae1178a1":{
      "scriptId":"u110"},
    "53f0337d51564dd499bbd63e59e877b5":{
      "scriptId":"u111"},
    "d845d86723cc4b32b172940e1345dd4b":{
      "scriptId":"u112"},
    "3586371981c1484788d42f81e0aca321":{
      "scriptId":"u113"},
    "b1bfda2e418741f28f6098beb35e48a4":{
      "scriptId":"u114"},
    "81da9230844644e6b0151638c5f4289c":{
      "scriptId":"u115"},
    "3e3f01f7c8844d93b097e9d72a72b6a1":{
      "scriptId":"u116"},
    "dd9a9f3ecdf847d980e81240da638b4b":{
      "scriptId":"u117"},
    "25664c51023a4acda1f4f9015e0983bf":{
      "scriptId":"u118"},
    "0cd0f348afdf4aad9b65a09301a019ee":{
      "scriptId":"u119"},
    "23e50c1871d84b539ab2ea904fdf67df":{
      "scriptId":"u120"},
    "33e32d719c304718a914f8c33b4a212c":{
      "scriptId":"u121"},
    "362d50eedde74f7c9788f3be57bdc3c5":{
      "scriptId":"u122"},
    "84a6274468394f85a8f9a2dab0e5adf4":{
      "scriptId":"u123"},
    "e27afc76e1f94cef8c33fc4ebda03711":{
      "scriptId":"u124"},
    "18bf2cd3644f42e8886a952471edbf7c":{
      "scriptId":"u125"},
    "ba189fb886f34e8dbdb5a0837cbedf74":{
      "scriptId":"u126"},
    "2d3cc125ee46417b9182170917fb71ae":{
      "scriptId":"u127"},
    "37e4532dcb9a444b86f494016323436b":{
      "scriptId":"u128"},
    "6d1a81697d3a404ca008987529a17a07":{
      "scriptId":"u129"},
    "a2663aaf836440dd888a987102b09338":{
      "scriptId":"u130"},
    "d79593f9cbf54b248d520aef0ac4e4e6":{
      "scriptId":"u131"},
    "b84bbd5aed494801a594d950a8ba7933":{
      "scriptId":"u132"},
    "be5d344936984d969c4e8a0d2e2ee66a":{
      "scriptId":"u133"},
    "8a96e4a5d7394c66a80422003d922696":{
      "scriptId":"u134"},
    "2b0d54c207ce404081d83c2022e65621":{
      "scriptId":"u135"},
    "e0ec561b223f47f5989ba73d66d2cd0f":{
      "scriptId":"u136"},
    "92b45675e5294fbeac766484f9f91875":{
      "scriptId":"u137"},
    "0e8d860b475643db9718465d14d0149b":{
      "scriptId":"u138"},
    "aeff3bda102b41be975b869b501ff35f":{
      "scriptId":"u139"},
    "923dec70a11844428218613a81d19347":{
      "scriptId":"u140"},
    "7cf1f224193a47f299cffc9ad9e254e5":{
      "scriptId":"u141"},
    "1efc662dfb644ca9b7523e97920219af":{
      "scriptId":"u142"},
    "ebd171caa05f4cb8bb19b8f3cd3d3525":{
      "scriptId":"u143"},
    "debbaa2c96e548cb8171ec0b576a0b73":{
      "scriptId":"u144"},
    "b6b4e2112c2540c7a81f7e61b9e54a4f":{
      "scriptId":"u145"}}});