$axure.loadCurrentPage({
  "url":"接力上架.html",
  "generationDate":new Date(1554888135746.2),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"38d000f86b6647ea9b6bbd42e914ae9a",
    "type":"Axure:Page",
    "name":"接力上架",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cbfb6ebd8ea34ec8a91dad39bf4dfee9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "location":{
              "x":30,
              "y":96},
            "size":{
              "width":59,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c7a8b55b36c47b7b7407372c289f587",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":30,
                  "y":96},
                "size":{
                  "width":59,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b652cf20e464572b8a6824d0864514a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":109,
              "y":97},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0164cae2cf074ebc8d8003b9307db9ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":19,
              "y":174},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f8ca07f03b7414c805db116d2f97241",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":19,
                  "y":174},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a8b7f84425f54136b85a7db62d7e4370",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "fontName":"'Arial Black', 'Arial'",
            "fontSize":"11px",
            "fontWeight":"900",
            "location":{
              "x":109,
              "y":174},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d3587541d2c84e5abaf8bdd99ec0832c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "size":{
              "width":305,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"520d0f785b4f4e9fa8119f8621cf6158",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "size":{
                  "width":305,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u6.png"}},
{
          "id":"d93c426975b54a7fa091a672fe8ec9be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":4,
              "y":5},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28227b3a46d54ad29e3800c1bc1e4ad4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":4,
                  "y":5},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af06f5690e174b69bb14d264944c0f7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":134,
              "y":6},
            "size":{
              "width":166,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddc5d1ec529345de94db14eebbf29689",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":134,
                  "y":6},
                "size":{
                  "width":166,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d7b9b79410d42e9a9d81735db9135dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":1,
              "y":451},
            "size":{
              "width":305,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a79c64046094025a52a6437fb73b297",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":1,
                  "y":451},
                "size":{
                  "width":305,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u6.png"}},
{
          "id":"66186140bd37401db032775f7f40763c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":143,
              "y":457},
            "size":{
              "width":157,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34ec1d6732584f79978bbf4f9b12ab40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":143,
                  "y":457},
                "size":{
                  "width":157,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"576ff25a328f405d8da114932a7252ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCCC},
            "location":{
              "x":348,
              "y":40},
            "size":{
              "width":362,
              "height":370}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d57aff4a90c34009a8be5819dd6dd0c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCCC},
                "location":{
                  "x":348,
                  "y":40},
                "size":{
                  "width":362,
                  "height":370}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/接力上架/u16.png"}},
{
          "id":"a5a7edbd72034c2f9f4106fcd87fb886",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "location":{
              "x":30,
              "y":135},
            "size":{
              "width":59,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c66f6cae65f7456eac54e1022a437e31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":30,
                  "y":135},
                "size":{
                  "width":59,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2562ca08cfb34a928d159b660c4daae9",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":109,
              "y":135},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c43d4f2d22484e38a5e42f50063efd7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":30.0000038146973,
              "y":216},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"189aac88eb14456489218f3de489dc8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":30.0000038146973,
                  "y":216},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"531f9bb3f65c4f7fa66c206bc93dc0e7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":216},
            "size":{
              "width":190,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"69a72ffbd6534d06acd589d18ddeb7b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":30,
              "y":254},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edd4d2490e62446a8ee922286f854251",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":30,
                  "y":254},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48968efaa2d24f4ca8aee3d68e8fbbd3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":254},
            "size":{
              "width":190,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"555ba589791f443f8314bb9dd56d7129",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":345},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 弹出窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"popup",
                      "popup":{
                        "left":100,
                        "top":100,
                        "width":500,
                        "height":500,
                        "toolbar":false,
                        "scrollbars":false,
                        "location":false,
                        "status":false,
                        "menubar":false,
                        "directories":false,
                        "resizable":false,
                        "centerwindow":true}}]}]}},
          "tabbable":true},
{
          "id":"f80d41006f674b2889089f14b653c021",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":305},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "cbfb6ebd8ea34ec8a91dad39bf4dfee9":{
      "scriptId":"u0"},
    "0c7a8b55b36c47b7b7407372c289f587":{
      "scriptId":"u1"},
    "9b652cf20e464572b8a6824d0864514a":{
      "scriptId":"u2"},
    "0164cae2cf074ebc8d8003b9307db9ae":{
      "scriptId":"u3"},
    "1f8ca07f03b7414c805db116d2f97241":{
      "scriptId":"u4"},
    "a8b7f84425f54136b85a7db62d7e4370":{
      "scriptId":"u5"},
    "d3587541d2c84e5abaf8bdd99ec0832c":{
      "scriptId":"u6"},
    "520d0f785b4f4e9fa8119f8621cf6158":{
      "scriptId":"u7"},
    "d93c426975b54a7fa091a672fe8ec9be":{
      "scriptId":"u8"},
    "28227b3a46d54ad29e3800c1bc1e4ad4":{
      "scriptId":"u9"},
    "af06f5690e174b69bb14d264944c0f7f":{
      "scriptId":"u10"},
    "ddc5d1ec529345de94db14eebbf29689":{
      "scriptId":"u11"},
    "3d7b9b79410d42e9a9d81735db9135dc":{
      "scriptId":"u12"},
    "6a79c64046094025a52a6437fb73b297":{
      "scriptId":"u13"},
    "66186140bd37401db032775f7f40763c":{
      "scriptId":"u14"},
    "34ec1d6732584f79978bbf4f9b12ab40":{
      "scriptId":"u15"},
    "576ff25a328f405d8da114932a7252ab":{
      "scriptId":"u16"},
    "d57aff4a90c34009a8be5819dd6dd0c5":{
      "scriptId":"u17"},
    "a5a7edbd72034c2f9f4106fcd87fb886":{
      "scriptId":"u18"},
    "c66f6cae65f7456eac54e1022a437e31":{
      "scriptId":"u19"},
    "2562ca08cfb34a928d159b660c4daae9":{
      "scriptId":"u20"},
    "c43d4f2d22484e38a5e42f50063efd7a":{
      "scriptId":"u21"},
    "189aac88eb14456489218f3de489dc8c":{
      "scriptId":"u22"},
    "531f9bb3f65c4f7fa66c206bc93dc0e7":{
      "scriptId":"u23"},
    "69a72ffbd6534d06acd589d18ddeb7b6":{
      "scriptId":"u24"},
    "edd4d2490e62446a8ee922286f854251":{
      "scriptId":"u25"},
    "48968efaa2d24f4ca8aee3d68e8fbbd3":{
      "scriptId":"u26"},
    "555ba589791f443f8314bb9dd56d7129":{
      "scriptId":"u27"},
    "f80d41006f674b2889089f14b653c021":{
      "scriptId":"u28"}}});