$axure.loadCurrentPage({
  "url":"标准盘点扫描.html",
  "generationDate":new Date(1554888136790.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"b1382853d3cf4ed498ccab51f82a660d",
    "type":"Axure:Page",
    "name":"标准盘点扫描",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5b42415adc0b4fc7915f9c128ee06605",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "size":{
              "width":305,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bf4e1589ef747cdb83f1c6b81e28a9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "size":{
                  "width":305,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u6.png"}},
{
          "id":"f6e99f0f351c4a348595e4d0fc63e2bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":4,
              "y":5},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"253a97e233c047b8825f3520832942e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":4,
                  "y":5},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5294a3bfe92f472a9e1158e2a48a12c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":124,
              "y":7},
            "size":{
              "width":181,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8fedbbd9600496cab362a6b891e6328",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":124,
                  "y":7},
                "size":{
                  "width":181,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97d014358af6443c9c37332a68ec80cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":1,
              "y":451},
            "size":{
              "width":308,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13b18f33f410405fa2b031818f3f42ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":1,
                  "y":451},
                "size":{
                  "width":308,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u12.png"}},
{
          "id":"675861b57d394b5fb639086c827c9534",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":144,
              "y":457},
            "size":{
              "width":162,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"064b0de1d0d14b3eb95d9976b285f650",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":144,
                  "y":457},
                "size":{
                  "width":162,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9676f9d37a8f4614a438c7bd02e55c96",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":49},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa7b9c9b86b247d6a2057385be95a5a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":49},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97dd850674294c04833d3f61217770e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCCC},
            "location":{
              "x":330,
              "y":40},
            "size":{
              "width":415,
              "height":416}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58f87f367f9a469ab8cf2c6a14ff0b92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCCC},
                "location":{
                  "x":330,
                  "y":40},
                "size":{
                  "width":415,
                  "height":416}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pod盘点_1/u15.png"}},
{
          "id":"02f3ae25948a4b02a6bd5928a92b0cee",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":50},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"53ec3c16e8254251abdbfbad20d616e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":16,
              "y":375},
            "size":{
              "width":272,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5445873d882e450e805a73be1112b47d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":16,
                  "y":375},
                "size":{
                  "width":272,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (提交按钮)",
                      "objectsToFades":[{
                          "objectPath":["92b9a2996e154264bdade33b3ada7816"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92b9a2996e154264bdade33b3ada7816",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":false,
          "style":{
            "location":{
              "x":106,
              "y":415},
            "size":{
              "width":91,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"4cb953399ded46c98566ba739fc27c00",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":165},
            "size":{
              "width":92,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"072c5debc4ca45478d33017419e7689b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":165},
                "size":{
                  "width":92,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e4513b4f2c18482b8eccade36e55bfd4",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":165},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d12c2b8bc83149e4a52ab9c4efdf01fa",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":200},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4e0dd9ba0e014918a5db1068039e96e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":199},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5606dc8e6eb46e291e9cdd87e260086",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":199},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a51b42984fa4139abb6f3e90a075ca2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":233},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e969b2a8bf0e44118e57b55b237e2598",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":233},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea3178be66044085a9fda54582809ef4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":233},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b9e00d5cb804c66bcccf8d221922595",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":101},
            "size":{
              "width":92,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62abd9f0b4db4d5e976bc64b83c5900d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":101},
                "size":{
                  "width":92,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e42f83825b0d4c2ba10a4029826bd04c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":101},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"06ee735116fd4558a6b3b1be99dfc4e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":132},
            "size":{
              "width":92,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91a6166442474a72a2c6341b3b7245fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":132},
                "size":{
                  "width":92,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f8a77031a5444669848a9b0ab53f6c42",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":132},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"72bc5523ff014566859d1b2b63f695e4",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":275},
            "size":{
              "width":122,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (形状)",
                      "objectsToFades":[{
                          "objectPath":["ab5145cae3ad4310bd86294b8c8234d8"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"ab5145cae3ad4310bd86294b8c8234d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":130,
              "y":273},
            "size":{
              "width":158,
              "height":24},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a5c005e171743329b276ba0b072fa5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":130,
                  "y":273},
                "size":{
                  "width":158,
                  "height":24},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80b535612f2a4a67b1309deef5aaa0d5",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":330},
            "size":{
              "width":122,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f2d5408e372c43a99f075a92b16e5c8c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":164,
              "y":330},
            "size":{
              "width":122,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "5b42415adc0b4fc7915f9c128ee06605":{
      "scriptId":"u0"},
    "1bf4e1589ef747cdb83f1c6b81e28a9b":{
      "scriptId":"u1"},
    "f6e99f0f351c4a348595e4d0fc63e2bc":{
      "scriptId":"u2"},
    "253a97e233c047b8825f3520832942e5":{
      "scriptId":"u3"},
    "5294a3bfe92f472a9e1158e2a48a12c7":{
      "scriptId":"u4"},
    "b8fedbbd9600496cab362a6b891e6328":{
      "scriptId":"u5"},
    "97d014358af6443c9c37332a68ec80cf":{
      "scriptId":"u6"},
    "13b18f33f410405fa2b031818f3f42ce":{
      "scriptId":"u7"},
    "675861b57d394b5fb639086c827c9534":{
      "scriptId":"u8"},
    "064b0de1d0d14b3eb95d9976b285f650":{
      "scriptId":"u9"},
    "9676f9d37a8f4614a438c7bd02e55c96":{
      "scriptId":"u10"},
    "aa7b9c9b86b247d6a2057385be95a5a2":{
      "scriptId":"u11"},
    "97dd850674294c04833d3f61217770e7":{
      "scriptId":"u12"},
    "58f87f367f9a469ab8cf2c6a14ff0b92":{
      "scriptId":"u13"},
    "02f3ae25948a4b02a6bd5928a92b0cee":{
      "scriptId":"u14"},
    "53ec3c16e8254251abdbfbad20d616e4":{
      "scriptId":"u15"},
    "5445873d882e450e805a73be1112b47d":{
      "scriptId":"u16"},
    "92b9a2996e154264bdade33b3ada7816":{
      "scriptId":"u17"},
    "4cb953399ded46c98566ba739fc27c00":{
      "scriptId":"u18"},
    "072c5debc4ca45478d33017419e7689b":{
      "scriptId":"u19"},
    "e4513b4f2c18482b8eccade36e55bfd4":{
      "scriptId":"u20"},
    "d12c2b8bc83149e4a52ab9c4efdf01fa":{
      "scriptId":"u21"},
    "4e0dd9ba0e014918a5db1068039e96e4":{
      "scriptId":"u22"},
    "a5606dc8e6eb46e291e9cdd87e260086":{
      "scriptId":"u23"},
    "9a51b42984fa4139abb6f3e90a075ca2":{
      "scriptId":"u24"},
    "e969b2a8bf0e44118e57b55b237e2598":{
      "scriptId":"u25"},
    "ea3178be66044085a9fda54582809ef4":{
      "scriptId":"u26"},
    "0b9e00d5cb804c66bcccf8d221922595":{
      "scriptId":"u27"},
    "62abd9f0b4db4d5e976bc64b83c5900d":{
      "scriptId":"u28"},
    "e42f83825b0d4c2ba10a4029826bd04c":{
      "scriptId":"u29"},
    "06ee735116fd4558a6b3b1be99dfc4e2":{
      "scriptId":"u30"},
    "91a6166442474a72a2c6341b3b7245fa":{
      "scriptId":"u31"},
    "f8a77031a5444669848a9b0ab53f6c42":{
      "scriptId":"u32"},
    "72bc5523ff014566859d1b2b63f695e4":{
      "scriptId":"u33"},
    "ab5145cae3ad4310bd86294b8c8234d8":{
      "scriptId":"u34"},
    "8a5c005e171743329b276ba0b072fa5c":{
      "scriptId":"u35"},
    "80b535612f2a4a67b1309deef5aaa0d5":{
      "scriptId":"u36"},
    "f2d5408e372c43a99f075a92b16e5c8c":{
      "scriptId":"u37"}}});