$axure.loadCurrentPage({
  "url":"添加_3.html",
  "generationDate":new Date(1554888121160.18),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"0d0790a522ed4cc18f77b37783294f28",
    "type":"Axure:Page",
    "name":"添加",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"851c165e6a834bff865f9e6dd93d8235",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":20,
              "y":94},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"996fe661ef694ab1a5f9f61afb42b194",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":94},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"baf024b0051d445da2c84859f4eac669",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":92},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"905c4fbdbfb74abfbdc7c99863357ee9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":220,
              "y":93},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97b7bdd6ffc64e2c84b11e6771e0883f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":220,
                  "y":93},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ba093b8019644cf8cc8f9d21f3dd162",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":91},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"07c6d54e2b6c4540af4eaa2bdc28082c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":44},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5341f5c84c4c4a27b6170dc6b3cab7e0",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":44},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"closeCurrent",
                      "description":"关闭当前窗口"}]}]}},
          "tabbable":true},
{
          "id":"295533257c6045fda3756ad6c5481553",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":88},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"cfebf3e4b301464fbbf6c0f79b0866d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":93},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c50b8c60fb840e2aa94fd3ccd4bdf6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":93},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"795d3ca084de4b26b889567a6b8781e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":204},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa2d7b029ec84ac09d97a79f78e0a0f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":204},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02841ca957664269a61fdc98f2c432d9",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":204},
            "size":{
              "width":740,
              "height":36}},
          "adaptiveStyles":{
}},
{
          "id":"7787c2fa2e0142afb08e792611b0d70a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":430,
              "y":93},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"078e4d8fb7554c6a8a60f17982f7ccbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":430,
                  "y":93},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4eb2c5ced92f4320b2ac77be5a84e7f7",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":91},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"9658babedf8c4e639217980a658a0000",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":127},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"82a5c288624a43f18ea9a6d233ee6462",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":132},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c080fb6ca21406a914904b3197c9de8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":132},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"089a14864b9e4314a9317025649aa80e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":126},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5ec76ddc2aeb48538db3d697282619a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":131},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2589d3a698648dfbedd1802d67af810",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":131},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b880b27e2b746b4a3424e447b470572",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":123},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3ff9104620a746b685cbe89345f1c056",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":129},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf64b2549197432092205a6b9d5889e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":129},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c414aa5999842bf88a601247fbdf7a8",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":123},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9bf155b16d6e4d68beba4d9a71223735",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":128},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f6aa5f579e344b49f7df101f28aebd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":128},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74c56980323f436d9ab9d65bac033d68",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":20,
              "y":165},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f80b6379593140a484120a049bd95ef7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":165},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f44fcfafb3f47fab29ed427e1fe319c",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":163},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"2ef06af6cb9445fba5e0386d3ddd3068",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":219,
              "y":165},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4265bf3034244fb4be96d242405bf37a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":219,
                  "y":165},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"266e16d79c7445448a5331f15708855b",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":289,
              "y":163},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"4424bc57e892466d9073ecf9f9324ee7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":17,
              "y":5},
            "size":{
              "width":950,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb1824a356154767a2ef2ade050209cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":17,
                  "y":5},
                "size":{
                  "width":950,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库信息/u144.png"}},
{
          "id":"3beba914e21e4747b31acd8369209a1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":23,
              "y":10},
            "size":{
              "width":122,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c2b7daa13434f0499a39aa5a9b8b489",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":23,
                  "y":10},
                "size":{
                  "width":122,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5cd03c35200a4f2d85acb6861a04b3fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":128,
              "y":12},
            "size":{
              "width":62,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46291f6d15cc4aaa9e574a778963bdb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":128,
                  "y":12},
                "size":{
                  "width":62,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c16539ca53146aaa7074e59fe9c632f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":190,
              "y":12},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bfb9be62cfe48efaf2a7db490966a95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":12},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7358b427cde34da884277c26d8a48d6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":304,
              "y":12},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb7ed6e1a5e6425093ac8d384014b7b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":304,
                  "y":12},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a366e10de79e4ae293eb400fa037bb1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":420,
              "y":12},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed64f7acf22b46c3960a98ef6f008a11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":420,
                  "y":12},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"72f6017334ca405fae67931db17741cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":530,
              "y":12},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1e126e1e2364fa0bfbd4d5a78ce5578",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":530,
                  "y":12},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96822a4989fc4f54a8614e8923bd0058",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":641,
              "y":12},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"437814f35f61474189f8e89f04416464",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":641,
                  "y":12},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6029e8a048d409f877d2a60ec337103",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":739,
              "y":12},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4579f1cffc6c483c8519c4dc268f89c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":739,
                  "y":12},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aeb95ff8c34241a5baa0c7f76e2efce1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":833,
              "y":12},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d00d7e9cc8c45dd993d21de150094d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":833,
                  "y":12},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"773a3d29c0984cd2a168f5deb82e44e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":22,
              "y":456},
            "size":{
              "width":957,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"361585492e3d47e5a5da9e85c9a7e6e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":22,
                  "y":456},
                "size":{
                  "width":957,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库信息/u164.png"}},
{
          "id":"a320dfba244f41849419e34aac0c5e8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":836,
              "y":462},
            "size":{
              "width":134,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a281a002fec24d62a42982ffd7bd49bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":836,
                  "y":462},
                "size":{
                  "width":134,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c3e778216ca4b76ba2725d3a2dfc187",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":430,
              "y":167},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"443d7e21a53541c3ab7faad27df3eaf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":430,
                  "y":167},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd5ef16140204ea2be81e1d3bbcd5349",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":500,
              "y":165},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"43f6961d6eb34cac9057386359dc15ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCCC},
            "location":{
              "x":650,
              "y":158},
            "size":{
              "width":170,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c1a5f38c15a4cddaa9d7a49f15dbbc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCCC},
                "location":{
                  "x":650,
                  "y":158},
                "size":{
                  "width":170,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加_3/u62.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "851c165e6a834bff865f9e6dd93d8235":{
      "scriptId":"u0"},
    "996fe661ef694ab1a5f9f61afb42b194":{
      "scriptId":"u1"},
    "baf024b0051d445da2c84859f4eac669":{
      "scriptId":"u2"},
    "905c4fbdbfb74abfbdc7c99863357ee9":{
      "scriptId":"u3"},
    "97b7bdd6ffc64e2c84b11e6771e0883f":{
      "scriptId":"u4"},
    "9ba093b8019644cf8cc8f9d21f3dd162":{
      "scriptId":"u5"},
    "07c6d54e2b6c4540af4eaa2bdc28082c":{
      "scriptId":"u6"},
    "5341f5c84c4c4a27b6170dc6b3cab7e0":{
      "scriptId":"u7"},
    "295533257c6045fda3756ad6c5481553":{
      "scriptId":"u8"},
    "cfebf3e4b301464fbbf6c0f79b0866d7":{
      "scriptId":"u9"},
    "2c50b8c60fb840e2aa94fd3ccd4bdf6e":{
      "scriptId":"u10"},
    "795d3ca084de4b26b889567a6b8781e5":{
      "scriptId":"u11"},
    "fa2d7b029ec84ac09d97a79f78e0a0f1":{
      "scriptId":"u12"},
    "02841ca957664269a61fdc98f2c432d9":{
      "scriptId":"u13"},
    "7787c2fa2e0142afb08e792611b0d70a":{
      "scriptId":"u14"},
    "078e4d8fb7554c6a8a60f17982f7ccbc":{
      "scriptId":"u15"},
    "4eb2c5ced92f4320b2ac77be5a84e7f7":{
      "scriptId":"u16"},
    "9658babedf8c4e639217980a658a0000":{
      "scriptId":"u17"},
    "82a5c288624a43f18ea9a6d233ee6462":{
      "scriptId":"u18"},
    "9c080fb6ca21406a914904b3197c9de8":{
      "scriptId":"u19"},
    "089a14864b9e4314a9317025649aa80e":{
      "scriptId":"u20"},
    "5ec76ddc2aeb48538db3d697282619a3":{
      "scriptId":"u21"},
    "d2589d3a698648dfbedd1802d67af810":{
      "scriptId":"u22"},
    "2b880b27e2b746b4a3424e447b470572":{
      "scriptId":"u23"},
    "3ff9104620a746b685cbe89345f1c056":{
      "scriptId":"u24"},
    "cf64b2549197432092205a6b9d5889e0":{
      "scriptId":"u25"},
    "6c414aa5999842bf88a601247fbdf7a8":{
      "scriptId":"u26"},
    "9bf155b16d6e4d68beba4d9a71223735":{
      "scriptId":"u27"},
    "6f6aa5f579e344b49f7df101f28aebd0":{
      "scriptId":"u28"},
    "74c56980323f436d9ab9d65bac033d68":{
      "scriptId":"u29"},
    "f80b6379593140a484120a049bd95ef7":{
      "scriptId":"u30"},
    "4f44fcfafb3f47fab29ed427e1fe319c":{
      "scriptId":"u31"},
    "2ef06af6cb9445fba5e0386d3ddd3068":{
      "scriptId":"u32"},
    "4265bf3034244fb4be96d242405bf37a":{
      "scriptId":"u33"},
    "266e16d79c7445448a5331f15708855b":{
      "scriptId":"u34"},
    "4424bc57e892466d9073ecf9f9324ee7":{
      "scriptId":"u35"},
    "cb1824a356154767a2ef2ade050209cf":{
      "scriptId":"u36"},
    "3beba914e21e4747b31acd8369209a1c":{
      "scriptId":"u37"},
    "1c2b7daa13434f0499a39aa5a9b8b489":{
      "scriptId":"u38"},
    "5cd03c35200a4f2d85acb6861a04b3fa":{
      "scriptId":"u39"},
    "46291f6d15cc4aaa9e574a778963bdb8":{
      "scriptId":"u40"},
    "8c16539ca53146aaa7074e59fe9c632f":{
      "scriptId":"u41"},
    "3bfb9be62cfe48efaf2a7db490966a95":{
      "scriptId":"u42"},
    "7358b427cde34da884277c26d8a48d6a":{
      "scriptId":"u43"},
    "fb7ed6e1a5e6425093ac8d384014b7b5":{
      "scriptId":"u44"},
    "a366e10de79e4ae293eb400fa037bb1b":{
      "scriptId":"u45"},
    "ed64f7acf22b46c3960a98ef6f008a11":{
      "scriptId":"u46"},
    "72f6017334ca405fae67931db17741cc":{
      "scriptId":"u47"},
    "a1e126e1e2364fa0bfbd4d5a78ce5578":{
      "scriptId":"u48"},
    "96822a4989fc4f54a8614e8923bd0058":{
      "scriptId":"u49"},
    "437814f35f61474189f8e89f04416464":{
      "scriptId":"u50"},
    "d6029e8a048d409f877d2a60ec337103":{
      "scriptId":"u51"},
    "4579f1cffc6c483c8519c4dc268f89c0":{
      "scriptId":"u52"},
    "aeb95ff8c34241a5baa0c7f76e2efce1":{
      "scriptId":"u53"},
    "3d00d7e9cc8c45dd993d21de150094d9":{
      "scriptId":"u54"},
    "773a3d29c0984cd2a168f5deb82e44e0":{
      "scriptId":"u55"},
    "361585492e3d47e5a5da9e85c9a7e6e8":{
      "scriptId":"u56"},
    "a320dfba244f41849419e34aac0c5e8f":{
      "scriptId":"u57"},
    "a281a002fec24d62a42982ffd7bd49bb":{
      "scriptId":"u58"},
    "6c3e778216ca4b76ba2725d3a2dfc187":{
      "scriptId":"u59"},
    "443d7e21a53541c3ab7faad27df3eaf8":{
      "scriptId":"u60"},
    "dd5ef16140204ea2be81e1d3bbcd5349":{
      "scriptId":"u61"},
    "43f6961d6eb34cac9057386359dc15ff":{
      "scriptId":"u62"},
    "9c1a5f38c15a4cddaa9d7a49f15dbbc2":{
      "scriptId":"u63"}}});