$axure.loadCurrentPage({
  "url":"_____--------------0403__.html",
  "generationDate":new Date(1554888138954.62),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"a66b3bd9b7f848b2980eae9f35aba5f6",
    "type":"Axure:Page",
    "name":"小黄标打印--------------0403更新",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"13071ac0068a4b878def25eb3cf61403",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "size":{
              "width":305,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"306df63fab42452eb319a5d03864383f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "size":{
                  "width":305,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u6.png"}},
{
          "id":"ecac3225cb2c492d9aa7090b48c767c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":4,
              "y":5},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f035f9b53ab14b72aa8bed20c8429c48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":4,
                  "y":5},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9a1ef7e7a554fbda7e984ac53d05446",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":136,
              "y":7},
            "size":{
              "width":128,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"807358a708764773b9baa9d1ed2425f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":136,
                  "y":7},
                "size":{
                  "width":128,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"60af62b46612448da5f982731e7bbc91",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":1,
              "y":451},
            "size":{
              "width":305,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4a708071e014a08bc7a351c42e85848",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":1,
                  "y":451},
                "size":{
                  "width":305,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u6.png"}},
{
          "id":"26c0563925d54e94a19fa14417deecf8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":143,
              "y":457},
            "size":{
              "width":157,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d31d4fc487a4c428fd0ed83624708f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":143,
                  "y":457},
                "size":{
                  "width":157,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9cf1dcb5c2044ab98b9978a58a9f952a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":13,
              "y":63},
            "size":{
              "width":97,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c5f59e7f5004d6eb3a7f3ffd7028747",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":13,
                  "y":63},
                "size":{
                  "width":97,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68c0f0dcab57460194abb117aba1cb85",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":128,
              "y":60},
            "size":{
              "width":166,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7acce3fb2b0e411a9d4695d122802877",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":108,
              "y":290},
            "size":{
              "width":91,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"786f1b18a17d4052ab6df89cb7ac54e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":108,
                  "y":290},
                "size":{
                  "width":91,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/任务交接/u18.png"}},
{
          "id":"09cd60102014495881c516fb351a4f49",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":13,
              "y":108},
            "size":{
              "width":91,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f09c9ae4a8244107b43b16c6aac993c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":13,
                  "y":108},
                "size":{
                  "width":91,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c48daac3fa6b4aef86616966cdd898f1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":128,
              "y":105},
            "size":{
              "width":166,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"04ced08778bd4f2e9f64fd22aaea1a9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCCC},
            "location":{
              "x":330,
              "y":70},
            "size":{
              "width":305,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"439acb4061f74eaeb1e643f4a6884182",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCCC},
                "location":{
                  "x":330,
                  "y":70},
                "size":{
                  "width":305,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/asn列表_1/u22.png"}},
{
          "id":"212fe12f4d9d43e6b07e014c7d28aacd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":13,
              "y":153},
            "size":{
              "width":91,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae4e873ba5df4f40a7ff4195418a4a73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":13,
                  "y":153},
                "size":{
                  "width":91,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1582ac689aad4b3c8f7fbd51199686a6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":128,
              "y":150},
            "size":{
              "width":166,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e3eadf7b526c496785bfea2a162c6fa2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":78,
              "y":220},
            "size":{
              "width":150,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca7c76e3d7a447d69a8268fcf11ee683",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":78,
                  "y":220},
                "size":{
                  "width":150,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "13071ac0068a4b878def25eb3cf61403":{
      "scriptId":"u0"},
    "306df63fab42452eb319a5d03864383f":{
      "scriptId":"u1"},
    "ecac3225cb2c492d9aa7090b48c767c7":{
      "scriptId":"u2"},
    "f035f9b53ab14b72aa8bed20c8429c48":{
      "scriptId":"u3"},
    "c9a1ef7e7a554fbda7e984ac53d05446":{
      "scriptId":"u4"},
    "807358a708764773b9baa9d1ed2425f8":{
      "scriptId":"u5"},
    "60af62b46612448da5f982731e7bbc91":{
      "scriptId":"u6"},
    "c4a708071e014a08bc7a351c42e85848":{
      "scriptId":"u7"},
    "26c0563925d54e94a19fa14417deecf8":{
      "scriptId":"u8"},
    "0d31d4fc487a4c428fd0ed83624708f9":{
      "scriptId":"u9"},
    "9cf1dcb5c2044ab98b9978a58a9f952a":{
      "scriptId":"u10"},
    "1c5f59e7f5004d6eb3a7f3ffd7028747":{
      "scriptId":"u11"},
    "68c0f0dcab57460194abb117aba1cb85":{
      "scriptId":"u12"},
    "7acce3fb2b0e411a9d4695d122802877":{
      "scriptId":"u13"},
    "786f1b18a17d4052ab6df89cb7ac54e0":{
      "scriptId":"u14"},
    "09cd60102014495881c516fb351a4f49":{
      "scriptId":"u15"},
    "f09c9ae4a8244107b43b16c6aac993c6":{
      "scriptId":"u16"},
    "c48daac3fa6b4aef86616966cdd898f1":{
      "scriptId":"u17"},
    "04ced08778bd4f2e9f64fd22aaea1a9f":{
      "scriptId":"u18"},
    "439acb4061f74eaeb1e643f4a6884182":{
      "scriptId":"u19"},
    "212fe12f4d9d43e6b07e014c7d28aacd":{
      "scriptId":"u20"},
    "ae4e873ba5df4f40a7ff4195418a4a73":{
      "scriptId":"u21"},
    "1582ac689aad4b3c8f7fbd51199686a6":{
      "scriptId":"u22"},
    "e3eadf7b526c496785bfea2a162c6fa2":{
      "scriptId":"u23"},
    "ca7c76e3d7a447d69a8268fcf11ee683":{
      "scriptId":"u24"}}});