$axure.loadCurrentPage({
  "url":"循环盘点.html",
  "generationDate":new Date(1554888129708.36),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"3edc223152a7423b8db56bd56e92692d",
    "type":"Axure:Page",
    "name":"循环盘点",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"02dab9fb592e448d89dd0d63118d0e50",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":44},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"512fb5a00eb04f9fad2b1711283e1814",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":44},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/新标签 打开 盘点单列表",
                      "target":{
                        "targetType":"page",
                        "url":"盘点单列表.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true},
{
          "id":"cc0ee685202c44c7b95acf326fceb100",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":0,
              "y":2},
            "size":{
              "width":950,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a318a09f724479f8baa2938403998da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":0,
                  "y":2},
                "size":{
                  "width":950,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库信息/u144.png"}},
{
          "id":"7e6402775d7d467eb1480919df57f028",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":6,
              "y":7},
            "size":{
              "width":122,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"766d749f5ae8402485004df43c882e84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":6,
                  "y":7},
                "size":{
                  "width":122,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5993a821b69d45079e07e9d05fa98528",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":111,
              "y":9},
            "size":{
              "width":62,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a42b86a0cec495095a6000679d6ce2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":111,
                  "y":9},
                "size":{
                  "width":62,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50acf406a7cf4a6d9d1f4af17d025810",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":173,
              "y":9},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e175b7e72d3347dfb067c09624382ac7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":173,
                  "y":9},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8fadfb20673149eb976dc8274ca21f39",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":287,
              "y":9},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed6c23e42fec42779d4292cdb5c54a63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":287,
                  "y":9},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7475f01829944b929ec352d48f5da3f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":403,
              "y":9},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfb71e6615a44f7a9c19af0ef2109ed2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":403,
                  "y":9},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b752ee319f7445eb9672805dceace100",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":513,
              "y":9},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e322d5cb55554aa6a0ba034a076d73a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":513,
                  "y":9},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3cda70367a4341dfa6db5ecce6b8c387",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":624,
              "y":9},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"759edea880eb414a8d2e92394ab012f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":624,
                  "y":9},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff97621ada704fcdb5916edbddd55d69",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":722,
              "y":9},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c0cde9b6e67438db7613b05d81d631c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":722,
                  "y":9},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"caceb407fd5b407fab3fc12a0a809a31",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":816,
              "y":9},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4363750f03de499fa7181e994505c281",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":816,
                  "y":9},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d83b6eb54c23430ea887743f88123075",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":1,
              "y":453},
            "size":{
              "width":949,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdd51b182b7b49f28ce94a137c10face",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":1,
                  "y":453},
                "size":{
                  "width":949,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/盘点策略/u20.png"}},
{
          "id":"3494d7e5854b44d9b7f6b673a9867bc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":808,
              "y":459},
            "size":{
              "width":133,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b604fa369d834734bdf1a14577b6a5b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":808,
                  "y":459},
                "size":{
                  "width":133,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f269d394aad4e5a8a68ee08ff5ecb12",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":87},
            "size":{
              "width":45,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fc7b8cb23a04a748f58abda73831d2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":87},
                "size":{
                  "width":45,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8dcf208b1c784825931f4b87280b60c2",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":83},
            "size":{
              "width":99,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"6030edf683eb4101ad70a646643c24c1",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":130},
            "size":{
              "width":323,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbb5d98c14744751aedbbf1be6969b1e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d5ac5f050b504a91870ca28380bdc499",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/循环盘点/u30.png"}},
{
              "id":"0aa1afb50525415dad957eac80e7182a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":20},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"40fb0c568e8a475ea5c4b824b65b657e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":20},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u546.png"}},
{
              "id":"26450782616b4eaa9eb25d47031f142b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8baec1ce7d6a42dc889faf3ce345faf3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u546.png"}},
{
              "id":"481e2b6a80dd43ccb7a34b9dc60fce1c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"91a95f51688348d798f5ff6c10123462",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u546.png"}},
{
              "id":"119046cf237c43128df8bef355873b66",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":80},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3151e919e3a342f282fd2ca4cd3109d8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":80},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u546.png"}},
{
              "id":"51d14bcfd17e454397de4ca277553431",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":100},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"769fb53c65834d85ad271613f124e358",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":100},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u546.png"}},
{
              "id":"69fecb02c84847f68579eda171d44d07",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8520140e560f447ca12782874d40ca4a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u546.png"}},
{
              "id":"5b5c926fd6c44b35b41b548807fb928c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":140},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b50741b1598242469a47f0ef4e70e3f6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":140},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u742.png"}},
{
              "id":"3615603fb66445c18154dbb0dd0d3098",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":154,
                  "y":0},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a14cb020fe674b01b8c5958e3a4f70ca",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":154,
                      "y":0},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/循环盘点/u30.png"}},
{
              "id":"6e761739aae84a7785d0e96ac23e3235",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":20},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"af0094acdb644d90904765352fc6e6f6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":154,
                      "y":20},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u546.png"}},
{
              "id":"951072c0bd2942fea7d555630f820d2a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":40},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5b1c9f6a4a4b45aeb61c97ac83eb2031",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":154,
                      "y":40},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u546.png"}},
{
              "id":"e32f38197c154a7a8b5131ad672cd90b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":60},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0446c393150041d6b18692067c52a531",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":154,
                      "y":60},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u546.png"}},
{
              "id":"67bbbd11786b411f87df34977f6ec0b5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":80},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4d2ff6057b0f4e379dc986f5da69d733",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":154,
                      "y":80},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u546.png"}},
{
              "id":"5932f0ee185c424e8c40b285ac45d51d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":100},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ae9c08339c9e4041a793a8813d0c49de",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":154,
                      "y":100},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u546.png"}},
{
              "id":"bb91ba816fe14984bff721a8fb0ccd9f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":120},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"906ffe2013eb49a1aed12699d638bbac",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":154,
                      "y":120},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u546.png"}},
{
              "id":"0c500c86f47d4b7f86642b6be40c5d93",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":154,
                  "y":140},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5ad24b4a2e3f4e73bc79852bb9ad44bc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":154,
                      "y":140},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u742.png"}},
{
              "id":"40bd916111fa482797357361099fbc7d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":226,
                  "y":0},
                "size":{
                  "width":97,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"71400e2ec9034f0fbe3180105f861cf5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":226,
                      "y":0},
                    "size":{
                      "width":97,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/循环盘点/u36.png"}},
{
              "id":"e111b2c88baa4436a4dcaa7ccaef4404",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":226,
                  "y":20},
                "size":{
                  "width":97,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"af144e9841c74aac888fe57c4cdf3d09",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":226,
                      "y":20},
                    "size":{
                      "width":97,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/循环盘点/u44.png"}},
{
              "id":"e1f3f60dc904444289190f564d9377d6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":226,
                  "y":40},
                "size":{
                  "width":97,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c63daa84f7c444e6bd54ba72116f924e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":226,
                      "y":40},
                    "size":{
                      "width":97,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/循环盘点/u44.png"}},
{
              "id":"2999f3b82ffe41c0b969b74354cd4dd2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":226,
                  "y":60},
                "size":{
                  "width":97,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"df95f3ea3af147fe9f14262a6ce503d9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":226,
                      "y":60},
                    "size":{
                      "width":97,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/循环盘点/u44.png"}},
{
              "id":"9b807b1195ad46448c4927340f4cc82a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":226,
                  "y":80},
                "size":{
                  "width":97,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2cc650ceb3c3473dae9e6df061964224",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":226,
                      "y":80},
                    "size":{
                      "width":97,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/循环盘点/u44.png"}},
{
              "id":"9bd04ddeefda4709a66068b9f31a58d6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":226,
                  "y":100},
                "size":{
                  "width":97,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"55fb1d17aa0745c59f3f5e77e9e01b5f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":226,
                      "y":100},
                    "size":{
                      "width":97,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/循环盘点/u44.png"}},
{
              "id":"0dcafe27f73d45caae2f0cc0ccc8c24a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":226,
                  "y":120},
                "size":{
                  "width":97,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"df513212050443e8945f713adf65e44a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":226,
                      "y":120},
                    "size":{
                      "width":97,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/循环盘点/u44.png"}},
{
              "id":"f49e04fad1a94e75bc8857cb730ecc45",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":226,
                  "y":140},
                "size":{
                  "width":97,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"68937847d7634e30a042e6e974c8d2ae",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":226,
                      "y":140},
                    "size":{
                      "width":97,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/循环盘点/u92.png"}},
{
              "id":"1e49fc297a92401b927ff2508e713c34",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":72,
                  "y":0},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2fadc65d6bab40f2814440cd2625db60",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":72,
                      "y":0},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/循环盘点/u32.png"}},
{
              "id":"bd36148d02af46f392a62aa8936847df",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":20},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fe8ab238f8e64e0fb90c93999611f373",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":72,
                      "y":20},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/月台维护/u53.png"}},
{
              "id":"abedeadf406f4db09267834f61e65059",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":40},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c69100b51d9f41acaa10555b1e0236a3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":72,
                      "y":40},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/月台维护/u53.png"}},
{
              "id":"2808fc1fa67b41c2b47bb9bbfeddfcb2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":60},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e827fc438bcb457092e399e34658bd48",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":72,
                      "y":60},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/月台维护/u53.png"}},
{
              "id":"0ab1382d5f47491f98926fdb864e1bc9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":80},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"92446ac3ea744dcda1f1f4871cd2e072",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":72,
                      "y":80},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/月台维护/u53.png"}},
{
              "id":"1c47ed6a41564934b6ed16c0c0d166dc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":100},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"39055f82d61640689c1fe458ba31b645",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":72,
                      "y":100},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/月台维护/u53.png"}},
{
              "id":"83db3bbe18fd456798a44c733168b2fc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":120},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"34320b0d9a944afc84c37d40de2dde10",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":72,
                      "y":120},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/月台维护/u53.png"}},
{
              "id":"c5ebe1bfd02f4b44a1de9f118af27c18",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":140},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"74d7fdca10574f46814be88839a73999",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":72,
                      "y":140},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/月台维护/u143.png"}}]},
{
          "id":"4560ec062d714e53a2df9150eb5f8c26",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":402,
              "y":86},
            "size":{
              "width":72,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba95cd2ca1ce49228f5d4e74fe132d58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":402,
                  "y":86},
                "size":{
                  "width":72,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ecf036b7bce94650a2874a9a655022a3",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":474,
              "y":84},
            "size":{
              "width":103,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"102c30b513d24604a4acb64e84a66835",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCCC},
            "location":{
              "x":6,
              "y":343},
            "size":{
              "width":908,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a123995361d4a37b7d7b06da5f0154c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCCC},
                "location":{
                  "x":6,
                  "y":343},
                "size":{
                  "width":908,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/循环盘点/u97.png"}},
{
          "id":"4e2ac745e6394dab866908a73503f254",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCCC},
            "location":{
              "x":579,
              "y":82},
            "size":{
              "width":39,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56129228f383421989d220c5b922112a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCCC},
                "location":{
                  "x":579,
                  "y":82},
                "size":{
                  "width":39,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/标准盘点/u217.png"}},
{
          "id":"be01a84eafe14204ab2a432ab0eab965",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":199,
              "y":87},
            "size":{
              "width":75,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1faf3914b7a4a0183dfec93cf7ff1b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":199,
                  "y":87},
                "size":{
                  "width":75,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba64e5c655f848af8705d68fe4e8e296",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":264,
              "y":85},
            "size":{
              "width":103,
              "height":22}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "02dab9fb592e448d89dd0d63118d0e50":{
      "scriptId":"u0"},
    "512fb5a00eb04f9fad2b1711283e1814":{
      "scriptId":"u1"},
    "cc0ee685202c44c7b95acf326fceb100":{
      "scriptId":"u2"},
    "3a318a09f724479f8baa2938403998da":{
      "scriptId":"u3"},
    "7e6402775d7d467eb1480919df57f028":{
      "scriptId":"u4"},
    "766d749f5ae8402485004df43c882e84":{
      "scriptId":"u5"},
    "5993a821b69d45079e07e9d05fa98528":{
      "scriptId":"u6"},
    "0a42b86a0cec495095a6000679d6ce2a":{
      "scriptId":"u7"},
    "50acf406a7cf4a6d9d1f4af17d025810":{
      "scriptId":"u8"},
    "e175b7e72d3347dfb067c09624382ac7":{
      "scriptId":"u9"},
    "8fadfb20673149eb976dc8274ca21f39":{
      "scriptId":"u10"},
    "ed6c23e42fec42779d4292cdb5c54a63":{
      "scriptId":"u11"},
    "7475f01829944b929ec352d48f5da3f4":{
      "scriptId":"u12"},
    "bfb71e6615a44f7a9c19af0ef2109ed2":{
      "scriptId":"u13"},
    "b752ee319f7445eb9672805dceace100":{
      "scriptId":"u14"},
    "e322d5cb55554aa6a0ba034a076d73a6":{
      "scriptId":"u15"},
    "3cda70367a4341dfa6db5ecce6b8c387":{
      "scriptId":"u16"},
    "759edea880eb414a8d2e92394ab012f3":{
      "scriptId":"u17"},
    "ff97621ada704fcdb5916edbddd55d69":{
      "scriptId":"u18"},
    "0c0cde9b6e67438db7613b05d81d631c":{
      "scriptId":"u19"},
    "caceb407fd5b407fab3fc12a0a809a31":{
      "scriptId":"u20"},
    "4363750f03de499fa7181e994505c281":{
      "scriptId":"u21"},
    "d83b6eb54c23430ea887743f88123075":{
      "scriptId":"u22"},
    "cdd51b182b7b49f28ce94a137c10face":{
      "scriptId":"u23"},
    "3494d7e5854b44d9b7f6b673a9867bc3":{
      "scriptId":"u24"},
    "b604fa369d834734bdf1a14577b6a5b4":{
      "scriptId":"u25"},
    "7f269d394aad4e5a8a68ee08ff5ecb12":{
      "scriptId":"u26"},
    "0fc7b8cb23a04a748f58abda73831d2a":{
      "scriptId":"u27"},
    "8dcf208b1c784825931f4b87280b60c2":{
      "scriptId":"u28"},
    "6030edf683eb4101ad70a646643c24c1":{
      "scriptId":"u29"},
    "dbb5d98c14744751aedbbf1be6969b1e":{
      "scriptId":"u30"},
    "d5ac5f050b504a91870ca28380bdc499":{
      "scriptId":"u31"},
    "1e49fc297a92401b927ff2508e713c34":{
      "scriptId":"u32"},
    "2fadc65d6bab40f2814440cd2625db60":{
      "scriptId":"u33"},
    "3615603fb66445c18154dbb0dd0d3098":{
      "scriptId":"u34"},
    "a14cb020fe674b01b8c5958e3a4f70ca":{
      "scriptId":"u35"},
    "40bd916111fa482797357361099fbc7d":{
      "scriptId":"u36"},
    "71400e2ec9034f0fbe3180105f861cf5":{
      "scriptId":"u37"},
    "0aa1afb50525415dad957eac80e7182a":{
      "scriptId":"u38"},
    "40fb0c568e8a475ea5c4b824b65b657e":{
      "scriptId":"u39"},
    "bd36148d02af46f392a62aa8936847df":{
      "scriptId":"u40"},
    "fe8ab238f8e64e0fb90c93999611f373":{
      "scriptId":"u41"},
    "6e761739aae84a7785d0e96ac23e3235":{
      "scriptId":"u42"},
    "af0094acdb644d90904765352fc6e6f6":{
      "scriptId":"u43"},
    "e111b2c88baa4436a4dcaa7ccaef4404":{
      "scriptId":"u44"},
    "af144e9841c74aac888fe57c4cdf3d09":{
      "scriptId":"u45"},
    "26450782616b4eaa9eb25d47031f142b":{
      "scriptId":"u46"},
    "8baec1ce7d6a42dc889faf3ce345faf3":{
      "scriptId":"u47"},
    "abedeadf406f4db09267834f61e65059":{
      "scriptId":"u48"},
    "c69100b51d9f41acaa10555b1e0236a3":{
      "scriptId":"u49"},
    "951072c0bd2942fea7d555630f820d2a":{
      "scriptId":"u50"},
    "5b1c9f6a4a4b45aeb61c97ac83eb2031":{
      "scriptId":"u51"},
    "e1f3f60dc904444289190f564d9377d6":{
      "scriptId":"u52"},
    "c63daa84f7c444e6bd54ba72116f924e":{
      "scriptId":"u53"},
    "481e2b6a80dd43ccb7a34b9dc60fce1c":{
      "scriptId":"u54"},
    "91a95f51688348d798f5ff6c10123462":{
      "scriptId":"u55"},
    "2808fc1fa67b41c2b47bb9bbfeddfcb2":{
      "scriptId":"u56"},
    "e827fc438bcb457092e399e34658bd48":{
      "scriptId":"u57"},
    "e32f38197c154a7a8b5131ad672cd90b":{
      "scriptId":"u58"},
    "0446c393150041d6b18692067c52a531":{
      "scriptId":"u59"},
    "2999f3b82ffe41c0b969b74354cd4dd2":{
      "scriptId":"u60"},
    "df95f3ea3af147fe9f14262a6ce503d9":{
      "scriptId":"u61"},
    "119046cf237c43128df8bef355873b66":{
      "scriptId":"u62"},
    "3151e919e3a342f282fd2ca4cd3109d8":{
      "scriptId":"u63"},
    "0ab1382d5f47491f98926fdb864e1bc9":{
      "scriptId":"u64"},
    "92446ac3ea744dcda1f1f4871cd2e072":{
      "scriptId":"u65"},
    "67bbbd11786b411f87df34977f6ec0b5":{
      "scriptId":"u66"},
    "4d2ff6057b0f4e379dc986f5da69d733":{
      "scriptId":"u67"},
    "9b807b1195ad46448c4927340f4cc82a":{
      "scriptId":"u68"},
    "2cc650ceb3c3473dae9e6df061964224":{
      "scriptId":"u69"},
    "51d14bcfd17e454397de4ca277553431":{
      "scriptId":"u70"},
    "769fb53c65834d85ad271613f124e358":{
      "scriptId":"u71"},
    "1c47ed6a41564934b6ed16c0c0d166dc":{
      "scriptId":"u72"},
    "39055f82d61640689c1fe458ba31b645":{
      "scriptId":"u73"},
    "5932f0ee185c424e8c40b285ac45d51d":{
      "scriptId":"u74"},
    "ae9c08339c9e4041a793a8813d0c49de":{
      "scriptId":"u75"},
    "9bd04ddeefda4709a66068b9f31a58d6":{
      "scriptId":"u76"},
    "55fb1d17aa0745c59f3f5e77e9e01b5f":{
      "scriptId":"u77"},
    "69fecb02c84847f68579eda171d44d07":{
      "scriptId":"u78"},
    "8520140e560f447ca12782874d40ca4a":{
      "scriptId":"u79"},
    "83db3bbe18fd456798a44c733168b2fc":{
      "scriptId":"u80"},
    "34320b0d9a944afc84c37d40de2dde10":{
      "scriptId":"u81"},
    "bb91ba816fe14984bff721a8fb0ccd9f":{
      "scriptId":"u82"},
    "906ffe2013eb49a1aed12699d638bbac":{
      "scriptId":"u83"},
    "0dcafe27f73d45caae2f0cc0ccc8c24a":{
      "scriptId":"u84"},
    "df513212050443e8945f713adf65e44a":{
      "scriptId":"u85"},
    "5b5c926fd6c44b35b41b548807fb928c":{
      "scriptId":"u86"},
    "b50741b1598242469a47f0ef4e70e3f6":{
      "scriptId":"u87"},
    "c5ebe1bfd02f4b44a1de9f118af27c18":{
      "scriptId":"u88"},
    "74d7fdca10574f46814be88839a73999":{
      "scriptId":"u89"},
    "0c500c86f47d4b7f86642b6be40c5d93":{
      "scriptId":"u90"},
    "5ad24b4a2e3f4e73bc79852bb9ad44bc":{
      "scriptId":"u91"},
    "f49e04fad1a94e75bc8857cb730ecc45":{
      "scriptId":"u92"},
    "68937847d7634e30a042e6e974c8d2ae":{
      "scriptId":"u93"},
    "4560ec062d714e53a2df9150eb5f8c26":{
      "scriptId":"u94"},
    "ba95cd2ca1ce49228f5d4e74fe132d58":{
      "scriptId":"u95"},
    "ecf036b7bce94650a2874a9a655022a3":{
      "scriptId":"u96"},
    "102c30b513d24604a4acb64e84a66835":{
      "scriptId":"u97"},
    "4a123995361d4a37b7d7b06da5f0154c":{
      "scriptId":"u98"},
    "4e2ac745e6394dab866908a73503f254":{
      "scriptId":"u99"},
    "56129228f383421989d220c5b922112a":{
      "scriptId":"u100"},
    "be01a84eafe14204ab2a432ab0eab965":{
      "scriptId":"u101"},
    "b1faf3914b7a4a0183dfec93cf7ff1b8":{
      "scriptId":"u102"},
    "ba64e5c655f848af8705d68fe4e8e296":{
      "scriptId":"u103"}}});