$axure.loadCurrentPage({
  "url":"new_page_1_1.html",
  "generationDate":new Date(1554888137914.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"93f32ffed1e94a78a8791deea5aded12",
    "type":"Axure:Page",
    "name":"New Page 1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c56f2eb6ec444be99e0fc894c63916e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":0,
              "y":6},
            "size":{
              "width":305,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55b9ca89e11f4238aafc0f4de286978e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":0,
                  "y":6},
                "size":{
                  "width":305,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u6.png"}},
{
          "id":"0fd4ac8c877e48b989c3a21b7054eb54",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":4,
              "y":11},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f201b0ce61246c39c19dd04fcddc73f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":4,
                  "y":11},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e015e8e0a2004993a96f7c8d87942d54",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":136,
              "y":13},
            "size":{
              "width":164,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"619a22a15c1f48dc895176052ea17a77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":136,
                  "y":13},
                "size":{
                  "width":164,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"418a2995302242659474692e5ddafb98",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":1,
              "y":380},
            "size":{
              "width":308,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bebedf53806460482662631ac929f22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":1,
                  "y":380},
                "size":{
                  "width":308,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u12.png"}},
{
          "id":"9118847ed505455bbafe5b46804bbebe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":144,
              "y":386},
            "size":{
              "width":162,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1247d86e92554603b55e5651fdcd3464",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":144,
                  "y":386},
                "size":{
                  "width":162,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d646b8fb0d5b41febaf6e9c62ebba817",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":14,
              "y":55},
            "size":{
              "width":78,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7770023dc41048c3b7114da22497dcca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":14,
                  "y":55},
                "size":{
                  "width":78,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa43401d8d23422fb989cc123a654ca9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":7,
              "y":140},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d55f2c9b4d24b489363ab1bb58ecea1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":7,
                  "y":140},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eba921292c2649bdafdacbd3c91ef821",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":105,
              "y":141},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7a192ebc5dcc449d951764c836f39c3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":14,
              "y":93},
            "size":{
              "width":78,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6022e107bed54958aa33cd8add5f6d4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":14,
                  "y":93},
                "size":{
                  "width":78,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95b567da1d7a47fc975296dee0b77e93",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":7,
              "y":264},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9258f1236b474d9b8a00da2cf14c58f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":7,
                  "y":264},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da84c806cc3244a082fe5f22dfa8dfe4",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":105,
              "y":95},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d063409abb04435781a880fb811e1820",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":105,
              "y":55},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c17a74b4df16473ab100ba4074d4ac90",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":105,
              "y":261},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"cb09c21e1334412b8947a58cbb3a96cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":7,
              "y":221},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b9c4aa2888d4ec889c031a195b654a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":7,
                  "y":221},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"551219166d50466db342d4d1ecdbacde",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":105,
              "y":221},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ce0d467f5b7946c5af4a8ccb198c209a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":5,
              "y":306},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cb2631a588047eeab4e612aa2443ef9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":5,
                  "y":306},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e3ccd79bfd04562bb8b859a8fe60fab",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":105,
              "y":304},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7b8bdbbdd5d94be79ced1af0914c4c6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":5,
              "y":346},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"765965dffbe949d1935bbcfbe80297f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":5,
                  "y":346},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2d979aba06a4e2dbb1cc08deb2500a2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":105,
              "y":343},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1c4b747c58354aeb83659a6126e2ed80",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":7,
              "y":184},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5315aac78a9d472c82a9ed03db7f60a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":7,
                  "y":184},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5491ae6e88c48b3ad9683589c10f539",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":105,
              "y":184},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "c56f2eb6ec444be99e0fc894c63916e4":{
      "scriptId":"u0"},
    "55b9ca89e11f4238aafc0f4de286978e":{
      "scriptId":"u1"},
    "0fd4ac8c877e48b989c3a21b7054eb54":{
      "scriptId":"u2"},
    "3f201b0ce61246c39c19dd04fcddc73f":{
      "scriptId":"u3"},
    "e015e8e0a2004993a96f7c8d87942d54":{
      "scriptId":"u4"},
    "619a22a15c1f48dc895176052ea17a77":{
      "scriptId":"u5"},
    "418a2995302242659474692e5ddafb98":{
      "scriptId":"u6"},
    "1bebedf53806460482662631ac929f22":{
      "scriptId":"u7"},
    "9118847ed505455bbafe5b46804bbebe":{
      "scriptId":"u8"},
    "1247d86e92554603b55e5651fdcd3464":{
      "scriptId":"u9"},
    "d646b8fb0d5b41febaf6e9c62ebba817":{
      "scriptId":"u10"},
    "7770023dc41048c3b7114da22497dcca":{
      "scriptId":"u11"},
    "fa43401d8d23422fb989cc123a654ca9":{
      "scriptId":"u12"},
    "6d55f2c9b4d24b489363ab1bb58ecea1":{
      "scriptId":"u13"},
    "eba921292c2649bdafdacbd3c91ef821":{
      "scriptId":"u14"},
    "7a192ebc5dcc449d951764c836f39c3c":{
      "scriptId":"u15"},
    "6022e107bed54958aa33cd8add5f6d4c":{
      "scriptId":"u16"},
    "95b567da1d7a47fc975296dee0b77e93":{
      "scriptId":"u17"},
    "9258f1236b474d9b8a00da2cf14c58f5":{
      "scriptId":"u18"},
    "da84c806cc3244a082fe5f22dfa8dfe4":{
      "scriptId":"u19"},
    "d063409abb04435781a880fb811e1820":{
      "scriptId":"u20"},
    "c17a74b4df16473ab100ba4074d4ac90":{
      "scriptId":"u21"},
    "cb09c21e1334412b8947a58cbb3a96cf":{
      "scriptId":"u22"},
    "4b9c4aa2888d4ec889c031a195b654a1":{
      "scriptId":"u23"},
    "551219166d50466db342d4d1ecdbacde":{
      "scriptId":"u24"},
    "ce0d467f5b7946c5af4a8ccb198c209a":{
      "scriptId":"u25"},
    "1cb2631a588047eeab4e612aa2443ef9":{
      "scriptId":"u26"},
    "3e3ccd79bfd04562bb8b859a8fe60fab":{
      "scriptId":"u27"},
    "7b8bdbbdd5d94be79ced1af0914c4c6f":{
      "scriptId":"u28"},
    "765965dffbe949d1935bbcfbe80297f7":{
      "scriptId":"u29"},
    "b2d979aba06a4e2dbb1cc08deb2500a2":{
      "scriptId":"u30"},
    "1c4b747c58354aeb83659a6126e2ed80":{
      "scriptId":"u31"},
    "5315aac78a9d472c82a9ed03db7f60a9":{
      "scriptId":"u32"},
    "a5491ae6e88c48b3ad9683589c10f539":{
      "scriptId":"u33"}}});