$axure.loadCurrentPage({
  "url":"人工拆垛分拣.html",
  "generationDate":new Date(1554888137249.18),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"8996e813c91d4bd1bd47a5ea632bc39f",
    "type":"Axure:Page",
    "name":"人工拆垛分拣",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3d03c5f1e43345efac415aff554ae528",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "location":{
              "x":25,
              "y":225},
            "size":{
              "width":85,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"620812ef45e54b4ab2bcf32c9fcfe2f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":25,
                  "y":225},
                "size":{
                  "width":85,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31866c6ee47a41c48e926239c33449ae",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":222},
            "size":{
              "width":175,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0c85562a0e9d481fafcba680f23f138a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "size":{
              "width":305,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"849ee6bea9f24a92bf3403a35338ca91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "size":{
                  "width":305,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u6.png"}},
{
          "id":"d8b67127a046402ba6a68de6e34fbe99",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":4,
              "y":5},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca7a08181a5742578a6989cf9d40925d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":4,
                  "y":5},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6b65f35d9f9483abb763fd5c828a2c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":134,
              "y":6},
            "size":{
              "width":166,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7dc69f127c924c69a30687dc3074b5a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":134,
                  "y":6},
                "size":{
                  "width":166,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a017689811814cd99d02c7329f8c7a09",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":1,
              "y":451},
            "size":{
              "width":305,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa6528efc2fc46b48ca0e06fa92ce279",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":1,
                  "y":451},
                "size":{
                  "width":305,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u6.png"}},
{
          "id":"b48fc66e881f4a01b995486dc8734439",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":143,
              "y":457},
            "size":{
              "width":157,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13c28685c72546c49531801c1cff19af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":143,
                  "y":457},
                "size":{
                  "width":157,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee746b92b3104568bdb00e2822e4d599",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCCC},
            "location":{
              "x":318,
              "y":7},
            "size":{
              "width":452,
              "height":473}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f059d7c49c54aacae28b3e44aad8838",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCCC},
                "location":{
                  "x":318,
                  "y":7},
                "size":{
                  "width":452,
                  "height":473}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/人工拆垛分拣/u13.png"}},
{
          "id":"c88a60fdb62a4ce1a56e8e728affa72e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "location":{
              "x":25,
              "y":92},
            "size":{
              "width":59,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60a8b0af6dcf48b085da72612c082ca9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":25,
                  "y":92},
                "size":{
                  "width":59,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc49419aa3414aea9669ad34f16b9813",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":90},
            "size":{
              "width":175,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e9732cd73c4d4c22af326de67b74811a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "location":{
              "x":25,
              "y":133},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7345401face94d0ea5cc0a836bc7e46c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":25,
                  "y":133},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"022982df722c4c05abdcc48a89b809e5",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":130},
            "size":{
              "width":175,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"45693eb3716d4c4184594233a754d43b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":107,
              "y":349},
            "size":{
              "width":91,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d07a8469fac43f1bfa96375d404c291",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":107,
                  "y":349},
                "size":{
                  "width":91,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/任务交接/u18.png"}},
{
          "id":"102f955d67e347f8aabdb0ee7db4611e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":343,
              "y":338},
            "size":{
              "width":362,
              "height":132}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd27b745308e4aa7b84f6cb2835422e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":343,
                  "y":338},
                "size":{
                  "width":362,
                  "height":132}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/人工拆垛分拣/u23.png"}},
{
          "id":"eaf7f63d301140dc9788c5f71be1e629",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "location":{
              "x":25,
              "y":265},
            "size":{
              "width":85,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"534e79d671b240068a15062d64edc1b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":25,
                  "y":265},
                "size":{
                  "width":85,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74af838f7cdf4d73929b7175bedd2be3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":262},
            "size":{
              "width":175,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ae845bfea3f545aeabe6f4b325296b65",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":87,
              "y":379},
            "size":{
              "width":133,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b5453e6403043a596eee11b1b28ca01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":87,
                  "y":379},
                "size":{
                  "width":133,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/人工拆垛分拣/u28.png"}},
{
          "id":"63fb46db1b224066a3d83b193fbb6b79",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":25,
              "y":178},
            "size":{
              "width":85,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8252983a16884559a09af45a73a65638",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":25,
                  "y":178},
                "size":{
                  "width":85,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94196caaca5e41f6bab017ae14b0afdd",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":120,
              "y":175},
            "size":{
              "width":175,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "3d03c5f1e43345efac415aff554ae528":{
      "scriptId":"u0"},
    "620812ef45e54b4ab2bcf32c9fcfe2f5":{
      "scriptId":"u1"},
    "31866c6ee47a41c48e926239c33449ae":{
      "scriptId":"u2"},
    "0c85562a0e9d481fafcba680f23f138a":{
      "scriptId":"u3"},
    "849ee6bea9f24a92bf3403a35338ca91":{
      "scriptId":"u4"},
    "d8b67127a046402ba6a68de6e34fbe99":{
      "scriptId":"u5"},
    "ca7a08181a5742578a6989cf9d40925d":{
      "scriptId":"u6"},
    "f6b65f35d9f9483abb763fd5c828a2c8":{
      "scriptId":"u7"},
    "7dc69f127c924c69a30687dc3074b5a9":{
      "scriptId":"u8"},
    "a017689811814cd99d02c7329f8c7a09":{
      "scriptId":"u9"},
    "aa6528efc2fc46b48ca0e06fa92ce279":{
      "scriptId":"u10"},
    "b48fc66e881f4a01b995486dc8734439":{
      "scriptId":"u11"},
    "13c28685c72546c49531801c1cff19af":{
      "scriptId":"u12"},
    "ee746b92b3104568bdb00e2822e4d599":{
      "scriptId":"u13"},
    "4f059d7c49c54aacae28b3e44aad8838":{
      "scriptId":"u14"},
    "c88a60fdb62a4ce1a56e8e728affa72e":{
      "scriptId":"u15"},
    "60a8b0af6dcf48b085da72612c082ca9":{
      "scriptId":"u16"},
    "cc49419aa3414aea9669ad34f16b9813":{
      "scriptId":"u17"},
    "e9732cd73c4d4c22af326de67b74811a":{
      "scriptId":"u18"},
    "7345401face94d0ea5cc0a836bc7e46c":{
      "scriptId":"u19"},
    "022982df722c4c05abdcc48a89b809e5":{
      "scriptId":"u20"},
    "45693eb3716d4c4184594233a754d43b":{
      "scriptId":"u21"},
    "4d07a8469fac43f1bfa96375d404c291":{
      "scriptId":"u22"},
    "102f955d67e347f8aabdb0ee7db4611e":{
      "scriptId":"u23"},
    "cd27b745308e4aa7b84f6cb2835422e8":{
      "scriptId":"u24"},
    "eaf7f63d301140dc9788c5f71be1e629":{
      "scriptId":"u25"},
    "534e79d671b240068a15062d64edc1b6":{
      "scriptId":"u26"},
    "74af838f7cdf4d73929b7175bedd2be3":{
      "scriptId":"u27"},
    "ae845bfea3f545aeabe6f4b325296b65":{
      "scriptId":"u28"},
    "0b5453e6403043a596eee11b1b28ca01":{
      "scriptId":"u29"},
    "63fb46db1b224066a3d83b193fbb6b79":{
      "scriptId":"u30"},
    "8252983a16884559a09af45a73a65638":{
      "scriptId":"u31"},
    "94196caaca5e41f6bab017ae14b0afdd":{
      "scriptId":"u32"}}});