$axure.loadCurrentPage({
  "url":"接货任务.html",
  "generationDate":new Date(1554888137173.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"fcc46ff9a0ff457c8e78a819b41727a5",
    "type":"Axure:Page",
    "name":"接货任务",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"009c4cf646854af08df3f54ece8f9f86",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "location":{
              "x":30,
              "y":137},
            "size":{
              "width":59,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb9ec90741c745d39e7f031c98838541",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":30,
                  "y":137},
                "size":{
                  "width":59,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7550f0af3e6b484eb362a06b6e92fb33",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":109,
              "y":134},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2a91ded157c94c278258a3e279abe320",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":19,
              "y":181},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12e34fd58de34cc8b71c47ef047c5614",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":19,
                  "y":181},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"923627157ef64762a977f157621cdb63",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "fontName":"'Arial Black', 'Arial'",
            "fontSize":"11px",
            "fontWeight":"900",
            "location":{
              "x":109,
              "y":181},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7a5a639f35c749479e2b3899cbebb714",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "size":{
              "width":305,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb454ba4cd414afcb359102dfa92d990",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "size":{
                  "width":305,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u6.png"}},
{
          "id":"bceefe47b9074c1ebd7c73733881a907",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":4,
              "y":5},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5c22cc47de546939f2e5891e42963e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":4,
                  "y":5},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a60e2557627a4051858a4a005dd45865",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":134,
              "y":6},
            "size":{
              "width":166,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0601c7d5e474716918566c275326d28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":134,
                  "y":6},
                "size":{
                  "width":166,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dc599cc666a0461b95b686a87cb0e6cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":1,
              "y":451},
            "size":{
              "width":305,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"849287da58a34d24930794855ad37603",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":1,
                  "y":451},
                "size":{
                  "width":305,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u6.png"}},
{
          "id":"4a442430257d4d359da66d0543f30e5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":143,
              "y":457},
            "size":{
              "width":157,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f414d5885ced4bd59d0352ee17fb50f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":143,
                  "y":457},
                "size":{
                  "width":157,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68a7199392d4416eab7ee262a09aaef4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCCC},
            "location":{
              "x":318,
              "y":47},
            "size":{
              "width":622,
              "height":370}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e3beea9affc4af4a5b37ff65a69967c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCCC},
                "location":{
                  "x":318,
                  "y":47},
                "size":{
                  "width":622,
                  "height":370}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/接货任务/u16.png"}},
{
          "id":"426ab73cd2714a32b04f9af10b173312",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":30,
              "y":219},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60e4a97166dd4ec2846eaa2620bcbcfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":30,
                  "y":219},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53319e3ccb1f44c1a77688d09f19055a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":219},
            "size":{
              "width":190,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"bc15357e2cec420e8f836f7fc6e42ce0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":30,
              "y":254},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf74c0f232c44b9b8626c94d9d4d5ee5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":30,
                  "y":254},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4231a911c8bd4c509f15b8502f88e116",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":254},
            "size":{
              "width":190,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a1c2b60d6c2043b89991395ea440a060",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":305},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"74d8bf9d05424c88a955581e1ada5f53",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "location":{
              "x":30,
              "y":53},
            "size":{
              "width":59,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"496132b9b7864c59aadf951603473021",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":30,
                  "y":53},
                "size":{
                  "width":59,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"60678a5fb6fd4a089437ae6436f09241",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":109,
              "y":51},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2c167877730e4565a5c695101d00ff3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "location":{
              "x":30,
              "y":94},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18ca812302e34d748f2fe8fbb655866a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":30,
                  "y":94},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"657ce4dbd7be4648b87a0001749f26f9",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":109,
              "y":91},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "009c4cf646854af08df3f54ece8f9f86":{
      "scriptId":"u0"},
    "eb9ec90741c745d39e7f031c98838541":{
      "scriptId":"u1"},
    "7550f0af3e6b484eb362a06b6e92fb33":{
      "scriptId":"u2"},
    "2a91ded157c94c278258a3e279abe320":{
      "scriptId":"u3"},
    "12e34fd58de34cc8b71c47ef047c5614":{
      "scriptId":"u4"},
    "923627157ef64762a977f157621cdb63":{
      "scriptId":"u5"},
    "7a5a639f35c749479e2b3899cbebb714":{
      "scriptId":"u6"},
    "fb454ba4cd414afcb359102dfa92d990":{
      "scriptId":"u7"},
    "bceefe47b9074c1ebd7c73733881a907":{
      "scriptId":"u8"},
    "f5c22cc47de546939f2e5891e42963e6":{
      "scriptId":"u9"},
    "a60e2557627a4051858a4a005dd45865":{
      "scriptId":"u10"},
    "e0601c7d5e474716918566c275326d28":{
      "scriptId":"u11"},
    "dc599cc666a0461b95b686a87cb0e6cc":{
      "scriptId":"u12"},
    "849287da58a34d24930794855ad37603":{
      "scriptId":"u13"},
    "4a442430257d4d359da66d0543f30e5b":{
      "scriptId":"u14"},
    "f414d5885ced4bd59d0352ee17fb50f6":{
      "scriptId":"u15"},
    "68a7199392d4416eab7ee262a09aaef4":{
      "scriptId":"u16"},
    "9e3beea9affc4af4a5b37ff65a69967c":{
      "scriptId":"u17"},
    "426ab73cd2714a32b04f9af10b173312":{
      "scriptId":"u18"},
    "60e4a97166dd4ec2846eaa2620bcbcfb":{
      "scriptId":"u19"},
    "53319e3ccb1f44c1a77688d09f19055a":{
      "scriptId":"u20"},
    "bc15357e2cec420e8f836f7fc6e42ce0":{
      "scriptId":"u21"},
    "cf74c0f232c44b9b8626c94d9d4d5ee5":{
      "scriptId":"u22"},
    "4231a911c8bd4c509f15b8502f88e116":{
      "scriptId":"u23"},
    "a1c2b60d6c2043b89991395ea440a060":{
      "scriptId":"u24"},
    "74d8bf9d05424c88a955581e1ada5f53":{
      "scriptId":"u25"},
    "496132b9b7864c59aadf951603473021":{
      "scriptId":"u26"},
    "60678a5fb6fd4a089437ae6436f09241":{
      "scriptId":"u27"},
    "2c167877730e4565a5c695101d00ff3d":{
      "scriptId":"u28"},
    "18ca812302e34d748f2fe8fbb655866a":{
      "scriptId":"u29"},
    "657ce4dbd7be4648b87a0001749f26f9":{
      "scriptId":"u30"}}});