$axure.loadCurrentPage({
  "url":"平库接货.html",
  "generationDate":new Date(1554888137890.47),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"ee428f08343541e39d86d83e766f428d",
    "type":"Axure:Page",
    "name":"平库接货",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0c3c5c9764ba412ea38a0c3a64e217ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "size":{
              "width":305,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"576d160b309148fe96922c374e3da7e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "size":{
                  "width":305,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u6.png"}},
{
          "id":"dc490ce5a67d4750b367cd12a8062cf8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":4,
              "y":5},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e76547e8e91e4ffbad194203ef0e0bdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":4,
                  "y":5},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b8baa88c66c4b69837f1602242cb36b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":136,
              "y":7},
            "size":{
              "width":164,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee72d635f8eb4b8d94d54f8eca1bb735",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":136,
                  "y":7},
                "size":{
                  "width":164,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75b3ccf662524acaac27662915c0e7d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":1,
              "y":451},
            "size":{
              "width":308,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"700daa332a8a4eaca6572e08c214d899",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":1,
                  "y":451},
                "size":{
                  "width":308,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u12.png"}},
{
          "id":"2618489798a243389d61e94c30643ce8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":144,
              "y":457},
            "size":{
              "width":162,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14a93a57c1e643a5bf8961a38bcb0793",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":144,
                  "y":457},
                "size":{
                  "width":162,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b103cd6716d4c7d8cdb4dcf75430dfd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCCC},
            "location":{
              "x":353,
              "y":39},
            "size":{
              "width":347,
              "height":311}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d826a31f90ca47088b1799c8a08d2c92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCCC},
                "location":{
                  "x":353,
                  "y":39},
                "size":{
                  "width":347,
                  "height":311}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/平库接货/u10.png"}},
{
          "id":"811098d511ad4a40ae74918bfeab7012",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":22,
              "y":50},
            "size":{
              "width":78,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23ab71dd01ad43bebe2d91d9af33f15a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":50},
                "size":{
                  "width":78,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ebf27e0f707454f955b47c137de1133",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":112,
              "y":45},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7db2b5041fab4bbbbad8d818968e5bf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":22,
              "y":124},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"885266a8072c4e6692d8dbbf5a8a2326",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":124},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5eea6784a724e84a44ae2ae6942393e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":112,
              "y":123},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"35e723463eed440eb933ae934c8ac4cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":22,
              "y":84},
            "size":{
              "width":78,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"408cdeb5272a4ec7a2c76a7f796ccbdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":84},
                "size":{
                  "width":78,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6d59c9473fa4fbca971e9a8e9e3337c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":112,
              "y":83},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"677b9938e3554fcc811057c09d62b45f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":22,
              "y":166},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0efb6a53783748069cf12f0a6cbce337",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":166},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5fa7bc7518b4586b4e2fa96e918c7f7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":112,
              "y":165},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"abdfd982e127405fba983bfb57f99d04",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":100,
              "y":290},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aee08371424a4132ab17d23e5bfca13f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":100,
                  "y":290},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/平库接货/u24.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "0c3c5c9764ba412ea38a0c3a64e217ae":{
      "scriptId":"u0"},
    "576d160b309148fe96922c374e3da7e1":{
      "scriptId":"u1"},
    "dc490ce5a67d4750b367cd12a8062cf8":{
      "scriptId":"u2"},
    "e76547e8e91e4ffbad194203ef0e0bdd":{
      "scriptId":"u3"},
    "8b8baa88c66c4b69837f1602242cb36b":{
      "scriptId":"u4"},
    "ee72d635f8eb4b8d94d54f8eca1bb735":{
      "scriptId":"u5"},
    "75b3ccf662524acaac27662915c0e7d9":{
      "scriptId":"u6"},
    "700daa332a8a4eaca6572e08c214d899":{
      "scriptId":"u7"},
    "2618489798a243389d61e94c30643ce8":{
      "scriptId":"u8"},
    "14a93a57c1e643a5bf8961a38bcb0793":{
      "scriptId":"u9"},
    "7b103cd6716d4c7d8cdb4dcf75430dfd":{
      "scriptId":"u10"},
    "d826a31f90ca47088b1799c8a08d2c92":{
      "scriptId":"u11"},
    "811098d511ad4a40ae74918bfeab7012":{
      "scriptId":"u12"},
    "23ab71dd01ad43bebe2d91d9af33f15a":{
      "scriptId":"u13"},
    "3ebf27e0f707454f955b47c137de1133":{
      "scriptId":"u14"},
    "7db2b5041fab4bbbbad8d818968e5bf2":{
      "scriptId":"u15"},
    "885266a8072c4e6692d8dbbf5a8a2326":{
      "scriptId":"u16"},
    "d5eea6784a724e84a44ae2ae6942393e":{
      "scriptId":"u17"},
    "35e723463eed440eb933ae934c8ac4cf":{
      "scriptId":"u18"},
    "408cdeb5272a4ec7a2c76a7f796ccbdd":{
      "scriptId":"u19"},
    "b6d59c9473fa4fbca971e9a8e9e3337c":{
      "scriptId":"u20"},
    "677b9938e3554fcc811057c09d62b45f":{
      "scriptId":"u21"},
    "0efb6a53783748069cf12f0a6cbce337":{
      "scriptId":"u22"},
    "c5fa7bc7518b4586b4e2fa96e918c7f7":{
      "scriptId":"u23"},
    "abdfd982e127405fba983bfb57f99d04":{
      "scriptId":"u24"},
    "aee08371424a4132ab17d23e5bfca13f":{
      "scriptId":"u25"}}});