$axure.loadCurrentPage({
  "url":"new_page_1.html",
  "generationDate":new Date(1554888137689),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"3266a3c0afd44a9fbaadbbe54ac16a39",
    "type":"Axure:Page",
    "name":"New Page 1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e74504aaeb2a4512aa441729cc9ff712",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":151,
              "y":29},
            "size":{
              "width":305,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe39b5cc4b4c449e9c3d6fbac9a26d2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":151,
                  "y":29},
                "size":{
                  "width":305,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u6.png"}},
{
          "id":"8d41200b5576459688d74a36eb6a0371",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":155,
              "y":34},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9012c716c7e84aa4ba815da9183b900f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":155,
                  "y":34},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4495d557042c411699375f275aa4755d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":305,
              "y":36},
            "size":{
              "width":164,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d57b80545644e2db2377bb10f513a21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":305,
                  "y":36},
                "size":{
                  "width":164,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1aa091d6ae5542d0ae2b823349b3a86a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":152,
              "y":380},
            "size":{
              "width":308,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8eb371efa625455e8590b30faa473d50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":152,
                  "y":380},
                "size":{
                  "width":308,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u12.png"}},
{
          "id":"71987a8eee64421ca93808a2b6ba42b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":295,
              "y":386},
            "size":{
              "width":162,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45566f2427c84a959a83d81302d08557",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":295,
                  "y":386},
                "size":{
                  "width":162,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab6b217e199a44e7bfa35301e2886b53",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":166,
              "y":81},
            "size":{
              "width":78,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd54e451c67b4f32a9b8ea2dac99c320",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":166,
                  "y":81},
                "size":{
                  "width":78,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42d489acb1894701aad871fa81cf08ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":166,
              "y":164},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7e05bdb9b8c46828a5886542506f9f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":166,
                  "y":164},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2707ddb0e75a47e1b39e3a5651c18e3b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":256,
              "y":165},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"712e5f1c9f384b32a53a3eb3fe9ba7ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":166,
              "y":121},
            "size":{
              "width":78,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f64144e61af04c6293825356831b5aec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":166,
                  "y":121},
                "size":{
                  "width":78,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04bd971d09a4439f9d4fd894156d6e7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":166,
              "y":287},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23f025d11f85427a8b0d288d20044647",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":166,
                  "y":287},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28737d4514a3452c81275b667c9790a5",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":256,
              "y":123},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4923d1bbbc8b43498be309186665443a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":256,
              "y":81},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"80795767d8fd4da98297b5cccf80c905",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":256,
              "y":284},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a7cc5b3441db4b19972e16cc510a0f7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":166,
              "y":331},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd38938261e543bfb552cf075a6a4e9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":166,
                  "y":331},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9a454f4d18d4c63b634cbbb8498f779",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":256,
              "y":328},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0f58cfbde3184e97bfce50329114f5fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":166,
              "y":208},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7908acc971e4c87b0cacbb828a8b753",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":166,
                  "y":208},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"931e18f9a94e45e8a5839f625a1a0ca3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":256,
              "y":208},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5e1ff174512542cd8793fe98786ee8ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":166,
              "y":249},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"312cb2c65fef4cae976598f391f3998f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":166,
                  "y":249},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e74504aaeb2a4512aa441729cc9ff712":{
      "scriptId":"u0"},
    "fe39b5cc4b4c449e9c3d6fbac9a26d2b":{
      "scriptId":"u1"},
    "8d41200b5576459688d74a36eb6a0371":{
      "scriptId":"u2"},
    "9012c716c7e84aa4ba815da9183b900f":{
      "scriptId":"u3"},
    "4495d557042c411699375f275aa4755d":{
      "scriptId":"u4"},
    "2d57b80545644e2db2377bb10f513a21":{
      "scriptId":"u5"},
    "1aa091d6ae5542d0ae2b823349b3a86a":{
      "scriptId":"u6"},
    "8eb371efa625455e8590b30faa473d50":{
      "scriptId":"u7"},
    "71987a8eee64421ca93808a2b6ba42b9":{
      "scriptId":"u8"},
    "45566f2427c84a959a83d81302d08557":{
      "scriptId":"u9"},
    "ab6b217e199a44e7bfa35301e2886b53":{
      "scriptId":"u10"},
    "bd54e451c67b4f32a9b8ea2dac99c320":{
      "scriptId":"u11"},
    "42d489acb1894701aad871fa81cf08ca":{
      "scriptId":"u12"},
    "b7e05bdb9b8c46828a5886542506f9f8":{
      "scriptId":"u13"},
    "2707ddb0e75a47e1b39e3a5651c18e3b":{
      "scriptId":"u14"},
    "712e5f1c9f384b32a53a3eb3fe9ba7ac":{
      "scriptId":"u15"},
    "f64144e61af04c6293825356831b5aec":{
      "scriptId":"u16"},
    "04bd971d09a4439f9d4fd894156d6e7b":{
      "scriptId":"u17"},
    "23f025d11f85427a8b0d288d20044647":{
      "scriptId":"u18"},
    "28737d4514a3452c81275b667c9790a5":{
      "scriptId":"u19"},
    "4923d1bbbc8b43498be309186665443a":{
      "scriptId":"u20"},
    "80795767d8fd4da98297b5cccf80c905":{
      "scriptId":"u21"},
    "a7cc5b3441db4b19972e16cc510a0f7d":{
      "scriptId":"u22"},
    "dd38938261e543bfb552cf075a6a4e9f":{
      "scriptId":"u23"},
    "c9a454f4d18d4c63b634cbbb8498f779":{
      "scriptId":"u24"},
    "0f58cfbde3184e97bfce50329114f5fd":{
      "scriptId":"u25"},
    "e7908acc971e4c87b0cacbb828a8b753":{
      "scriptId":"u26"},
    "931e18f9a94e45e8a5839f625a1a0ca3":{
      "scriptId":"u27"},
    "5e1ff174512542cd8793fe98786ee8ac":{
      "scriptId":"u28"},
    "312cb2c65fef4cae976598f391f3998f":{
      "scriptId":"u29"}}});