$axure.loadCurrentPage({
  "url":"异动盘点.html",
  "generationDate":new Date(1554888129833),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"b95db9fd3dbb456293b22ad6dd36da35",
    "type":"Axure:Page",
    "name":"异动盘点",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1c7931aa6c404b8a8bfbf12be1fb8f5f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":44},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3e792dbaf2d44c33874903e38a0398f3",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":44},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/新标签 打开 盘点单列表",
                      "target":{
                        "targetType":"page",
                        "url":"盘点单列表.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true},
{
          "id":"ae2af5a390254b0caafcd9090efd8a19",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":0,
              "y":2},
            "size":{
              "width":950,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"745aeb2503e1441d98b02f2c6141a60f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":0,
                  "y":2},
                "size":{
                  "width":950,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库信息/u144.png"}},
{
          "id":"7db4b3e4961043f084cdfc8c527e7217",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":6,
              "y":7},
            "size":{
              "width":122,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5866d2ab9adc4c60ba14dc82324464b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":6,
                  "y":7},
                "size":{
                  "width":122,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dc3df445ae94434f9c4e9cc091de3d2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":111,
              "y":9},
            "size":{
              "width":62,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d1144b019d9490bad1c1f88571b35d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":111,
                  "y":9},
                "size":{
                  "width":62,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28d8417e2c044c8f9a5bcbe7f085e3ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":173,
              "y":9},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cfdc693cbf34a7f90e03726a6ca2755",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":173,
                  "y":9},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2dcc18ecc0ef48d1908486fb6f335d05",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":287,
              "y":9},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b2a265f858844dc9265b2cbd7329e9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":287,
                  "y":9},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fba2a1e2ed384b4b8d0cb4430e1b90fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":403,
              "y":9},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4723d0ccf01b43b8bbda2702d8e1ca4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":403,
                  "y":9},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"60dc037c66bf4b03a8fd4871528e747b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":513,
              "y":9},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20b31a62688a4173a921e3cafe89fb1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":513,
                  "y":9},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"51a70d2b4e5347b09d936bdd277f30d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":624,
              "y":9},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19d34de9e73a48879b17f734e38c3024",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":624,
                  "y":9},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8643a2dfd2cc4fd7877e72d91935fdf0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":722,
              "y":9},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a4aacc4e87544d18a40b5ca2c63c907",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":722,
                  "y":9},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7712e9c109884f35a356800b7707ab08",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":816,
              "y":9},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c38b014b46414a358ad289a5ef80ca2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":816,
                  "y":9},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0f26d87dadd4c9080405f5a4bb19192",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":1,
              "y":453},
            "size":{
              "width":949,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a0680a029fd4905a2045b4eceadf9c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":1,
                  "y":453},
                "size":{
                  "width":949,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/盘点策略/u20.png"}},
{
          "id":"22bb31a4d52f4af098081cbd90b2a02d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":808,
              "y":459},
            "size":{
              "width":133,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2d021ad3acf436d963a49d3156f7a51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":808,
                  "y":459},
                "size":{
                  "width":133,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dcaedcfe59594dfbb4303ceb5697b829",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":87},
            "size":{
              "width":45,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c4bc449a32844dea9efb815a476a1c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":87},
                "size":{
                  "width":45,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af7d473edea34ff79622ecec51e70c74",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":83},
            "size":{
              "width":99,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"df99d60d3669494bae1a7559a57f6ce7",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":130},
            "size":{
              "width":323,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6aad86bf84d342fdbe14c829873646a8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5877807df30a4960a5ac95e8cb6221a6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/循环盘点/u30.png"}},
{
              "id":"9efe8d7617124eeeafcb7ce103fb6e7c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":20},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"de03bd51e33343398e4b1e09276e9ced",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":20},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u546.png"}},
{
              "id":"7415ad55913f4bf5bb80645ec80c3585",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"193fef181b5649aeb17dae10ef125ac1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u546.png"}},
{
              "id":"46d8ec39aebe45fa8bc51776a6476d05",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ee5be5b80b4e484d852eea2324440806",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u546.png"}},
{
              "id":"59afca97ff114d0cb27427d567065356",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":80},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"25ba0dae18d94453bf0725e6e8b5d0b5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":80},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u546.png"}},
{
              "id":"60d54b5bf35b4f05a133339e1a6a5c62",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":100},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"95f2977911b04a5bab23d2208f1b9c19",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":100},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u546.png"}},
{
              "id":"0a67cb429fac4423bf623f92da28dc88",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1e4f2ee29fde4d9fb27f9bcffda6a829",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u546.png"}},
{
              "id":"d304327aeaf24189b5b774e62070d271",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":140},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b45d12e683a44a4b91ac31a95a5e28c9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":140},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u742.png"}},
{
              "id":"244a999701fb4afa839e8b3cd25d3112",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":154,
                  "y":0},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0abd05fe4dc1465aa23c46a03abb976c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":154,
                      "y":0},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/循环盘点/u30.png"}},
{
              "id":"0fe1bce0c128409e8e8b0c38a939049d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":20},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"72df29e652c1400898ca36ba915f9d7d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":154,
                      "y":20},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u546.png"}},
{
              "id":"2a6531c6d8a24c4ba415051c84a79cbf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":40},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e396a753d7534ae686a749e2f8ae0307",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":154,
                      "y":40},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u546.png"}},
{
              "id":"b5e4aac39adc42b2a1f71148d0b5ed95",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":60},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"aac3f159e6be4a5a9ed7c439a27f062e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":154,
                      "y":60},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u546.png"}},
{
              "id":"785e05f8e9d342d2b95684cad3ec2451",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":80},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"77c28277855d41e4ad30dc6988776110",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":154,
                      "y":80},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u546.png"}},
{
              "id":"8b886311eb19498aa31ac7b603ee8d62",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":100},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a5adadceac3247d8b7ba3a548a8e15e6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":154,
                      "y":100},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u546.png"}},
{
              "id":"16571abecd3a47d3be3b824c7d22cdba",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":120},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"684e623b983648d9b051427aeabdfe32",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":154,
                      "y":120},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u546.png"}},
{
              "id":"418f28848c2e45759a5aa7dc5f2fe9d8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":154,
                  "y":140},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c98b1a39fa3c489894a7039bbf324273",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":154,
                      "y":140},
                    "size":{
                      "width":72,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u742.png"}},
{
              "id":"40f2faf8730240e499db47aeb870bb0a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":226,
                  "y":0},
                "size":{
                  "width":97,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"077b195e769a48cbb5ebf83f7e53004f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":226,
                      "y":0},
                    "size":{
                      "width":97,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/循环盘点/u36.png"}},
{
              "id":"260c99e2507d4665b5082d4679fc76da",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":226,
                  "y":20},
                "size":{
                  "width":97,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"93cda2282aff4a6cbc6b9dc7722f0da2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":226,
                      "y":20},
                    "size":{
                      "width":97,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/循环盘点/u44.png"}},
{
              "id":"409f4789e0c042a0a6628776b86d3950",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":226,
                  "y":40},
                "size":{
                  "width":97,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"86953f96f6b24d2487f1a5af6421e37f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":226,
                      "y":40},
                    "size":{
                      "width":97,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/循环盘点/u44.png"}},
{
              "id":"37897f63898c4b8991bfa650ad747314",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":226,
                  "y":60},
                "size":{
                  "width":97,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"62de23de404c42e1bd2f1adf4610f49f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":226,
                      "y":60},
                    "size":{
                      "width":97,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/循环盘点/u44.png"}},
{
              "id":"7d237efd4a14418a9525885f2b8994be",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":226,
                  "y":80},
                "size":{
                  "width":97,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3eed471c397c4e1088415a79349ba4e8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":226,
                      "y":80},
                    "size":{
                      "width":97,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/循环盘点/u44.png"}},
{
              "id":"90f5a3ea0c604d19b7e0159e80d61ef6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":226,
                  "y":100},
                "size":{
                  "width":97,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"277560e0cbe64ff7a59fcf8ba95fcb9c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":226,
                      "y":100},
                    "size":{
                      "width":97,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/循环盘点/u44.png"}},
{
              "id":"fb2c5d11a3724b82939ed2cb9ef78926",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":226,
                  "y":120},
                "size":{
                  "width":97,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d880ac75560f47ae918408397f10339b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":226,
                      "y":120},
                    "size":{
                      "width":97,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/循环盘点/u44.png"}},
{
              "id":"25f1010cf3a345bca42c161fc0b24d25",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":226,
                  "y":140},
                "size":{
                  "width":97,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9cee7e56965f4d9cbfbb944e1f825f63",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":226,
                      "y":140},
                    "size":{
                      "width":97,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/循环盘点/u92.png"}},
{
              "id":"8ec8612c63204f0fba5e4faf2534b27c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":72,
                  "y":0},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"03e00899caae479cb67ad754c9bc10ab",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":72,
                      "y":0},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/循环盘点/u32.png"}},
{
              "id":"e0178647a6f44fbaa3e968fc30adfb17",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":20},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c1fbd8cb468b4bc4998b5794e53c8309",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":72,
                      "y":20},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/月台维护/u53.png"}},
{
              "id":"2beefcfaad5e4bf3b73eb251ca5d3fe7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":40},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"43a531a5bc9d4133b12458137c4e38b9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":72,
                      "y":40},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/月台维护/u53.png"}},
{
              "id":"f1ea68e6a4f44e408a2bdf7ef1e2c7b2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":60},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5bd0f9dfd6e74024bd6013c693916dcf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":72,
                      "y":60},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/月台维护/u53.png"}},
{
              "id":"c2a0fcf142c442e38205d460646294a5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":80},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"da332974bf81410c8ad030448993369e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":72,
                      "y":80},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/月台维护/u53.png"}},
{
              "id":"d97a321cc8e544fd84f2c2ec87d7548b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":100},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9623ff45023f413e84eee666e3b13c05",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":72,
                      "y":100},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/月台维护/u53.png"}},
{
              "id":"71b950dc7b4246dc9797726b2e0461de",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":120},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f991cc41b661422c8741b564a1c3d535",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":72,
                      "y":120},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/月台维护/u53.png"}},
{
              "id":"8faff5cb14b64c778df480c462b2d816",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":140},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"04a861a2e26f4a568bf75d0002c0389b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":72,
                      "y":140},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/月台维护/u143.png"}}]},
{
          "id":"02eac410bbcc4d19874a037c0e92365c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":182,
              "y":86},
            "size":{
              "width":48,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"096e37de312b48b488efa84552b66adb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":182,
                  "y":86},
                "size":{
                  "width":48,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"63828578dd644efc80235c5d47d3a6cf",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":239,
              "y":84},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"ce84ce648fa44d91963750790e160e4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCCC},
            "location":{
              "x":12,
              "y":343},
            "size":{
              "width":908,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"795a71504b904c508da5e99d0c17331c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCCC},
                "location":{
                  "x":12,
                  "y":343},
                "size":{
                  "width":908,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/循环盘点/u97.png"}},
{
          "id":"21ff179c87a148c69fba07d514344a22",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCCC},
            "location":{
              "x":330,
              "y":83},
            "size":{
              "width":40,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6522a17f8e044bb185ad2d2840ddf23f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCCC},
                "location":{
                  "x":330,
                  "y":83},
                "size":{
                  "width":40,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/异动盘点/u99.png"}},
{
          "id":"53106b54ab6041618d704855ba9f4806",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":403,
              "y":87},
            "size":{
              "width":75,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac35fed30d434424ba93aa11ca1f7eda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":403,
                  "y":87},
                "size":{
                  "width":75,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c98114bc61d4f20ae737bf01520843d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":464,
              "y":82},
            "size":{
              "width":140,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7b7c8d0cd672464d9c89a2c05633511e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":638,
              "y":82},
            "size":{
              "width":140,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4cb3becd356d4050984efd7701aef67b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":614,
              "y":84},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f56cc63d2934146b737fb8dd24e0f68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":614,
                  "y":84},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1c7931aa6c404b8a8bfbf12be1fb8f5f":{
      "scriptId":"u0"},
    "3e792dbaf2d44c33874903e38a0398f3":{
      "scriptId":"u1"},
    "ae2af5a390254b0caafcd9090efd8a19":{
      "scriptId":"u2"},
    "745aeb2503e1441d98b02f2c6141a60f":{
      "scriptId":"u3"},
    "7db4b3e4961043f084cdfc8c527e7217":{
      "scriptId":"u4"},
    "5866d2ab9adc4c60ba14dc82324464b4":{
      "scriptId":"u5"},
    "dc3df445ae94434f9c4e9cc091de3d2d":{
      "scriptId":"u6"},
    "3d1144b019d9490bad1c1f88571b35d8":{
      "scriptId":"u7"},
    "28d8417e2c044c8f9a5bcbe7f085e3ba":{
      "scriptId":"u8"},
    "1cfdc693cbf34a7f90e03726a6ca2755":{
      "scriptId":"u9"},
    "2dcc18ecc0ef48d1908486fb6f335d05":{
      "scriptId":"u10"},
    "2b2a265f858844dc9265b2cbd7329e9a":{
      "scriptId":"u11"},
    "fba2a1e2ed384b4b8d0cb4430e1b90fd":{
      "scriptId":"u12"},
    "4723d0ccf01b43b8bbda2702d8e1ca4a":{
      "scriptId":"u13"},
    "60dc037c66bf4b03a8fd4871528e747b":{
      "scriptId":"u14"},
    "20b31a62688a4173a921e3cafe89fb1d":{
      "scriptId":"u15"},
    "51a70d2b4e5347b09d936bdd277f30d8":{
      "scriptId":"u16"},
    "19d34de9e73a48879b17f734e38c3024":{
      "scriptId":"u17"},
    "8643a2dfd2cc4fd7877e72d91935fdf0":{
      "scriptId":"u18"},
    "9a4aacc4e87544d18a40b5ca2c63c907":{
      "scriptId":"u19"},
    "7712e9c109884f35a356800b7707ab08":{
      "scriptId":"u20"},
    "c38b014b46414a358ad289a5ef80ca2a":{
      "scriptId":"u21"},
    "e0f26d87dadd4c9080405f5a4bb19192":{
      "scriptId":"u22"},
    "6a0680a029fd4905a2045b4eceadf9c4":{
      "scriptId":"u23"},
    "22bb31a4d52f4af098081cbd90b2a02d":{
      "scriptId":"u24"},
    "c2d021ad3acf436d963a49d3156f7a51":{
      "scriptId":"u25"},
    "dcaedcfe59594dfbb4303ceb5697b829":{
      "scriptId":"u26"},
    "3c4bc449a32844dea9efb815a476a1c2":{
      "scriptId":"u27"},
    "af7d473edea34ff79622ecec51e70c74":{
      "scriptId":"u28"},
    "df99d60d3669494bae1a7559a57f6ce7":{
      "scriptId":"u29"},
    "6aad86bf84d342fdbe14c829873646a8":{
      "scriptId":"u30"},
    "5877807df30a4960a5ac95e8cb6221a6":{
      "scriptId":"u31"},
    "8ec8612c63204f0fba5e4faf2534b27c":{
      "scriptId":"u32"},
    "03e00899caae479cb67ad754c9bc10ab":{
      "scriptId":"u33"},
    "244a999701fb4afa839e8b3cd25d3112":{
      "scriptId":"u34"},
    "0abd05fe4dc1465aa23c46a03abb976c":{
      "scriptId":"u35"},
    "40f2faf8730240e499db47aeb870bb0a":{
      "scriptId":"u36"},
    "077b195e769a48cbb5ebf83f7e53004f":{
      "scriptId":"u37"},
    "9efe8d7617124eeeafcb7ce103fb6e7c":{
      "scriptId":"u38"},
    "de03bd51e33343398e4b1e09276e9ced":{
      "scriptId":"u39"},
    "e0178647a6f44fbaa3e968fc30adfb17":{
      "scriptId":"u40"},
    "c1fbd8cb468b4bc4998b5794e53c8309":{
      "scriptId":"u41"},
    "0fe1bce0c128409e8e8b0c38a939049d":{
      "scriptId":"u42"},
    "72df29e652c1400898ca36ba915f9d7d":{
      "scriptId":"u43"},
    "260c99e2507d4665b5082d4679fc76da":{
      "scriptId":"u44"},
    "93cda2282aff4a6cbc6b9dc7722f0da2":{
      "scriptId":"u45"},
    "7415ad55913f4bf5bb80645ec80c3585":{
      "scriptId":"u46"},
    "193fef181b5649aeb17dae10ef125ac1":{
      "scriptId":"u47"},
    "2beefcfaad5e4bf3b73eb251ca5d3fe7":{
      "scriptId":"u48"},
    "43a531a5bc9d4133b12458137c4e38b9":{
      "scriptId":"u49"},
    "2a6531c6d8a24c4ba415051c84a79cbf":{
      "scriptId":"u50"},
    "e396a753d7534ae686a749e2f8ae0307":{
      "scriptId":"u51"},
    "409f4789e0c042a0a6628776b86d3950":{
      "scriptId":"u52"},
    "86953f96f6b24d2487f1a5af6421e37f":{
      "scriptId":"u53"},
    "46d8ec39aebe45fa8bc51776a6476d05":{
      "scriptId":"u54"},
    "ee5be5b80b4e484d852eea2324440806":{
      "scriptId":"u55"},
    "f1ea68e6a4f44e408a2bdf7ef1e2c7b2":{
      "scriptId":"u56"},
    "5bd0f9dfd6e74024bd6013c693916dcf":{
      "scriptId":"u57"},
    "b5e4aac39adc42b2a1f71148d0b5ed95":{
      "scriptId":"u58"},
    "aac3f159e6be4a5a9ed7c439a27f062e":{
      "scriptId":"u59"},
    "37897f63898c4b8991bfa650ad747314":{
      "scriptId":"u60"},
    "62de23de404c42e1bd2f1adf4610f49f":{
      "scriptId":"u61"},
    "59afca97ff114d0cb27427d567065356":{
      "scriptId":"u62"},
    "25ba0dae18d94453bf0725e6e8b5d0b5":{
      "scriptId":"u63"},
    "c2a0fcf142c442e38205d460646294a5":{
      "scriptId":"u64"},
    "da332974bf81410c8ad030448993369e":{
      "scriptId":"u65"},
    "785e05f8e9d342d2b95684cad3ec2451":{
      "scriptId":"u66"},
    "77c28277855d41e4ad30dc6988776110":{
      "scriptId":"u67"},
    "7d237efd4a14418a9525885f2b8994be":{
      "scriptId":"u68"},
    "3eed471c397c4e1088415a79349ba4e8":{
      "scriptId":"u69"},
    "60d54b5bf35b4f05a133339e1a6a5c62":{
      "scriptId":"u70"},
    "95f2977911b04a5bab23d2208f1b9c19":{
      "scriptId":"u71"},
    "d97a321cc8e544fd84f2c2ec87d7548b":{
      "scriptId":"u72"},
    "9623ff45023f413e84eee666e3b13c05":{
      "scriptId":"u73"},
    "8b886311eb19498aa31ac7b603ee8d62":{
      "scriptId":"u74"},
    "a5adadceac3247d8b7ba3a548a8e15e6":{
      "scriptId":"u75"},
    "90f5a3ea0c604d19b7e0159e80d61ef6":{
      "scriptId":"u76"},
    "277560e0cbe64ff7a59fcf8ba95fcb9c":{
      "scriptId":"u77"},
    "0a67cb429fac4423bf623f92da28dc88":{
      "scriptId":"u78"},
    "1e4f2ee29fde4d9fb27f9bcffda6a829":{
      "scriptId":"u79"},
    "71b950dc7b4246dc9797726b2e0461de":{
      "scriptId":"u80"},
    "f991cc41b661422c8741b564a1c3d535":{
      "scriptId":"u81"},
    "16571abecd3a47d3be3b824c7d22cdba":{
      "scriptId":"u82"},
    "684e623b983648d9b051427aeabdfe32":{
      "scriptId":"u83"},
    "fb2c5d11a3724b82939ed2cb9ef78926":{
      "scriptId":"u84"},
    "d880ac75560f47ae918408397f10339b":{
      "scriptId":"u85"},
    "d304327aeaf24189b5b774e62070d271":{
      "scriptId":"u86"},
    "b45d12e683a44a4b91ac31a95a5e28c9":{
      "scriptId":"u87"},
    "8faff5cb14b64c778df480c462b2d816":{
      "scriptId":"u88"},
    "04a861a2e26f4a568bf75d0002c0389b":{
      "scriptId":"u89"},
    "418f28848c2e45759a5aa7dc5f2fe9d8":{
      "scriptId":"u90"},
    "c98b1a39fa3c489894a7039bbf324273":{
      "scriptId":"u91"},
    "25f1010cf3a345bca42c161fc0b24d25":{
      "scriptId":"u92"},
    "9cee7e56965f4d9cbfbb944e1f825f63":{
      "scriptId":"u93"},
    "02eac410bbcc4d19874a037c0e92365c":{
      "scriptId":"u94"},
    "096e37de312b48b488efa84552b66adb":{
      "scriptId":"u95"},
    "63828578dd644efc80235c5d47d3a6cf":{
      "scriptId":"u96"},
    "ce84ce648fa44d91963750790e160e4f":{
      "scriptId":"u97"},
    "795a71504b904c508da5e99d0c17331c":{
      "scriptId":"u98"},
    "21ff179c87a148c69fba07d514344a22":{
      "scriptId":"u99"},
    "6522a17f8e044bb185ad2d2840ddf23f":{
      "scriptId":"u100"},
    "53106b54ab6041618d704855ba9f4806":{
      "scriptId":"u101"},
    "ac35fed30d434424ba93aa11ca1f7eda":{
      "scriptId":"u102"},
    "6c98114bc61d4f20ae737bf01520843d":{
      "scriptId":"u103"},
    "7b7c8d0cd672464d9c89a2c05633511e":{
      "scriptId":"u104"},
    "4cb3becd356d4050984efd7701aef67b":{
      "scriptId":"u105"},
    "6f56cc63d2934146b737fb8dd24e0f68":{
      "scriptId":"u106"}}});