$axure.loadCurrentPage({
  "url":"套板策略.html",
  "generationDate":new Date(1554888122683.12),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"bd46cbb105ec41c6bb4b96f2d5e0d682",
    "type":"Axure:Page",
    "name":"套板策略",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"200af035595440ff9052ff699c4f54f3",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":58},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"75f69f33de09482395d4ec452f642d85",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":17,
              "y":19},
            "size":{
              "width":950,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2f6720b741b494dac257fc83ef9315c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":17,
                  "y":19},
                "size":{
                  "width":950,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库信息/u144.png"}},
{
          "id":"4047d83e0c304f7885d58f5c656ee846",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":23,
              "y":24},
            "size":{
              "width":122,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0dc822c1765d4eb3b1f5af70a5362974",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":23,
                  "y":24},
                "size":{
                  "width":122,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"beb3c2d7dd3e4b1eacd1cff293dd0059",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":128,
              "y":26},
            "size":{
              "width":62,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f23a892f79a14ca1967ee791e3352339",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":128,
                  "y":26},
                "size":{
                  "width":62,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6efcd5845faf467aa1feec5dbedd9899",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":190,
              "y":26},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e54d61e8ad724b6e8ff53b2f65b5375e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":26},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2766b5dca1034a6185dbfabedc9c3cb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":304,
              "y":26},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"714f9751a64c4d76aa3ef9e2170eec99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":304,
                  "y":26},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f96472e2d61b4087b9a6f7dae4b74668",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":420,
              "y":26},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab0b085de1be4d0192a1cecfe6c7cc11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":420,
                  "y":26},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"875f69072b094e73bbee1e6a838a2474",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":530,
              "y":26},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7b36c433c8142caa354bc2c903771c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":530,
                  "y":26},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"87f0f67d58c44ec4be1e9f08afe6baf1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":641,
              "y":26},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5c33774985341b69260d12e1f2a1f93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":641,
                  "y":26},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"87f676c0f0c448818604c61ef28f2a60",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":739,
              "y":26},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d85a27cd3ad345a8bd58ea9e6ecd17e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":739,
                  "y":26},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca3f8610a4444d299785e9da9c43538d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":833,
              "y":26},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"371b56dba37c4d8aadb7023fa4223835",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":833,
                  "y":26},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a07b48755e294d4fafcede8241b39deb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":22,
              "y":470},
            "size":{
              "width":957,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28cd760166eb4bdc8e196a68322d2b25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":22,
                  "y":470},
                "size":{
                  "width":957,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库信息/u164.png"}},
{
          "id":"d8ad6d75eaab40e7afbafe78452902d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":836,
              "y":476},
            "size":{
              "width":134,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63014765fce146cf9536465a8a1a2495",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":836,
                  "y":476},
                "size":{
                  "width":134,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e9b116cedae646a7b2dca90443364c5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":94},
            "size":{
              "width":123,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb551db3be0743a0a71a1847e856ad88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":94},
                "size":{
                  "width":123,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad66ee14c73a40b8916efca1a8a8c623",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":21,
              "y":130},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1d3399e967841278fd4da048ef15940",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":21,
                  "y":130},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"0b364af1559d4fdf9bbc7af2720d3846",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":21,
              "y":155},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc7349184cfc431790defa92fe3addf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":21,
                  "y":155},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"7bcd0385a8014508b0510e85ffcecbd9",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":21,
              "y":180},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f51bce2388e43faa87f19a609413780",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":21,
                  "y":180},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"d9f2c2f7252d44dca4d17f1b5238587a",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":21,
              "y":205},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68b80ef8544644e189c6dc4db4a0f6d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":21,
                  "y":205},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"b8d27eee5e5a4148a0ac7e80ac1d0a16",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":21,
              "y":243},
            "size":{
              "width":123,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d53fa9cca10245de87e83ce4499937ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":21,
                  "y":243},
                "size":{
                  "width":123,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a21565cb268c463a9bcfee66e7a9503e",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":279},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66b38c4b0ef94ed5a04e341761f9d920",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":22,
                  "y":279},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"e0e1bb1da6bb4ba4b1da2ade80e77754",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":304},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"994df3dbec734984a1c09b7a1f214aee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":22,
                  "y":304},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"7b0a6ae247dd4c4e969beb4a2337f628",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":329},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fef467d328244aea4cf0f29dc604edc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":22,
                  "y":329},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"1bc87c7592714239bdab82ab82828b01",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":391},
            "size":{
              "width":128,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d70cc9f4e44f40569ac5f122387ecb16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":22,
                  "y":391},
                "size":{
                  "width":128,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"432070b52b9d4b63b1691bb59c747e1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":425},
            "size":{
              "width":128,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c6b5d9fc69447249460d0109c6f4092",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":22,
                  "y":425},
                "size":{
                  "width":128,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"018e23e211564419852bd63e0a938e0d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":385},
            "size":{
              "width":175,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2728da7c289c4d6eb8b73ecf9422e1a6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":420},
            "size":{
              "width":175,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "200af035595440ff9052ff699c4f54f3":{
      "scriptId":"u0"},
    "75f69f33de09482395d4ec452f642d85":{
      "scriptId":"u1"},
    "a2f6720b741b494dac257fc83ef9315c":{
      "scriptId":"u2"},
    "4047d83e0c304f7885d58f5c656ee846":{
      "scriptId":"u3"},
    "0dc822c1765d4eb3b1f5af70a5362974":{
      "scriptId":"u4"},
    "beb3c2d7dd3e4b1eacd1cff293dd0059":{
      "scriptId":"u5"},
    "f23a892f79a14ca1967ee791e3352339":{
      "scriptId":"u6"},
    "6efcd5845faf467aa1feec5dbedd9899":{
      "scriptId":"u7"},
    "e54d61e8ad724b6e8ff53b2f65b5375e":{
      "scriptId":"u8"},
    "2766b5dca1034a6185dbfabedc9c3cb7":{
      "scriptId":"u9"},
    "714f9751a64c4d76aa3ef9e2170eec99":{
      "scriptId":"u10"},
    "f96472e2d61b4087b9a6f7dae4b74668":{
      "scriptId":"u11"},
    "ab0b085de1be4d0192a1cecfe6c7cc11":{
      "scriptId":"u12"},
    "875f69072b094e73bbee1e6a838a2474":{
      "scriptId":"u13"},
    "c7b36c433c8142caa354bc2c903771c1":{
      "scriptId":"u14"},
    "87f0f67d58c44ec4be1e9f08afe6baf1":{
      "scriptId":"u15"},
    "e5c33774985341b69260d12e1f2a1f93":{
      "scriptId":"u16"},
    "87f676c0f0c448818604c61ef28f2a60":{
      "scriptId":"u17"},
    "d85a27cd3ad345a8bd58ea9e6ecd17e0":{
      "scriptId":"u18"},
    "ca3f8610a4444d299785e9da9c43538d":{
      "scriptId":"u19"},
    "371b56dba37c4d8aadb7023fa4223835":{
      "scriptId":"u20"},
    "a07b48755e294d4fafcede8241b39deb":{
      "scriptId":"u21"},
    "28cd760166eb4bdc8e196a68322d2b25":{
      "scriptId":"u22"},
    "d8ad6d75eaab40e7afbafe78452902d5":{
      "scriptId":"u23"},
    "63014765fce146cf9536465a8a1a2495":{
      "scriptId":"u24"},
    "e9b116cedae646a7b2dca90443364c5f":{
      "scriptId":"u25"},
    "fb551db3be0743a0a71a1847e856ad88":{
      "scriptId":"u26"},
    "ad66ee14c73a40b8916efca1a8a8c623":{
      "scriptId":"u27"},
    "d1d3399e967841278fd4da048ef15940":{
      "scriptId":"u28"},
    "0b364af1559d4fdf9bbc7af2720d3846":{
      "scriptId":"u29"},
    "fc7349184cfc431790defa92fe3addf8":{
      "scriptId":"u30"},
    "7bcd0385a8014508b0510e85ffcecbd9":{
      "scriptId":"u31"},
    "7f51bce2388e43faa87f19a609413780":{
      "scriptId":"u32"},
    "d9f2c2f7252d44dca4d17f1b5238587a":{
      "scriptId":"u33"},
    "68b80ef8544644e189c6dc4db4a0f6d4":{
      "scriptId":"u34"},
    "b8d27eee5e5a4148a0ac7e80ac1d0a16":{
      "scriptId":"u35"},
    "d53fa9cca10245de87e83ce4499937ec":{
      "scriptId":"u36"},
    "a21565cb268c463a9bcfee66e7a9503e":{
      "scriptId":"u37"},
    "66b38c4b0ef94ed5a04e341761f9d920":{
      "scriptId":"u38"},
    "e0e1bb1da6bb4ba4b1da2ade80e77754":{
      "scriptId":"u39"},
    "994df3dbec734984a1c09b7a1f214aee":{
      "scriptId":"u40"},
    "7b0a6ae247dd4c4e969beb4a2337f628":{
      "scriptId":"u41"},
    "0fef467d328244aea4cf0f29dc604edc":{
      "scriptId":"u42"},
    "1bc87c7592714239bdab82ab82828b01":{
      "scriptId":"u43"},
    "d70cc9f4e44f40569ac5f122387ecb16":{
      "scriptId":"u44"},
    "432070b52b9d4b63b1691bb59c747e1e":{
      "scriptId":"u45"},
    "1c6b5d9fc69447249460d0109c6f4092":{
      "scriptId":"u46"},
    "018e23e211564419852bd63e0a938e0d":{
      "scriptId":"u47"},
    "2728da7c289c4d6eb8b73ecf9422e1a6":{
      "scriptId":"u48"}}});