$axure.loadCurrentPage({
  "url":"盘点策略.html",
  "generationDate":new Date(1554888123000.27),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"3f8e5c896d5946ed95c626d398315364",
    "type":"Axure:Page",
    "name":"盘点策略",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5a3dbbd9d1124c2592ea8a5f8fd5eed1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":0,
              "y":2},
            "size":{
              "width":950,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0dced355358645f59557f80cef5d56dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":0,
                  "y":2},
                "size":{
                  "width":950,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库信息/u144.png"}},
{
          "id":"71b12261498d4c4e93d671b5524959da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":6,
              "y":7},
            "size":{
              "width":122,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a7a0398d9f14ad0945be86c4ebbecb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":6,
                  "y":7},
                "size":{
                  "width":122,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d961eb4665214e9e92aad5211687ab70",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":111,
              "y":9},
            "size":{
              "width":62,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fc0e4b98b1d48f08eb777ede39b3b89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":111,
                  "y":9},
                "size":{
                  "width":62,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5d1365b8c2a4e5bb909f041fb42697b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":173,
              "y":9},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a91e183744345bdaf81815bf3f05467",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":173,
                  "y":9},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"91b1201a75b549c1a4dd3363ec376fb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":287,
              "y":9},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20f6a265fbdb4ff69c639c2a415ee716",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":287,
                  "y":9},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80df999cc39d435eae222c02acd87509",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":403,
              "y":9},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9ce90df1ab44d6fb5bd36baf1d710ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":403,
                  "y":9},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe8a9092c99c4f3d90eed6e0e44fc5a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":513,
              "y":9},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4b8d16a5ec94d5991bc25bc1501b91b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":513,
                  "y":9},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b89811792c0141a68e86ca494bddefa2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":624,
              "y":9},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ad935de15c54dc884ad166f86d0d2f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":624,
                  "y":9},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"248ccfbdb87c430fb623ad0590b41a8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":722,
              "y":9},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f397bc280c54d389431d0e1ee1ebd53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":722,
                  "y":9},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"501d35686bfc46d39238ddc61cbcd456",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":816,
              "y":9},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7bd55033c64426b9903ead58dedae41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":816,
                  "y":9},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1de8e572e8944872b7bbcaea54ffeb6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":1,
              "y":453},
            "size":{
              "width":949,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0fac3302de841b8966e734d16b04a10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":1,
                  "y":453},
                "size":{
                  "width":949,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/盘点策略/u20.png"}},
{
          "id":"003a91eb31ff4139b2ad33ec13f1743b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":808,
              "y":459},
            "size":{
              "width":133,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f77448bd9f543ecacb58b10043fd910",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":808,
                  "y":459},
                "size":{
                  "width":133,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe74d493eb9f4a67bee22120629a2728",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":244,
              "y":60},
            "size":{
              "width":130,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a5e8e92c06f40aaa6af11235af07616",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":244,
                  "y":60},
                "size":{
                  "width":130,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9d3ce22717947c29ec97356b16837a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":715,
              "y":60},
            "size":{
              "width":103,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a15941a4aa564830ad5ed141d4327f10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":715,
                  "y":60},
                "size":{
                  "width":103,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac5dc1bf912f4eb09ff175671237e514",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":478,
              "y":60},
            "size":{
              "width":98,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36a99fcb650a4e82953ee0e3e9e73279",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":478,
                  "y":60},
                "size":{
                  "width":98,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bed53dab2d574f60aa0269c84a168795",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":9,
              "y":60},
            "size":{
              "width":130,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec685e5b6aba428f8cd2d25ad161fc3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":9,
                  "y":60},
                "size":{
                  "width":130,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c4f7b0e56cf4931ab3b0c14921be360",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCCC},
            "location":{
              "x":4,
              "y":85},
            "size":{
              "width":224,
              "height":185}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec8e94da5b484fd98b2adb3d9a6b5067",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCCC},
                "location":{
                  "x":4,
                  "y":85},
                "size":{
                  "width":224,
                  "height":185}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/盘点策略/u32.png"}},
{
          "id":"fbdc5c095742479ca60682ea836123ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCCC},
            "location":{
              "x":237,
              "y":85},
            "size":{
              "width":221,
              "height":185}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f5f94ab690244d5a6136dc63c02fcd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCCC},
                "location":{
                  "x":237,
                  "y":85},
                "size":{
                  "width":221,
                  "height":185}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/盘点策略/u34.png"}},
{
          "id":"beacf1a573b64afba67632257fc55a29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCCC},
            "location":{
              "x":466,
              "y":85},
            "size":{
              "width":241,
              "height":185}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18ae4b8065954fdfac2347417f61a29f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCCC},
                "location":{
                  "x":466,
                  "y":85},
                "size":{
                  "width":241,
                  "height":185}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/盘点策略/u36.png"}},
{
          "id":"ab1bab18b74c40c792184a9725b70d93",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCCC},
            "location":{
              "x":716,
              "y":85},
            "size":{
              "width":234,
              "height":185}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af1795a5e94d472b868f1da4dcaedfe3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCCC},
                "location":{
                  "x":716,
                  "y":85},
                "size":{
                  "width":234,
                  "height":185}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/盘点策略/u38.png"}},
{
          "id":"f7c99081156e42d89a3ff3e7eef2f917",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCCC},
            "location":{
              "x":6,
              "y":276},
            "size":{
              "width":944,
              "height":167}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea0bb901f27e49f7b09ac7efd5d40c76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCCC},
                "location":{
                  "x":6,
                  "y":276},
                "size":{
                  "width":944,
                  "height":167}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/盘点策略/u40.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "5a3dbbd9d1124c2592ea8a5f8fd5eed1":{
      "scriptId":"u0"},
    "0dced355358645f59557f80cef5d56dd":{
      "scriptId":"u1"},
    "71b12261498d4c4e93d671b5524959da":{
      "scriptId":"u2"},
    "3a7a0398d9f14ad0945be86c4ebbecb8":{
      "scriptId":"u3"},
    "d961eb4665214e9e92aad5211687ab70":{
      "scriptId":"u4"},
    "1fc0e4b98b1d48f08eb777ede39b3b89":{
      "scriptId":"u5"},
    "d5d1365b8c2a4e5bb909f041fb42697b":{
      "scriptId":"u6"},
    "7a91e183744345bdaf81815bf3f05467":{
      "scriptId":"u7"},
    "91b1201a75b549c1a4dd3363ec376fb7":{
      "scriptId":"u8"},
    "20f6a265fbdb4ff69c639c2a415ee716":{
      "scriptId":"u9"},
    "80df999cc39d435eae222c02acd87509":{
      "scriptId":"u10"},
    "a9ce90df1ab44d6fb5bd36baf1d710ba":{
      "scriptId":"u11"},
    "fe8a9092c99c4f3d90eed6e0e44fc5a0":{
      "scriptId":"u12"},
    "c4b8d16a5ec94d5991bc25bc1501b91b":{
      "scriptId":"u13"},
    "b89811792c0141a68e86ca494bddefa2":{
      "scriptId":"u14"},
    "0ad935de15c54dc884ad166f86d0d2f1":{
      "scriptId":"u15"},
    "248ccfbdb87c430fb623ad0590b41a8e":{
      "scriptId":"u16"},
    "7f397bc280c54d389431d0e1ee1ebd53":{
      "scriptId":"u17"},
    "501d35686bfc46d39238ddc61cbcd456":{
      "scriptId":"u18"},
    "f7bd55033c64426b9903ead58dedae41":{
      "scriptId":"u19"},
    "1de8e572e8944872b7bbcaea54ffeb6e":{
      "scriptId":"u20"},
    "d0fac3302de841b8966e734d16b04a10":{
      "scriptId":"u21"},
    "003a91eb31ff4139b2ad33ec13f1743b":{
      "scriptId":"u22"},
    "6f77448bd9f543ecacb58b10043fd910":{
      "scriptId":"u23"},
    "fe74d493eb9f4a67bee22120629a2728":{
      "scriptId":"u24"},
    "2a5e8e92c06f40aaa6af11235af07616":{
      "scriptId":"u25"},
    "d9d3ce22717947c29ec97356b16837a2":{
      "scriptId":"u26"},
    "a15941a4aa564830ad5ed141d4327f10":{
      "scriptId":"u27"},
    "ac5dc1bf912f4eb09ff175671237e514":{
      "scriptId":"u28"},
    "36a99fcb650a4e82953ee0e3e9e73279":{
      "scriptId":"u29"},
    "bed53dab2d574f60aa0269c84a168795":{
      "scriptId":"u30"},
    "ec685e5b6aba428f8cd2d25ad161fc3e":{
      "scriptId":"u31"},
    "1c4f7b0e56cf4931ab3b0c14921be360":{
      "scriptId":"u32"},
    "ec8e94da5b484fd98b2adb3d9a6b5067":{
      "scriptId":"u33"},
    "fbdc5c095742479ca60682ea836123ba":{
      "scriptId":"u34"},
    "9f5f94ab690244d5a6136dc63c02fcd1":{
      "scriptId":"u35"},
    "beacf1a573b64afba67632257fc55a29":{
      "scriptId":"u36"},
    "18ae4b8065954fdfac2347417f61a29f":{
      "scriptId":"u37"},
    "ab1bab18b74c40c792184a9725b70d93":{
      "scriptId":"u38"},
    "af1795a5e94d472b868f1da4dcaedfe3":{
      "scriptId":"u39"},
    "f7c99081156e42d89a3ff3e7eef2f917":{
      "scriptId":"u40"},
    "ea0bb901f27e49f7b09ac7efd5d40c76":{
      "scriptId":"u41"}}});