$axure.loadCurrentPage({
  "url":"添加asn.html",
  "generationDate":new Date(1554888123581.72),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"d6ec5db027974f808f942a85791b5422",
    "type":"Axure:Page",
    "name":"添加ASN",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"45e9bfd390444a849bb77e38a97e7699",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "size":{
              "width":950,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55ec1f7d54a440538f146cf82704676a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "size":{
                  "width":950,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库信息/u144.png"}},
{
          "id":"e8324ce28e764c50b4df56185acd3df1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":6,
              "y":5},
            "size":{
              "width":122,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4215995b1ea44006b3bcb55c4dbe198c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":6,
                  "y":5},
                "size":{
                  "width":122,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f25dc7b322c74075926025d4a117eaa9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":111,
              "y":7},
            "size":{
              "width":62,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a40d29ba168a459fb0b38891f07c4214",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":111,
                  "y":7},
                "size":{
                  "width":62,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d3056016d5f4f27935d535063d60e6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":173,
              "y":7},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47c7c8ce704443eeb21b696285b2cfe3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":173,
                  "y":7},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d629f4fead4f4cf39f354c71232e4337",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":287,
              "y":7},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9801cc426ad428aaa774ad616e6e0ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":287,
                  "y":7},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3b0f3c9ffd54404a278a7af027d9e70",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":403,
              "y":7},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5960a1e79abe46afaa27a7454f9215a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":403,
                  "y":7},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d584910b9d584f06bc3399655f7c782a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":513,
              "y":7},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"275a3d85c8e14513ab67590dc958cd38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":513,
                  "y":7},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d3c35caaae04105a953a6f77081864d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":624,
              "y":7},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee6159fb62c14f3e9a3aa0f031afc01f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":624,
                  "y":7},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e69963fb941d4790a5d670c1a8c4d471",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":722,
              "y":7},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b1370262ac14bbfb8fb8588d25518dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":722,
                  "y":7},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d60b52c93ec414eba8367ea84a2b1ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":816,
              "y":7},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7db266520094aeeb823efdf76d59fcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":816,
                  "y":7},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a8382da468ff474fa5dc977813abbb0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":5,
              "y":451},
            "size":{
              "width":957,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f568d2d043524ae8b33a82b52f9bf323",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":5,
                  "y":451},
                "size":{
                  "width":957,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库信息/u164.png"}},
{
          "id":"d5219e7bb5e140a3ae13d68b8449bdd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":819,
              "y":457},
            "size":{
              "width":134,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e82d7fd2c608439cac51006f295716bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":819,
                  "y":457},
                "size":{
                  "width":134,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c43455f0ea6e41dd8eaf524649136f9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3300FF,
              "opacity":1},
            "location":{
              "x":6,
              "y":90},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ab8cdf05103493fbb2a36b2031530ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3300FF,
                  "opacity":1},
                "location":{
                  "x":6,
                  "y":90},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20a65b730ffa4f3a86ffcd1524c382f5",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":76,
              "y":85},
            "size":{
              "width":104,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2f073a329da745d3b49e512546791f34",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3300FF,
              "opacity":1},
            "location":{
              "x":196,
              "y":88},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1bd5e847144469e930dd257ca268038",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3300FF,
                  "opacity":1},
                "location":{
                  "x":196,
                  "y":88},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33cfc37891714d829b3cb66159e2c612",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":85},
            "size":{
              "width":73,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b5e05a6894044ebbbd4d487c494db5aa",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":40},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a61ed44b58ed4c32bc04fc73c9a1888d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":40},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"closeCurrent",
                      "description":"关闭当前窗口"}]}]}},
          "tabbable":true},
{
          "id":"cf06ad0d87d047beb28651f8a5f056e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":131},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"667cf9d1ea644e048cdbb714d1f366f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":131},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"046cf7a72df1456ab2dfae514282e1e7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":76,
              "y":131},
            "size":{
              "width":527,
              "height":95}},
          "adaptiveStyles":{
}},
{
          "id":"b352d1f3ac194c18812b08c9ca262d4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":537,
              "y":90},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08b494d6b5d142e39b374e3ab9078811",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":537,
                  "y":90},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"075e32c86133476ca47b02f0064de9c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3300FF,
              "opacity":1},
            "location":{
              "x":347,
              "y":90},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00cf0586a72d4a809b18ca3d2959e2e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3300FF,
                  "opacity":1},
                "location":{
                  "x":347,
                  "y":90},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"763869b40bd84371a1408744a58e4004",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":417,
              "y":85},
            "size":{
              "width":87,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f0871b14f6024155b0659a26868908ed",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":612,
              "y":86},
            "size":{
              "width":108,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"bd6a92f946c044c5840255caa78a3649",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9999},
            "location":{
              "x":601,
              "y":161},
            "size":{
              "width":159,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04e6fdb34740465c9df1bb1d4c3227ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9999},
                "location":{
                  "x":601,
                  "y":161},
                "size":{
                  "width":159,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加asn/u41.png"}},
{
          "id":"eda9a7d979c449c0a26b3455e2be14a6",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":161},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd999b929327464cac0a938076945bb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":161},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}]},
{
          "id":"0294166073634584a70df93ff2665c20",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":737,
              "y":89},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1d4fb027f4f4823aa1efcf37a8fe071",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":737,
                  "y":89},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d0c60bfffbad4d32a0d62896a23cf29c",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":807,
              "y":85},
            "size":{
              "width":123,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ba957661fb4743aaa65b283a82740ba3",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9999},
            "location":{
              "x":771,
              "y":160},
            "size":{
              "width":159,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7abcaee4c93d4d16b9133772db06b298",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9999},
                "location":{
                  "x":771,
                  "y":160},
                "size":{
                  "width":159,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加asn/u41.png"}},
{
          "id":"50553a5ab46847ba9d7b168d67617437",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":850,
              "y":160},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78e818da128542bc99abafe5ca14e825",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":850,
                  "y":160},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "45e9bfd390444a849bb77e38a97e7699":{
      "scriptId":"u0"},
    "55ec1f7d54a440538f146cf82704676a":{
      "scriptId":"u1"},
    "e8324ce28e764c50b4df56185acd3df1":{
      "scriptId":"u2"},
    "4215995b1ea44006b3bcb55c4dbe198c":{
      "scriptId":"u3"},
    "f25dc7b322c74075926025d4a117eaa9":{
      "scriptId":"u4"},
    "a40d29ba168a459fb0b38891f07c4214":{
      "scriptId":"u5"},
    "1d3056016d5f4f27935d535063d60e6a":{
      "scriptId":"u6"},
    "47c7c8ce704443eeb21b696285b2cfe3":{
      "scriptId":"u7"},
    "d629f4fead4f4cf39f354c71232e4337":{
      "scriptId":"u8"},
    "f9801cc426ad428aaa774ad616e6e0ea":{
      "scriptId":"u9"},
    "c3b0f3c9ffd54404a278a7af027d9e70":{
      "scriptId":"u10"},
    "5960a1e79abe46afaa27a7454f9215a3":{
      "scriptId":"u11"},
    "d584910b9d584f06bc3399655f7c782a":{
      "scriptId":"u12"},
    "275a3d85c8e14513ab67590dc958cd38":{
      "scriptId":"u13"},
    "5d3c35caaae04105a953a6f77081864d":{
      "scriptId":"u14"},
    "ee6159fb62c14f3e9a3aa0f031afc01f":{
      "scriptId":"u15"},
    "e69963fb941d4790a5d670c1a8c4d471":{
      "scriptId":"u16"},
    "0b1370262ac14bbfb8fb8588d25518dc":{
      "scriptId":"u17"},
    "7d60b52c93ec414eba8367ea84a2b1ae":{
      "scriptId":"u18"},
    "c7db266520094aeeb823efdf76d59fcb":{
      "scriptId":"u19"},
    "a8382da468ff474fa5dc977813abbb0a":{
      "scriptId":"u20"},
    "f568d2d043524ae8b33a82b52f9bf323":{
      "scriptId":"u21"},
    "d5219e7bb5e140a3ae13d68b8449bdd9":{
      "scriptId":"u22"},
    "e82d7fd2c608439cac51006f295716bf":{
      "scriptId":"u23"},
    "c43455f0ea6e41dd8eaf524649136f9c":{
      "scriptId":"u24"},
    "3ab8cdf05103493fbb2a36b2031530ec":{
      "scriptId":"u25"},
    "20a65b730ffa4f3a86ffcd1524c382f5":{
      "scriptId":"u26"},
    "2f073a329da745d3b49e512546791f34":{
      "scriptId":"u27"},
    "d1bd5e847144469e930dd257ca268038":{
      "scriptId":"u28"},
    "33cfc37891714d829b3cb66159e2c612":{
      "scriptId":"u29"},
    "b5e05a6894044ebbbd4d487c494db5aa":{
      "scriptId":"u30"},
    "a61ed44b58ed4c32bc04fc73c9a1888d":{
      "scriptId":"u31"},
    "cf06ad0d87d047beb28651f8a5f056e8":{
      "scriptId":"u32"},
    "667cf9d1ea644e048cdbb714d1f366f4":{
      "scriptId":"u33"},
    "046cf7a72df1456ab2dfae514282e1e7":{
      "scriptId":"u34"},
    "b352d1f3ac194c18812b08c9ca262d4b":{
      "scriptId":"u35"},
    "08b494d6b5d142e39b374e3ab9078811":{
      "scriptId":"u36"},
    "075e32c86133476ca47b02f0064de9c0":{
      "scriptId":"u37"},
    "00cf0586a72d4a809b18ca3d2959e2e4":{
      "scriptId":"u38"},
    "763869b40bd84371a1408744a58e4004":{
      "scriptId":"u39"},
    "f0871b14f6024155b0659a26868908ed":{
      "scriptId":"u40"},
    "bd6a92f946c044c5840255caa78a3649":{
      "scriptId":"u41"},
    "04e6fdb34740465c9df1bb1d4c3227ae":{
      "scriptId":"u42"},
    "eda9a7d979c449c0a26b3455e2be14a6":{
      "scriptId":"u43"},
    "cd999b929327464cac0a938076945bb3":{
      "scriptId":"u44"},
    "0294166073634584a70df93ff2665c20":{
      "scriptId":"u45"},
    "f1d4fb027f4f4823aa1efcf37a8fe071":{
      "scriptId":"u46"},
    "d0c60bfffbad4d32a0d62896a23cf29c":{
      "scriptId":"u47"},
    "ba957661fb4743aaa65b283a82740ba3":{
      "scriptId":"u48"},
    "7abcaee4c93d4d16b9133772db06b298":{
      "scriptId":"u49"},
    "50553a5ab46847ba9d7b168d67617437":{
      "scriptId":"u50"},
    "78e818da128542bc99abafe5ca14e825":{
      "scriptId":"u51"}}});