$axure.loadCurrentPage({
  "url":"库存监控图表.html",
  "generationDate":new Date(1554888141797.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"a26f292bb8dd4827bf0f6640a548b61e",
    "type":"Axure:Page",
    "name":"库存监控图表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b9e88a6ff4e744c582f504f64061d486",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":1,
              "y":1},
            "size":{
              "width":1189,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27f8cd2a4fb146a390b8fa0090aef207",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":1,
                  "y":1},
                "size":{
                  "width":1189,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/库存监控图表/u0.png"}},
{
          "id":"28ee4f546bc54a19929da2ef183c014b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":9,
              "y":6},
            "size":{
              "width":156,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f53b6f6aa8f49abb94007237854db8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":9,
                  "y":6},
                "size":{
                  "width":156,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d2afe0e1c2b4b80b430664563c0b01b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":143,
              "y":8},
            "size":{
              "width":79,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d91b363cbf344afae90a2a608dd843c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":143,
                  "y":8},
                "size":{
                  "width":79,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d92c9a34e0e4fcf9f91c1d879973981",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":222,
              "y":8},
            "size":{
              "width":105,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3b44680bb1749779ca9d0e8810b2ace",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":222,
                  "y":8},
                "size":{
                  "width":105,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9fee71474d034439ac25027d13986414",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":367,
              "y":8},
            "size":{
              "width":105,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85f336f7a4e14066920d78e6c0e332c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":367,
                  "y":8},
                "size":{
                  "width":105,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06127952e1e740fc92803f0306f80e12",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":516,
              "y":8},
            "size":{
              "width":105,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7172b8389f948b98cf7741b5bc76035",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":516,
                  "y":8},
                "size":{
                  "width":105,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb2541692e0a4896aeb34565c1521c08",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":656,
              "y":8},
            "size":{
              "width":105,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f115e92ab3a34ebc8cf195edd08d138b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":656,
                  "y":8},
                "size":{
                  "width":105,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a49340a247e140b9903b632f587862bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":798,
              "y":8},
            "size":{
              "width":83,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d6ca992db054198bbc168c02fd6df96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":798,
                  "y":8},
                "size":{
                  "width":83,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a97e5286f20543c2bc54ba77bb63dae0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":923,
              "y":8},
            "size":{
              "width":83,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"297f7545974644418cc667f11a33fadf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":923,
                  "y":8},
                "size":{
                  "width":83,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25644d50da82477bbda8318b4f217429",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1043,
              "y":8},
            "size":{
              "width":83,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"733aaee1b9b84a97b098e0092cefca8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1043,
                  "y":8},
                "size":{
                  "width":83,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a10f461c09154f7d9dfc689199f52aa7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":0,
              "y":630},
            "size":{
              "width":1189,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21c4e7924cf84252868ab9613c9dea96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":0,
                  "y":630},
                "size":{
                  "width":1189,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/库存监控图表/u0.png"}},
{
          "id":"518f658f44304c2da7a56b82345c7916",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1011,
              "y":636},
            "size":{
              "width":166,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0bf9ee14b5345adb1744c75906f3f43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1011,
                  "y":636},
                "size":{
                  "width":166,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65c7d380b4c744ea935d9f1063746d97",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":31},
            "size":{
              "width":1190,
              "height":599}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26fb3cc4fc814721992a02da7e486da0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":31},
                "size":{
                  "width":1190,
                  "height":599}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/库存监控图表/u24.png"}},
{
          "id":"2095761278ed4c60ad81969f14797eb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFF00,
              "opacity":1},
            "location":{
              "x":9,
              "y":575},
            "size":{
              "width":190,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80be2e56396c48739347f796f15e904e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF00,
                  "opacity":1},
                "location":{
                  "x":9,
                  "y":575},
                "size":{
                  "width":190,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "b9e88a6ff4e744c582f504f64061d486":{
      "scriptId":"u0"},
    "27f8cd2a4fb146a390b8fa0090aef207":{
      "scriptId":"u1"},
    "28ee4f546bc54a19929da2ef183c014b":{
      "scriptId":"u2"},
    "8f53b6f6aa8f49abb94007237854db8b":{
      "scriptId":"u3"},
    "1d2afe0e1c2b4b80b430664563c0b01b":{
      "scriptId":"u4"},
    "6d91b363cbf344afae90a2a608dd843c":{
      "scriptId":"u5"},
    "4d92c9a34e0e4fcf9f91c1d879973981":{
      "scriptId":"u6"},
    "b3b44680bb1749779ca9d0e8810b2ace":{
      "scriptId":"u7"},
    "9fee71474d034439ac25027d13986414":{
      "scriptId":"u8"},
    "85f336f7a4e14066920d78e6c0e332c6":{
      "scriptId":"u9"},
    "06127952e1e740fc92803f0306f80e12":{
      "scriptId":"u10"},
    "f7172b8389f948b98cf7741b5bc76035":{
      "scriptId":"u11"},
    "fb2541692e0a4896aeb34565c1521c08":{
      "scriptId":"u12"},
    "f115e92ab3a34ebc8cf195edd08d138b":{
      "scriptId":"u13"},
    "a49340a247e140b9903b632f587862bd":{
      "scriptId":"u14"},
    "8d6ca992db054198bbc168c02fd6df96":{
      "scriptId":"u15"},
    "a97e5286f20543c2bc54ba77bb63dae0":{
      "scriptId":"u16"},
    "297f7545974644418cc667f11a33fadf":{
      "scriptId":"u17"},
    "25644d50da82477bbda8318b4f217429":{
      "scriptId":"u18"},
    "733aaee1b9b84a97b098e0092cefca8d":{
      "scriptId":"u19"},
    "a10f461c09154f7d9dfc689199f52aa7":{
      "scriptId":"u20"},
    "21c4e7924cf84252868ab9613c9dea96":{
      "scriptId":"u21"},
    "518f658f44304c2da7a56b82345c7916":{
      "scriptId":"u22"},
    "e0bf9ee14b5345adb1744c75906f3f43":{
      "scriptId":"u23"},
    "65c7d380b4c744ea935d9f1063746d97":{
      "scriptId":"u24"},
    "26fb3cc4fc814721992a02da7e486da0":{
      "scriptId":"u25"},
    "2095761278ed4c60ad81969f14797eb4":{
      "scriptId":"u26"},
    "80be2e56396c48739347f796f15e904e":{
      "scriptId":"u27"}}});