$axure.loadCurrentPage({
  "url":"拣货扫描.html",
  "generationDate":new Date(1554888137656.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"16b4a85cb6e24519b436299bbee11913",
    "type":"Axure:Page",
    "name":"拣货扫描",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0c3c5c9764ba412ea38a0c3a64e217ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "size":{
              "width":305,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"576d160b309148fe96922c374e3da7e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "size":{
                  "width":305,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u6.png"}},
{
          "id":"dc490ce5a67d4750b367cd12a8062cf8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":4,
              "y":5},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e76547e8e91e4ffbad194203ef0e0bdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":4,
                  "y":5},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b8baa88c66c4b69837f1602242cb36b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":136,
              "y":7},
            "size":{
              "width":164,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee72d635f8eb4b8d94d54f8eca1bb735",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":136,
                  "y":7},
                "size":{
                  "width":164,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75b3ccf662524acaac27662915c0e7d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":1,
              "y":451},
            "size":{
              "width":308,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"700daa332a8a4eaca6572e08c214d899",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":1,
                  "y":451},
                "size":{
                  "width":308,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u12.png"}},
{
          "id":"2618489798a243389d61e94c30643ce8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":144,
              "y":457},
            "size":{
              "width":162,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14a93a57c1e643a5bf8961a38bcb0793",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":144,
                  "y":457},
                "size":{
                  "width":162,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b103cd6716d4c7d8cdb4dcf75430dfd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCCC},
            "location":{
              "x":353,
              "y":39},
            "size":{
              "width":347,
              "height":351}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d826a31f90ca47088b1799c8a08d2c92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCCC},
                "location":{
                  "x":353,
                  "y":39},
                "size":{
                  "width":347,
                  "height":351}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拣货扫描/u10.png"}},
{
          "id":"811098d511ad4a40ae74918bfeab7012",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":22,
              "y":52},
            "size":{
              "width":78,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23ab71dd01ad43bebe2d91d9af33f15a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":22,
                  "y":52},
                "size":{
                  "width":78,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ebf27e0f707454f955b47c137de1133",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":112,
              "y":47},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7db2b5041fab4bbbbad8d818968e5bf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":22,
              "y":129},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"885266a8072c4e6692d8dbbf5a8a2326",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":22,
                  "y":129},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5eea6784a724e84a44ae2ae6942393e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":112,
              "y":128},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"35e723463eed440eb933ae934c8ac4cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":22,
              "y":89},
            "size":{
              "width":78,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"408cdeb5272a4ec7a2c76a7f796ccbdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":22,
                  "y":89},
                "size":{
                  "width":78,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6d59c9473fa4fbca971e9a8e9e3337c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":112,
              "y":88},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"03909631d8f842f0bd9f6ee1394fc9b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":22,
              "y":211},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9666263d71b24c7183342aab376183d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":22,
                  "y":211},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4965069be88142ea876d052c2cdbcc04",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":113,
              "y":210},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"677b9938e3554fcc811057c09d62b45f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":22,
              "y":169},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0efb6a53783748069cf12f0a6cbce337",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":22,
                  "y":169},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5fa7bc7518b4586b4e2fa96e918c7f7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":112,
              "y":168},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6e7350ee5aa94b67bd4deb363130cd89",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "verticalAlignment":"bottom",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":21,
              "y":266},
            "size":{
              "width":129,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e01aadc6366e465189c9a82f0d48a096",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "verticalAlignment":"bottom",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":21,
                  "y":266},
                "size":{
                  "width":129,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c1335bf840642719706303747c77e91",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":127,
              "y":265},
            "size":{
              "width":164,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"feafcf11983043e28827a566b9c5369d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "location":{
              "x":240,
              "y":711},
            "size":{
              "width":89,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74583247cbdd4f7b8bfd9e89a9f07c16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "location":{
                  "x":240,
                  "y":711},
                "size":{
                  "width":89,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f56d30963da4d1c97a673b7bb7d1002",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "location":{
              "x":239,
              "y":764},
            "size":{
              "width":80,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79361b5b5a8d4acaa8141e2097e1e646",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "location":{
                  "x":239,
                  "y":764},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f868ca4901340b8847dceff5bfa2138",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":225,
              "y":540},
            "size":{
              "width":305,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c79149e987aa4fe1a695e35113366cb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":225,
                  "y":540},
                "size":{
                  "width":305,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u6.png"}},
{
          "id":"4fae3c1f1ec146d19eb6bc5a40dc174f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":229,
              "y":545},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ed6c9845e6f4d75a74aab57008e4448",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":229,
                  "y":545},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f83b245be284a35b0a1636d2cd6eca4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":359,
              "y":546},
            "size":{
              "width":166,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6413961d3c0424caa95c26593d7a203",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":359,
                  "y":546},
                "size":{
                  "width":166,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23045e5deecb4b0ea41d2399853db17e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":226,
              "y":911},
            "size":{
              "width":305,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9a07b1bc86d4e6ab1902177c9527b5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":226,
                  "y":911},
                "size":{
                  "width":305,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u6.png"}},
{
          "id":"334290c27b1245458c85e8f11b06840c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":368,
              "y":917},
            "size":{
              "width":157,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea0d840ad87d42da9c8486a27d29977a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":368,
                  "y":917},
                "size":{
                  "width":157,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"857fc685c4ec49fdb21503e840a1ef41",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"bottom",
            "location":{
              "x":240,
              "y":820},
            "size":{
              "width":86,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ecf777e04014b9cb3d5ab7331ef6bab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"bottom",
                "location":{
                  "x":240,
                  "y":820},
                "size":{
                  "width":86,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"51bdd8419db245ffa2501185c6eb7e17",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":816},
            "size":{
              "width":190,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"02ee95ce98c642f3b56971157695b0c4",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":866},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"dcef60ca62054b4c8b9b3d4819023e8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "location":{
              "x":240,
              "y":601},
            "size":{
              "width":69,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd6ffb9bf7c341c3952c10d2b729df6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "location":{
                  "x":240,
                  "y":601},
                "size":{
                  "width":69,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb85b773b1cc43fbb73777393b7e4df6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "location":{
              "x":240,
              "y":655},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7673adca1f4740dbb765944d9f22a6dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "location":{
                  "x":240,
                  "y":655},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"548cc89146d54992b279b1d97acac622",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":329,
              "y":652},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d4b4a1f6729a40d784606c7fab8340eb",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":329,
              "y":599},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"92203087f72c4e308820a4ef04c98079",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":329,
              "y":762},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c75f7bb917424b47ac5f10a6c76665b9",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":329,
              "y":709},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "0c3c5c9764ba412ea38a0c3a64e217ae":{
      "scriptId":"u0"},
    "576d160b309148fe96922c374e3da7e1":{
      "scriptId":"u1"},
    "dc490ce5a67d4750b367cd12a8062cf8":{
      "scriptId":"u2"},
    "e76547e8e91e4ffbad194203ef0e0bdd":{
      "scriptId":"u3"},
    "8b8baa88c66c4b69837f1602242cb36b":{
      "scriptId":"u4"},
    "ee72d635f8eb4b8d94d54f8eca1bb735":{
      "scriptId":"u5"},
    "75b3ccf662524acaac27662915c0e7d9":{
      "scriptId":"u6"},
    "700daa332a8a4eaca6572e08c214d899":{
      "scriptId":"u7"},
    "2618489798a243389d61e94c30643ce8":{
      "scriptId":"u8"},
    "14a93a57c1e643a5bf8961a38bcb0793":{
      "scriptId":"u9"},
    "7b103cd6716d4c7d8cdb4dcf75430dfd":{
      "scriptId":"u10"},
    "d826a31f90ca47088b1799c8a08d2c92":{
      "scriptId":"u11"},
    "811098d511ad4a40ae74918bfeab7012":{
      "scriptId":"u12"},
    "23ab71dd01ad43bebe2d91d9af33f15a":{
      "scriptId":"u13"},
    "3ebf27e0f707454f955b47c137de1133":{
      "scriptId":"u14"},
    "7db2b5041fab4bbbbad8d818968e5bf2":{
      "scriptId":"u15"},
    "885266a8072c4e6692d8dbbf5a8a2326":{
      "scriptId":"u16"},
    "d5eea6784a724e84a44ae2ae6942393e":{
      "scriptId":"u17"},
    "35e723463eed440eb933ae934c8ac4cf":{
      "scriptId":"u18"},
    "408cdeb5272a4ec7a2c76a7f796ccbdd":{
      "scriptId":"u19"},
    "b6d59c9473fa4fbca971e9a8e9e3337c":{
      "scriptId":"u20"},
    "03909631d8f842f0bd9f6ee1394fc9b7":{
      "scriptId":"u21"},
    "9666263d71b24c7183342aab376183d6":{
      "scriptId":"u22"},
    "4965069be88142ea876d052c2cdbcc04":{
      "scriptId":"u23"},
    "677b9938e3554fcc811057c09d62b45f":{
      "scriptId":"u24"},
    "0efb6a53783748069cf12f0a6cbce337":{
      "scriptId":"u25"},
    "c5fa7bc7518b4586b4e2fa96e918c7f7":{
      "scriptId":"u26"},
    "6e7350ee5aa94b67bd4deb363130cd89":{
      "scriptId":"u27"},
    "e01aadc6366e465189c9a82f0d48a096":{
      "scriptId":"u28"},
    "9c1335bf840642719706303747c77e91":{
      "scriptId":"u29"},
    "feafcf11983043e28827a566b9c5369d":{
      "scriptId":"u30"},
    "74583247cbdd4f7b8bfd9e89a9f07c16":{
      "scriptId":"u31"},
    "7f56d30963da4d1c97a673b7bb7d1002":{
      "scriptId":"u32"},
    "79361b5b5a8d4acaa8141e2097e1e646":{
      "scriptId":"u33"},
    "1f868ca4901340b8847dceff5bfa2138":{
      "scriptId":"u34"},
    "c79149e987aa4fe1a695e35113366cb2":{
      "scriptId":"u35"},
    "4fae3c1f1ec146d19eb6bc5a40dc174f":{
      "scriptId":"u36"},
    "5ed6c9845e6f4d75a74aab57008e4448":{
      "scriptId":"u37"},
    "0f83b245be284a35b0a1636d2cd6eca4":{
      "scriptId":"u38"},
    "d6413961d3c0424caa95c26593d7a203":{
      "scriptId":"u39"},
    "23045e5deecb4b0ea41d2399853db17e":{
      "scriptId":"u40"},
    "d9a07b1bc86d4e6ab1902177c9527b5c":{
      "scriptId":"u41"},
    "334290c27b1245458c85e8f11b06840c":{
      "scriptId":"u42"},
    "ea0d840ad87d42da9c8486a27d29977a":{
      "scriptId":"u43"},
    "857fc685c4ec49fdb21503e840a1ef41":{
      "scriptId":"u44"},
    "1ecf777e04014b9cb3d5ab7331ef6bab":{
      "scriptId":"u45"},
    "51bdd8419db245ffa2501185c6eb7e17":{
      "scriptId":"u46"},
    "02ee95ce98c642f3b56971157695b0c4":{
      "scriptId":"u47"},
    "dcef60ca62054b4c8b9b3d4819023e8d":{
      "scriptId":"u48"},
    "cd6ffb9bf7c341c3952c10d2b729df6e":{
      "scriptId":"u49"},
    "eb85b773b1cc43fbb73777393b7e4df6":{
      "scriptId":"u50"},
    "7673adca1f4740dbb765944d9f22a6dc":{
      "scriptId":"u51"},
    "548cc89146d54992b279b1d97acac622":{
      "scriptId":"u52"},
    "d4b4a1f6729a40d784606c7fab8340eb":{
      "scriptId":"u53"},
    "92203087f72c4e308820a4ef04c98079":{
      "scriptId":"u54"},
    "c75f7bb917424b47ac5f10a6c76665b9":{
      "scriptId":"u55"}}});