$axure.loadCurrentPage({
  "url":"添加_4.html",
  "generationDate":new Date(1554888121586.05),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"6c809232d2c143fb9e367812df254c62",
    "type":"Axure:Page",
    "name":"添加",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"469b8f9300a7450e8b6f8fa7dbc84c6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":20,
              "y":93},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"948ba1c86896482c8e61ccc71152e943",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":93},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24a64bb89da54763b233d1d94e7f0cab",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":91},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2471b474b68243c9b802bcb41bcd77f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":220,
              "y":92},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcddb04326354805b2bb65d24fde52ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":220,
                  "y":92},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3da4392157fb4c729732585eb852a476",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":90},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8e0297ea4d2f454998d36441447da5c2",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":43},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"851a3f6f96a44a7a852ce1675c6b8fc5",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":43},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"closeCurrent",
                      "description":"关闭当前窗口"}]}]}},
          "tabbable":true},
{
          "id":"7e63b9b3a3ff435a8ec408508315b74a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":690,
              "y":93},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b6ada20efd34cbfad160c78c3324591",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":690,
                  "y":93},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5995b08ffa5441e86d49400d8109b83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":136},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a44cb0b6e7b043488724bbdd3584d600",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":136},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58e0c7913d1c4545813dc2a4b19b9539",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":136},
            "size":{
              "width":320,
              "height":95}},
          "adaptiveStyles":{
}},
{
          "id":"26d1a15b371a4e78828077e54f02a743",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":430,
              "y":92},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19a6a7dfe42f4a2b8e92228ba5cd4168",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":430,
                  "y":92},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8bdae4e8c548421d9e6a30da594cbe95",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":750,
              "y":91},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"e86d9fd8ab684c49a83d968191ebfe91",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":91},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a72648723861423fa1627da5077b8a76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":91},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"e395f255cc3649b5b5b0ab94d28fc457",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":91},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"054df47d8466409abd30e620b6c93d54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":91},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"1d66c38f1e9843ff8b80af7f52242c94",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":93},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bec8da536ace441f990d8bdacac94fe2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":93},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"b7056c587c1947118e3842fddaf3e7b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":17,
              "y":5},
            "size":{
              "width":950,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f52cfe73e2814044a3f1998aca107428",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":17,
                  "y":5},
                "size":{
                  "width":950,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库信息/u144.png"}},
{
          "id":"4c1c13a372b244a682ca8555d3b2702f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":23,
              "y":10},
            "size":{
              "width":122,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0800347d9eb646a198a40bdef7f36bc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":23,
                  "y":10},
                "size":{
                  "width":122,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f686f5069794442ebea1b892d013aabf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":128,
              "y":12},
            "size":{
              "width":62,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94a4ab7b28c548ae8982023d35a2bd71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":128,
                  "y":12},
                "size":{
                  "width":62,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"494192a702404db9a77f5c811d597f38",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":190,
              "y":12},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d153105c0a3541a785e9b4ac4d3bc61d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":12},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6ce5f0ef4a6497cad44211501e855f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":304,
              "y":12},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6593855eded149c78fd9b92a007619f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":304,
                  "y":12},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26e2fb79b1c0445c87853e3deee194f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":420,
              "y":12},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e0f71212d90436a9b9dc60de9bc458f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":420,
                  "y":12},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"253f5d609e33471097afc95382129e40",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":530,
              "y":12},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b74a5b28ac94c5491fb787b2eee0412",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":530,
                  "y":12},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df930ffc15d54ec59aa82a02c435d4c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":641,
              "y":12},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6325df1e5204a12b7ba3d0a2952d244",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":641,
                  "y":12},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92abfb1a48e1447fbc5d210a359eac63",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":739,
              "y":12},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a599d2ee4b6c48f19b250a7b2b15a0d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":739,
                  "y":12},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8cfedd4da9c54c8789812b0c92635d69",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":833,
              "y":12},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"921b1481ad59449e847423237a921c2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":833,
                  "y":12},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04cc3d5f910b4d98a28a882cad9fc7c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":22,
              "y":456},
            "size":{
              "width":957,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a216f7ce7d1b4586be8810d1c467f21c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":22,
                  "y":456},
                "size":{
                  "width":957,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库信息/u164.png"}},
{
          "id":"65a2e6a03d594e809150fd65606c8a55",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":836,
              "y":462},
            "size":{
              "width":134,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2945c664bfb4a0b92ab9fe8ea5c6a97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":836,
                  "y":462},
                "size":{
                  "width":134,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "469b8f9300a7450e8b6f8fa7dbc84c6b":{
      "scriptId":"u0"},
    "948ba1c86896482c8e61ccc71152e943":{
      "scriptId":"u1"},
    "24a64bb89da54763b233d1d94e7f0cab":{
      "scriptId":"u2"},
    "2471b474b68243c9b802bcb41bcd77f1":{
      "scriptId":"u3"},
    "bcddb04326354805b2bb65d24fde52ab":{
      "scriptId":"u4"},
    "3da4392157fb4c729732585eb852a476":{
      "scriptId":"u5"},
    "8e0297ea4d2f454998d36441447da5c2":{
      "scriptId":"u6"},
    "851a3f6f96a44a7a852ce1675c6b8fc5":{
      "scriptId":"u7"},
    "7e63b9b3a3ff435a8ec408508315b74a":{
      "scriptId":"u8"},
    "8b6ada20efd34cbfad160c78c3324591":{
      "scriptId":"u9"},
    "b5995b08ffa5441e86d49400d8109b83":{
      "scriptId":"u10"},
    "a44cb0b6e7b043488724bbdd3584d600":{
      "scriptId":"u11"},
    "58e0c7913d1c4545813dc2a4b19b9539":{
      "scriptId":"u12"},
    "26d1a15b371a4e78828077e54f02a743":{
      "scriptId":"u13"},
    "19a6a7dfe42f4a2b8e92228ba5cd4168":{
      "scriptId":"u14"},
    "8bdae4e8c548421d9e6a30da594cbe95":{
      "scriptId":"u15"},
    "e86d9fd8ab684c49a83d968191ebfe91":{
      "scriptId":"u16"},
    "a72648723861423fa1627da5077b8a76":{
      "scriptId":"u17"},
    "e395f255cc3649b5b5b0ab94d28fc457":{
      "scriptId":"u18"},
    "054df47d8466409abd30e620b6c93d54":{
      "scriptId":"u19"},
    "1d66c38f1e9843ff8b80af7f52242c94":{
      "scriptId":"u20"},
    "bec8da536ace441f990d8bdacac94fe2":{
      "scriptId":"u21"},
    "b7056c587c1947118e3842fddaf3e7b3":{
      "scriptId":"u22"},
    "f52cfe73e2814044a3f1998aca107428":{
      "scriptId":"u23"},
    "4c1c13a372b244a682ca8555d3b2702f":{
      "scriptId":"u24"},
    "0800347d9eb646a198a40bdef7f36bc9":{
      "scriptId":"u25"},
    "f686f5069794442ebea1b892d013aabf":{
      "scriptId":"u26"},
    "94a4ab7b28c548ae8982023d35a2bd71":{
      "scriptId":"u27"},
    "494192a702404db9a77f5c811d597f38":{
      "scriptId":"u28"},
    "d153105c0a3541a785e9b4ac4d3bc61d":{
      "scriptId":"u29"},
    "b6ce5f0ef4a6497cad44211501e855f7":{
      "scriptId":"u30"},
    "6593855eded149c78fd9b92a007619f6":{
      "scriptId":"u31"},
    "26e2fb79b1c0445c87853e3deee194f2":{
      "scriptId":"u32"},
    "9e0f71212d90436a9b9dc60de9bc458f":{
      "scriptId":"u33"},
    "253f5d609e33471097afc95382129e40":{
      "scriptId":"u34"},
    "8b74a5b28ac94c5491fb787b2eee0412":{
      "scriptId":"u35"},
    "df930ffc15d54ec59aa82a02c435d4c9":{
      "scriptId":"u36"},
    "b6325df1e5204a12b7ba3d0a2952d244":{
      "scriptId":"u37"},
    "92abfb1a48e1447fbc5d210a359eac63":{
      "scriptId":"u38"},
    "a599d2ee4b6c48f19b250a7b2b15a0d6":{
      "scriptId":"u39"},
    "8cfedd4da9c54c8789812b0c92635d69":{
      "scriptId":"u40"},
    "921b1481ad59449e847423237a921c2c":{
      "scriptId":"u41"},
    "04cc3d5f910b4d98a28a882cad9fc7c2":{
      "scriptId":"u42"},
    "a216f7ce7d1b4586be8810d1c467f21c":{
      "scriptId":"u43"},
    "65a2e6a03d594e809150fd65606c8a55":{
      "scriptId":"u44"},
    "a2945c664bfb4a0b92ab9fe8ea5c6a97":{
      "scriptId":"u45"}}});