$axure.loadCurrentPage({
  "url":"箱移入.html",
  "generationDate":new Date(1554888136358.56),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"182e74577f7f462396abed1738bee4bd",
    "type":"Axure:Page",
    "name":"箱移入",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5518a590ea9b46dbafd008e4220149f1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":50},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"840d29799b894f6fba757062ae7dd871",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":85},
            "size":{
              "width":92,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cec22b6e853b4b919ad333099b9a4e0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":85},
                "size":{
                  "width":92,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac4132db7c7f4720a571adf9bc984e7e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":85},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8173c7d6ec364001847df253cf705044",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "size":{
              "width":305,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"482f4943268140be8ad87a580def8c00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "size":{
                  "width":305,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u6.png"}},
{
          "id":"0829e1a4204848cd9bbd16108288ad46",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":4,
              "y":5},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d5fa96bfd04459d82404400feb51930",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":4,
                  "y":5},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35b2b05e07e149b5ab1c1362dcffea37",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":124,
              "y":7},
            "size":{
              "width":181,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbeb027b3b434ca4a33b4554106a6bc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":124,
                  "y":7},
                "size":{
                  "width":181,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f2bc84c7c0e43be9d189002f171d5f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":1,
              "y":451},
            "size":{
              "width":308,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"084bceef2674439f8619ced7f52cc425",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":1,
                  "y":451},
                "size":{
                  "width":308,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u12.png"}},
{
          "id":"f5102393bf5f4744b101be41cd5e3ad7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":144,
              "y":457},
            "size":{
              "width":162,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e4295955555469a8461cec979d35014",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":144,
                  "y":457},
                "size":{
                  "width":162,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"541d83f38fb545b69f5cd559aa72c433",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":49},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8cec3c252c84648b4eec3e95e88ab36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":49},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"83beee1e8d734bb1aec5fe2708d22c95",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCCC},
            "location":{
              "x":305,
              "y":24},
            "size":{
              "width":300,
              "height":276}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21bbba458085474d8a98b18c451b4404",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCCC},
                "location":{
                  "x":305,
                  "y":24},
                "size":{
                  "width":300,
                  "height":276}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/箱移入/u16.png"}},
{
          "id":"43093af4139d429a9c9a0ee4051b6d30",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":194,
              "y":400},
            "size":{
              "width":91,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"66964971d227455ea41ff3e0f21ecbf7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":120},
            "size":{
              "width":92,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ebd032d32884fdca0ef1f4d28cef140",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":120},
                "size":{
                  "width":92,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9dcd9cfcc1fd497ab41e7d69dc690d61",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":120},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2f851f603ed0415c837d6e416bdd540c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":166},
            "size":{
              "width":92,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92fd3b0ea9e44c42b4da72cfb85fa9fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":166},
                "size":{
                  "width":92,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb771e0654bf4cf184f0844e86b66c15",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":166},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c372c04fe7b14834b4971cf0e5951726",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":201},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"65649cb5571c48688c3f72cceeefdc7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":200},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5343cab05488475db88d8e70de9fffe7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":200},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e7de1e4a8a040eba07f5c2c6a48a1f2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":234},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2edb994b1f394fec83ff287c5364c730",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":234},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ae78986de0f427b81c2b557922b42aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":234},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5d2a22223ad485ba8885179326751a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFF00FF00},
            "location":{
              "x":60,
              "y":350},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"110bbef989444beeba774a10bcb27a02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FF00},
                "location":{
                  "x":60,
                  "y":350},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/箱移入/u31.png"}},
{
          "id":"0d6e7990ed0c44efa7af1344f57613ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":178,
              "y":350},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5db64b8de91c454f93ff52e224802395",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":178,
                  "y":350},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/箱移入/u33.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "5518a590ea9b46dbafd008e4220149f1":{
      "scriptId":"u0"},
    "840d29799b894f6fba757062ae7dd871":{
      "scriptId":"u1"},
    "cec22b6e853b4b919ad333099b9a4e0c":{
      "scriptId":"u2"},
    "ac4132db7c7f4720a571adf9bc984e7e":{
      "scriptId":"u3"},
    "8173c7d6ec364001847df253cf705044":{
      "scriptId":"u4"},
    "482f4943268140be8ad87a580def8c00":{
      "scriptId":"u5"},
    "0829e1a4204848cd9bbd16108288ad46":{
      "scriptId":"u6"},
    "8d5fa96bfd04459d82404400feb51930":{
      "scriptId":"u7"},
    "35b2b05e07e149b5ab1c1362dcffea37":{
      "scriptId":"u8"},
    "fbeb027b3b434ca4a33b4554106a6bc4":{
      "scriptId":"u9"},
    "2f2bc84c7c0e43be9d189002f171d5f6":{
      "scriptId":"u10"},
    "084bceef2674439f8619ced7f52cc425":{
      "scriptId":"u11"},
    "f5102393bf5f4744b101be41cd5e3ad7":{
      "scriptId":"u12"},
    "0e4295955555469a8461cec979d35014":{
      "scriptId":"u13"},
    "541d83f38fb545b69f5cd559aa72c433":{
      "scriptId":"u14"},
    "a8cec3c252c84648b4eec3e95e88ab36":{
      "scriptId":"u15"},
    "83beee1e8d734bb1aec5fe2708d22c95":{
      "scriptId":"u16"},
    "21bbba458085474d8a98b18c451b4404":{
      "scriptId":"u17"},
    "43093af4139d429a9c9a0ee4051b6d30":{
      "scriptId":"u18"},
    "66964971d227455ea41ff3e0f21ecbf7":{
      "scriptId":"u19"},
    "7ebd032d32884fdca0ef1f4d28cef140":{
      "scriptId":"u20"},
    "9dcd9cfcc1fd497ab41e7d69dc690d61":{
      "scriptId":"u21"},
    "2f851f603ed0415c837d6e416bdd540c":{
      "scriptId":"u22"},
    "92fd3b0ea9e44c42b4da72cfb85fa9fb":{
      "scriptId":"u23"},
    "fb771e0654bf4cf184f0844e86b66c15":{
      "scriptId":"u24"},
    "c372c04fe7b14834b4971cf0e5951726":{
      "scriptId":"u25"},
    "65649cb5571c48688c3f72cceeefdc7c":{
      "scriptId":"u26"},
    "5343cab05488475db88d8e70de9fffe7":{
      "scriptId":"u27"},
    "2e7de1e4a8a040eba07f5c2c6a48a1f2":{
      "scriptId":"u28"},
    "2edb994b1f394fec83ff287c5364c730":{
      "scriptId":"u29"},
    "5ae78986de0f427b81c2b557922b42aa":{
      "scriptId":"u30"},
    "d5d2a22223ad485ba8885179326751a6":{
      "scriptId":"u31"},
    "110bbef989444beeba774a10bcb27a02":{
      "scriptId":"u32"},
    "0d6e7990ed0c44efa7af1344f57613ea":{
      "scriptId":"u33"},
    "5db64b8de91c454f93ff52e224802395":{
      "scriptId":"u34"}}});