$axure.loadCurrentPage({
  "url":"任务交接.html",
  "generationDate":new Date(1554888135675.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"14694036f765451c81f67248dc7bf58d",
    "type":"Axure:Page",
    "name":"任务交接",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"58eb5a586bc74f0eb6bfd31e0ce3a11f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "location":{
              "x":30,
              "y":57},
            "size":{
              "width":59,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8740dc74c384998a0dfb7fd8f2418cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":30,
                  "y":57},
                "size":{
                  "width":59,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db336adb02af422a9ccd7d7812f9ee62",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":109,
              "y":58},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f8a519ef594645019929e70741bbaf08",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":19,
              "y":168},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01a02637c4654156a9b8401dbd7e1126",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":19,
                  "y":168},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b8e369ef1435454481ed7a21913cce79",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "fontName":"'Arial Black', 'Arial'",
            "fontSize":"11px",
            "fontWeight":"900",
            "location":{
              "x":109,
              "y":168},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a6ceedf752fc4865b288357ab684d277",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "size":{
              "width":305,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03fb261b17f2407ab5e1ac86d84dfbc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "size":{
                  "width":305,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u6.png"}},
{
          "id":"e3c952fddffe410e992c1debccd7ade6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":4,
              "y":5},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6c546c88573472181719ef31cda26df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":4,
                  "y":5},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"22adf9cc270d42859cf36137dc9bd2b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":134,
              "y":6},
            "size":{
              "width":166,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92930a4208c94f31a3ce66ea70d4c97b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":134,
                  "y":6},
                "size":{
                  "width":166,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c050792e7fc643f79dd853dbb3df2283",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":1,
              "y":451},
            "size":{
              "width":305,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"977c3809827a41d4a503dc324e3d5cf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":1,
                  "y":451},
                "size":{
                  "width":305,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u6.png"}},
{
          "id":"9b103428bbc94213bcae478478d37506",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":143,
              "y":457},
            "size":{
              "width":157,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34b07cd7012b4099abe54249d87f79cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":143,
                  "y":457},
                "size":{
                  "width":157,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"faa8447721dc4e14bfbd01b8166f7efe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCCC},
            "location":{
              "x":350,
              "y":7},
            "size":{
              "width":332,
              "height":473}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a03078efc5334457bd2a4b86983b0fa2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCCC},
                "location":{
                  "x":350,
                  "y":7},
                "size":{
                  "width":332,
                  "height":473}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/任务交接/u16.png"}},
{
          "id":"c74d3f97ce994a40b7a1e740cae0f688",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":109,
              "y":330},
            "size":{
              "width":91,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb7de0ca22ce485e831e9d23fd72ef94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":109,
                  "y":330},
                "size":{
                  "width":91,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/任务交接/u18.png"}},
{
          "id":"40fadc45757443149355a1f8506638bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":40,
              "y":370},
            "size":{
              "width":250,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd251c9c9e4b4829bf327052630da7c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":40,
                  "y":370},
                "size":{
                  "width":250,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/任务交接/u20.png"}},
{
          "id":"138f086b4213487f9f7bd91ab904e420",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "location":{
              "x":30,
              "y":96},
            "size":{
              "width":59,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d0a21f042824454b19cd29f290ae455",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":30,
                  "y":96},
                "size":{
                  "width":59,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25a534e02ef84796ad32552766386f52",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "fontName":"'Arial Black', 'Arial'",
            "fontSize":"11px",
            "fontWeight":"900",
            "location":{
              "x":109,
              "y":96},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9a20bd59299644a5ad05130d10e313b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "location":{
              "x":30,
              "y":131},
            "size":{
              "width":59,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1939b2d436d7482fab1a9f7bd0ae8da2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":30,
                  "y":131},
                "size":{
                  "width":59,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"784991b361fe469291e883b49bbd93d7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "fontName":"'Arial Black', 'Arial'",
            "fontSize":"11px",
            "fontWeight":"900",
            "location":{
              "x":109,
              "y":131},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9210b149a2db40f7a59b88695b652af7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":30,
              "y":224},
            "size":{
              "width":270,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9d259af575e40e09b19d6b9b35cf8ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":30,
                  "y":224},
                "size":{
                  "width":270,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/任务交接/u28.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "58eb5a586bc74f0eb6bfd31e0ce3a11f":{
      "scriptId":"u0"},
    "e8740dc74c384998a0dfb7fd8f2418cd":{
      "scriptId":"u1"},
    "db336adb02af422a9ccd7d7812f9ee62":{
      "scriptId":"u2"},
    "f8a519ef594645019929e70741bbaf08":{
      "scriptId":"u3"},
    "01a02637c4654156a9b8401dbd7e1126":{
      "scriptId":"u4"},
    "b8e369ef1435454481ed7a21913cce79":{
      "scriptId":"u5"},
    "a6ceedf752fc4865b288357ab684d277":{
      "scriptId":"u6"},
    "03fb261b17f2407ab5e1ac86d84dfbc3":{
      "scriptId":"u7"},
    "e3c952fddffe410e992c1debccd7ade6":{
      "scriptId":"u8"},
    "a6c546c88573472181719ef31cda26df":{
      "scriptId":"u9"},
    "22adf9cc270d42859cf36137dc9bd2b5":{
      "scriptId":"u10"},
    "92930a4208c94f31a3ce66ea70d4c97b":{
      "scriptId":"u11"},
    "c050792e7fc643f79dd853dbb3df2283":{
      "scriptId":"u12"},
    "977c3809827a41d4a503dc324e3d5cf8":{
      "scriptId":"u13"},
    "9b103428bbc94213bcae478478d37506":{
      "scriptId":"u14"},
    "34b07cd7012b4099abe54249d87f79cf":{
      "scriptId":"u15"},
    "faa8447721dc4e14bfbd01b8166f7efe":{
      "scriptId":"u16"},
    "a03078efc5334457bd2a4b86983b0fa2":{
      "scriptId":"u17"},
    "c74d3f97ce994a40b7a1e740cae0f688":{
      "scriptId":"u18"},
    "cb7de0ca22ce485e831e9d23fd72ef94":{
      "scriptId":"u19"},
    "40fadc45757443149355a1f8506638bb":{
      "scriptId":"u20"},
    "fd251c9c9e4b4829bf327052630da7c5":{
      "scriptId":"u21"},
    "138f086b4213487f9f7bd91ab904e420":{
      "scriptId":"u22"},
    "8d0a21f042824454b19cd29f290ae455":{
      "scriptId":"u23"},
    "25a534e02ef84796ad32552766386f52":{
      "scriptId":"u24"},
    "9a20bd59299644a5ad05130d10e313b5":{
      "scriptId":"u25"},
    "1939b2d436d7482fab1a9f7bd0ae8da2":{
      "scriptId":"u26"},
    "784991b361fe469291e883b49bbd93d7":{
      "scriptId":"u27"},
    "9210b149a2db40f7a59b88695b652af7":{
      "scriptId":"u28"},
    "f9d259af575e40e09b19d6b9b35cf8ba":{
      "scriptId":"u29"}}});