$axure.loadCurrentPage({
  "url":"用户管理.html",
  "generationDate":new Date(1554888121887.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"d13acdaf55eb4e4d91eed54add9158ea",
    "type":"Axure:Page",
    "name":"用户管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"074076e8df634c75892f622d30e301ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":17,
              "y":19},
            "size":{
              "width":950,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed7a775dee094322b5f58ea8c1949d3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":17,
                  "y":19},
                "size":{
                  "width":950,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库信息/u144.png"}},
{
          "id":"6ff72c781fcd4a1e92bc63cdde9f6960",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":23,
              "y":24},
            "size":{
              "width":122,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe93236dd6a8465fb80f76c2d78d7ef2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":23,
                  "y":24},
                "size":{
                  "width":122,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ecf5b11d65614dd598b51e2ab9320029",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":128,
              "y":26},
            "size":{
              "width":62,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fe970859f5f4b02a87a1e1d9dcdebb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":128,
                  "y":26},
                "size":{
                  "width":62,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6712b43ceea4a28a048e64408faf5c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":190,
              "y":26},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c33b21c1d33484988dd31ee40714a8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":26},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70691e18da2f494ca6a6b142a5b8f54c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":304,
              "y":26},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bac4fce6cba44abab5800ea8b8042513",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":304,
                  "y":26},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18e1cd98d6564d4d83d0ba101b7d5f80",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":420,
              "y":26},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96c4b329e5644f0790663113fa6ed660",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":420,
                  "y":26},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3d97a88bc79438d824e390c5bad93dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":530,
              "y":26},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a6dd45882854993832c9569929fa2dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":530,
                  "y":26},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3bc7337172c481b95557a045feec1a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":641,
              "y":26},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"babf542fcc2b40c093bd8702b2d60312",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":641,
                  "y":26},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e6e0b6dfb344d66b0fc13c6472aa4be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":739,
              "y":26},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8550440d5a2a4be49625e3153ee82dc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":739,
                  "y":26},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14ebf081cbd74181895ba9deedcaadf0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":833,
              "y":26},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a7233e7cecb413bbf00f5fb71310a5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":833,
                  "y":26},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"afa6ceba21ec4cf9a6c6004539150eac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":22,
              "y":470},
            "size":{
              "width":957,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8393b197293f47ee853f215eacf7d6b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":22,
                  "y":470},
                "size":{
                  "width":957,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库信息/u164.png"}},
{
          "id":"0dbbcf764d914bbf8c128afe8e40809b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":836,
              "y":476},
            "size":{
              "width":134,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"878e7eaf2aa344f486e509a44779c3cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":836,
                  "y":476},
                "size":{
                  "width":134,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6cba18e3e6cc4e87a4a3ca41af40c6b6",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":53},
            "size":{
              "width":74,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"85ece1a2be774d179a5c6b6574ed763f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":94,
              "y":53},
            "size":{
              "width":74,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1fd80bf9f23a4f1dab9bb66b2e647ec8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":53},
            "size":{
              "width":74,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ff3a7f3b79b948c68443a3837a89c0b8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":242,
              "y":53},
            "size":{
              "width":74,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4f91a17583624cf397c2ed59e511f51c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":315,
              "y":53},
            "size":{
              "width":74,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5c96d236abb8439da42256176a011a7f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":388,
              "y":53},
            "size":{
              "width":74,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "074076e8df634c75892f622d30e301ba":{
      "scriptId":"u0"},
    "ed7a775dee094322b5f58ea8c1949d3d":{
      "scriptId":"u1"},
    "6ff72c781fcd4a1e92bc63cdde9f6960":{
      "scriptId":"u2"},
    "fe93236dd6a8465fb80f76c2d78d7ef2":{
      "scriptId":"u3"},
    "ecf5b11d65614dd598b51e2ab9320029":{
      "scriptId":"u4"},
    "7fe970859f5f4b02a87a1e1d9dcdebb3":{
      "scriptId":"u5"},
    "d6712b43ceea4a28a048e64408faf5c0":{
      "scriptId":"u6"},
    "0c33b21c1d33484988dd31ee40714a8d":{
      "scriptId":"u7"},
    "70691e18da2f494ca6a6b142a5b8f54c":{
      "scriptId":"u8"},
    "bac4fce6cba44abab5800ea8b8042513":{
      "scriptId":"u9"},
    "18e1cd98d6564d4d83d0ba101b7d5f80":{
      "scriptId":"u10"},
    "96c4b329e5644f0790663113fa6ed660":{
      "scriptId":"u11"},
    "e3d97a88bc79438d824e390c5bad93dd":{
      "scriptId":"u12"},
    "2a6dd45882854993832c9569929fa2dd":{
      "scriptId":"u13"},
    "b3bc7337172c481b95557a045feec1a1":{
      "scriptId":"u14"},
    "babf542fcc2b40c093bd8702b2d60312":{
      "scriptId":"u15"},
    "8e6e0b6dfb344d66b0fc13c6472aa4be":{
      "scriptId":"u16"},
    "8550440d5a2a4be49625e3153ee82dc9":{
      "scriptId":"u17"},
    "14ebf081cbd74181895ba9deedcaadf0":{
      "scriptId":"u18"},
    "5a7233e7cecb413bbf00f5fb71310a5f":{
      "scriptId":"u19"},
    "afa6ceba21ec4cf9a6c6004539150eac":{
      "scriptId":"u20"},
    "8393b197293f47ee853f215eacf7d6b6":{
      "scriptId":"u21"},
    "0dbbcf764d914bbf8c128afe8e40809b":{
      "scriptId":"u22"},
    "878e7eaf2aa344f486e509a44779c3cf":{
      "scriptId":"u23"},
    "6cba18e3e6cc4e87a4a3ca41af40c6b6":{
      "scriptId":"u24"},
    "85ece1a2be774d179a5c6b6574ed763f":{
      "scriptId":"u25"},
    "1fd80bf9f23a4f1dab9bb66b2e647ec8":{
      "scriptId":"u26"},
    "ff3a7f3b79b948c68443a3837a89c0b8":{
      "scriptId":"u27"},
    "4f91a17583624cf397c2ed59e511f51c":{
      "scriptId":"u28"},
    "5c96d236abb8439da42256176a011a7f":{
      "scriptId":"u29"}}});