$axure.loadCurrentPage({
  "url":"添加_5.html",
  "generationDate":new Date(1554888121857.33),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"6614a8d29cc84c319cf8c5d65676a450",
    "type":"Axure:Page",
    "name":"添加",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8fdb6a6cb9234e04bba5862eabab61d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":20,
              "y":93},
            "size":{
              "width":65,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b398ebd7c6642d7b1e60e313f6b74ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":93},
                "size":{
                  "width":65,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec81632fc0a44eddba21c9357439ca6f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":91},
            "size":{
              "width":230,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"289bbedcaca54d5fa5dfa9a2d84da757",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":43},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c90d4610170442538c40d11fd0785c4b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":43},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"closeCurrent",
                      "description":"关闭当前窗口"}]}]}},
          "tabbable":true},
{
          "id":"5db6004441734d1780d3be0d62538b71",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":30,
              "y":201},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2e0105e8eee4b2585968c100f50a20c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":30,
                  "y":201},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89a23b93abd8435f9c622b6dd7438a13",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":199},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"efca45c1e4704a00a0b91b51f897206d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":345,
              "y":93},
            "size":{
              "width":65,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78496b2ee1034182bc4647dfcf0989de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":345,
                  "y":93},
                "size":{
                  "width":65,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b897306526734e5ebd61c6157515e86a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":415,
              "y":91},
            "size":{
              "width":480,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6ebb50f1b4ed4df2b4f24390b88c8daf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":20,
              "y":128},
            "size":{
              "width":65,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6196db79ab2a4a6c96354c6b22be1e79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":128},
                "size":{
                  "width":65,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9d56b50f84847178bbb0e1df14fea0e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":126},
            "size":{
              "width":230,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8148ac1ff7bd4cabb2c4a0ef788b496a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":20,
              "y":163},
            "size":{
              "width":65,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e893f82f6f834db0954ed28c73defa8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":163},
                "size":{
                  "width":65,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e801c16b8e8745288a76457a4863e75b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":161},
            "size":{
              "width":230,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6900a519c4f74de18603725d98ac23b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":345,
              "y":128},
            "size":{
              "width":65,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7ec396714314658befa131f0d32e4e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":345,
                  "y":128},
                "size":{
                  "width":65,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"470b96feeb2a477e9d7526dbcd2c57f7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":415,
              "y":126},
            "size":{
              "width":195,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f23c312242d4455d98227ea04fb02bbb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":345,
              "y":163},
            "size":{
              "width":65,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9aad7e691b3e43a5a2a9cca4e6841e47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":345,
                  "y":163},
                "size":{
                  "width":65,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61b5f0de9a5a4ff09dbefad723f5489e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":415,
              "y":161},
            "size":{
              "width":195,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1389f2b0bcc642f2b9d805769875b168",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":345,
              "y":198},
            "size":{
              "width":65,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"496eb5dd6ff245bfac66795ee014045b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":345,
                  "y":198},
                "size":{
                  "width":65,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45370fb567c3421eaff58786bf80b03a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":415,
              "y":196},
            "size":{
              "width":480,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d5b0326a08b84ed4b9fb5e74c0ca2fbc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":630,
              "y":128},
            "size":{
              "width":65,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9175961a713e43f2a3898a8efecd5f23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":630,
                  "y":128},
                "size":{
                  "width":65,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2dea044e8a464b229b2ef298cb9656c3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":126},
            "size":{
              "width":195,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"20b09b5b00e849cb81cb88256590c4bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":630,
              "y":163},
            "size":{
              "width":65,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b1f587ceaec4901881933d14ff417c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":630,
                  "y":163},
                "size":{
                  "width":65,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e5c1466c3af4baeb94346cf4836af34",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":161},
            "size":{
              "width":195,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"21be30d9acd04a0e8157a960a4c0e22f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":17,
              "y":5},
            "size":{
              "width":950,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfdaebd514e148c2bca7f2ceb6532872",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":17,
                  "y":5},
                "size":{
                  "width":950,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库信息/u144.png"}},
{
          "id":"63ecef2078f94ddf90f3c231ce36b05c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":23,
              "y":10},
            "size":{
              "width":122,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2863f65b7753443593093250d4a01c0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":23,
                  "y":10},
                "size":{
                  "width":122,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5dcdb20e9d3e4e619c2b40b788416a63",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":128,
              "y":12},
            "size":{
              "width":62,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3fe42d451d943dfb45bf459f0bfff42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":128,
                  "y":12},
                "size":{
                  "width":62,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ad368a893ae4054ad3892cc68327bc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":190,
              "y":12},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd9358fa2f794c809ecb2c2b3e3b2c7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":12},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20de94edfb684c91a756ad20a6385f04",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":304,
              "y":12},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cff73d497bd34f3ba0d2651c8134dff2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":304,
                  "y":12},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd863224de7a487d95eda9daf6431fc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":420,
              "y":12},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5bc3812dd494f38b6e98d243df3c6db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":420,
                  "y":12},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5116f165b0e042b9bfab4f7f8c65e60c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":530,
              "y":12},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a095c31c52f40a1b8d098a2d6b12391",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":530,
                  "y":12},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca141ff1211a40459c2ae1e0197aa490",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":641,
              "y":12},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"387a858493ee4c49ac86ab2f3954d79c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":641,
                  "y":12},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59480ad567b146dd81629f4bd62a1c17",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":739,
              "y":12},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4906496306564c53894007802c22ad6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":739,
                  "y":12},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab318092eb60482283d79a306255a2b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":833,
              "y":12},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e210ebb27d4c4ebabba8b4208d9a3889",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":833,
                  "y":12},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c59e20b593054ea7821977bb074af186",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":22,
              "y":456},
            "size":{
              "width":957,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a61f8864f5943f29bc35a2fb1956a8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":22,
                  "y":456},
                "size":{
                  "width":957,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库信息/u164.png"}},
{
          "id":"64bb0e48e7bd45f1ad5b6a80e73b5d89",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":836,
              "y":462},
            "size":{
              "width":134,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bef1ee14764c498789b10094639e43cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":836,
                  "y":462},
                "size":{
                  "width":134,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "8fdb6a6cb9234e04bba5862eabab61d3":{
      "scriptId":"u0"},
    "6b398ebd7c6642d7b1e60e313f6b74ce":{
      "scriptId":"u1"},
    "ec81632fc0a44eddba21c9357439ca6f":{
      "scriptId":"u2"},
    "289bbedcaca54d5fa5dfa9a2d84da757":{
      "scriptId":"u3"},
    "c90d4610170442538c40d11fd0785c4b":{
      "scriptId":"u4"},
    "5db6004441734d1780d3be0d62538b71":{
      "scriptId":"u5"},
    "b2e0105e8eee4b2585968c100f50a20c":{
      "scriptId":"u6"},
    "89a23b93abd8435f9c622b6dd7438a13":{
      "scriptId":"u7"},
    "efca45c1e4704a00a0b91b51f897206d":{
      "scriptId":"u8"},
    "78496b2ee1034182bc4647dfcf0989de":{
      "scriptId":"u9"},
    "b897306526734e5ebd61c6157515e86a":{
      "scriptId":"u10"},
    "6ebb50f1b4ed4df2b4f24390b88c8daf":{
      "scriptId":"u11"},
    "6196db79ab2a4a6c96354c6b22be1e79":{
      "scriptId":"u12"},
    "d9d56b50f84847178bbb0e1df14fea0e":{
      "scriptId":"u13"},
    "8148ac1ff7bd4cabb2c4a0ef788b496a":{
      "scriptId":"u14"},
    "e893f82f6f834db0954ed28c73defa8d":{
      "scriptId":"u15"},
    "e801c16b8e8745288a76457a4863e75b":{
      "scriptId":"u16"},
    "6900a519c4f74de18603725d98ac23b8":{
      "scriptId":"u17"},
    "c7ec396714314658befa131f0d32e4e9":{
      "scriptId":"u18"},
    "470b96feeb2a477e9d7526dbcd2c57f7":{
      "scriptId":"u19"},
    "f23c312242d4455d98227ea04fb02bbb":{
      "scriptId":"u20"},
    "9aad7e691b3e43a5a2a9cca4e6841e47":{
      "scriptId":"u21"},
    "61b5f0de9a5a4ff09dbefad723f5489e":{
      "scriptId":"u22"},
    "1389f2b0bcc642f2b9d805769875b168":{
      "scriptId":"u23"},
    "496eb5dd6ff245bfac66795ee014045b":{
      "scriptId":"u24"},
    "45370fb567c3421eaff58786bf80b03a":{
      "scriptId":"u25"},
    "d5b0326a08b84ed4b9fb5e74c0ca2fbc":{
      "scriptId":"u26"},
    "9175961a713e43f2a3898a8efecd5f23":{
      "scriptId":"u27"},
    "2dea044e8a464b229b2ef298cb9656c3":{
      "scriptId":"u28"},
    "20b09b5b00e849cb81cb88256590c4bd":{
      "scriptId":"u29"},
    "1b1f587ceaec4901881933d14ff417c7":{
      "scriptId":"u30"},
    "7e5c1466c3af4baeb94346cf4836af34":{
      "scriptId":"u31"},
    "21be30d9acd04a0e8157a960a4c0e22f":{
      "scriptId":"u32"},
    "cfdaebd514e148c2bca7f2ceb6532872":{
      "scriptId":"u33"},
    "63ecef2078f94ddf90f3c231ce36b05c":{
      "scriptId":"u34"},
    "2863f65b7753443593093250d4a01c0e":{
      "scriptId":"u35"},
    "5dcdb20e9d3e4e619c2b40b788416a63":{
      "scriptId":"u36"},
    "c3fe42d451d943dfb45bf459f0bfff42":{
      "scriptId":"u37"},
    "1ad368a893ae4054ad3892cc68327bc5":{
      "scriptId":"u38"},
    "dd9358fa2f794c809ecb2c2b3e3b2c7a":{
      "scriptId":"u39"},
    "20de94edfb684c91a756ad20a6385f04":{
      "scriptId":"u40"},
    "cff73d497bd34f3ba0d2651c8134dff2":{
      "scriptId":"u41"},
    "bd863224de7a487d95eda9daf6431fc0":{
      "scriptId":"u42"},
    "b5bc3812dd494f38b6e98d243df3c6db":{
      "scriptId":"u43"},
    "5116f165b0e042b9bfab4f7f8c65e60c":{
      "scriptId":"u44"},
    "8a095c31c52f40a1b8d098a2d6b12391":{
      "scriptId":"u45"},
    "ca141ff1211a40459c2ae1e0197aa490":{
      "scriptId":"u46"},
    "387a858493ee4c49ac86ab2f3954d79c":{
      "scriptId":"u47"},
    "59480ad567b146dd81629f4bd62a1c17":{
      "scriptId":"u48"},
    "4906496306564c53894007802c22ad6b":{
      "scriptId":"u49"},
    "ab318092eb60482283d79a306255a2b2":{
      "scriptId":"u50"},
    "e210ebb27d4c4ebabba8b4208d9a3889":{
      "scriptId":"u51"},
    "c59e20b593054ea7821977bb074af186":{
      "scriptId":"u52"},
    "4a61f8864f5943f29bc35a2fb1956a8c":{
      "scriptId":"u53"},
    "64bb0e48e7bd45f1ad5b6a80e73b5d89":{
      "scriptId":"u54"},
    "bef1ee14764c498789b10094639e43cc":{
      "scriptId":"u55"}}});