$axure.loadCurrentPage({
  "url":"上架策略.html",
  "generationDate":new Date(1554888122834.71),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"a1b3aa40891e4036a95ebfd04891a41f",
    "type":"Axure:Page",
    "name":"上架策略",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"17bcfc90795f4a429c0755b113dbaaa4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":17,
              "y":19},
            "size":{
              "width":950,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc6afeeb552f4a9e98ec8b63f863f493",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":17,
                  "y":19},
                "size":{
                  "width":950,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库信息/u144.png"}},
{
          "id":"72f58ea4fef1493ebd14e0249a22548e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":23,
              "y":24},
            "size":{
              "width":122,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d92dd9051e654e7bbeda3694075e411e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":23,
                  "y":24},
                "size":{
                  "width":122,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2098b783ae1d4b12bc76b8e3e8779cfc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":128,
              "y":26},
            "size":{
              "width":62,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f907d6fde23442999d2952c0bd660ff2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":128,
                  "y":26},
                "size":{
                  "width":62,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68dd2bdd6a22427e961a2dd4400a2e92",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":190,
              "y":26},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4d9b0735d284c57847e55b164a5e56c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":26},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca4670252a904a4994b97b8c4d2f7e87",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":304,
              "y":26},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d71815bbb4b406e9a055b857f90823d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":304,
                  "y":26},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c719b6dcdbdb4c59a213ce9a2f5b50d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":420,
              "y":26},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83e11170ed414cf98bf420b746efc383",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":420,
                  "y":26},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"087c16c94fd7453b93476ac313e14122",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":530,
              "y":26},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7fb3d392a04497f9a911d74861054e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":530,
                  "y":26},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3bbdb635bee5478bbf02462dcd56db37",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":641,
              "y":26},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1778be7aac3447bcba5cbdc872052f4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":641,
                  "y":26},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58f8b0e8f20049628301cce2db4f0036",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":739,
              "y":26},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3238aefc506543f59a66dbd96d186f54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":739,
                  "y":26},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12df297bb37041f08cfdcdb40354b7ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":833,
              "y":26},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4539b1bb4344f538906e6af5dff90a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":833,
                  "y":26},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d882cf1d99e24e81921ea6b0529909cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":22,
              "y":470},
            "size":{
              "width":957,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1507408c79004aeda9244022f949dbd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":22,
                  "y":470},
                "size":{
                  "width":957,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库信息/u164.png"}},
{
          "id":"3225dc49facb4e51936f40500065cb6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":836,
              "y":476},
            "size":{
              "width":134,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f4a1ede7eb540b6839785cf1dc34c33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":836,
                  "y":476},
                "size":{
                  "width":134,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c495fa5c2ef46958eb0920b9ba82284",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":59},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d819bd221817474583dbdbbc97a70852",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":94},
            "size":{
              "width":123,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"495e91b1b6ee4dcbb723a59d5730085c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":94},
                "size":{
                  "width":123,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be4087a81c1743f495fedc24de87d067",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":456,
              "y":94},
            "size":{
              "width":123,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23034bb1e59c4142a2e3fabe4a6534bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":456,
                  "y":94},
                "size":{
                  "width":123,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"429ee75f75654eccb4017fded8c90a22",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":119},
            "size":{
              "width":190,
              "height":20}},
          "adaptiveStyles":{
}},
{
          "id":"49c4d90251e84641b790d8f77ec4d638",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":456,
              "y":119},
            "size":{
              "width":232,
              "height":20}},
          "adaptiveStyles":{
}},
{
          "id":"77afcd266bb34b3791fd954550a41115",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":217,
              "y":94},
            "size":{
              "width":123,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90b30f977ad6400d92ca6e79b0ecc39e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":217,
                  "y":94},
                "size":{
                  "width":123,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b39c6995b40d4d239cdbe131d6d3554e",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":217,
              "y":119},
            "size":{
              "width":229,
              "height":20}},
          "adaptiveStyles":{
}},
{
          "id":"5ce1e92f9ac443089f2f3b728e126c90",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":697,
              "y":94},
            "size":{
              "width":123,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7fbde3476b5456da8069f97a1959d3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":697,
                  "y":94},
                "size":{
                  "width":123,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec3794309ab243c3ad9e51510562288c",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":697,
              "y":119},
            "size":{
              "width":270,
              "height":20}},
          "adaptiveStyles":{
}},
{
          "id":"bd53cf7942de449093472973cfda1226",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":149},
            "size":{
              "width":190,
              "height":163}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2a272a3cc994a41a9ef9ba9f59a5bef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":149},
                "size":{
                  "width":190,
                  "height":163}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/上架策略/u37.png"}},
{
          "id":"cb872a22f1cd4e0aae8e39824b02f4b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":218,
              "y":149},
            "size":{
              "width":228,
              "height":163}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa4986cae9c1463696a9577da572b80a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":218,
                  "y":149},
                "size":{
                  "width":228,
                  "height":163}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/上架策略/u39.png"}},
{
          "id":"622a26cd77d24e8185548f7709ee0455",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":456,
              "y":149},
            "size":{
              "width":232,
              "height":163}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"952623bde9db4242afcd1b75e32dd384",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":456,
                  "y":149},
                "size":{
                  "width":232,
                  "height":163}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/上架策略/u41.png"}},
{
          "id":"2fae7b43e1a54183824e6060a56cae77",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":698,
              "y":149},
            "size":{
              "width":269,
              "height":163}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3be555293e864ecfbf17adcb2022c10f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":698,
                  "y":149},
                "size":{
                  "width":269,
                  "height":163}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/上架策略/u43.png"}},
{
          "id":"3bf76715ab804273b93f02f03f008fca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":341},
            "size":{
              "width":128,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46c43dac3e724ff1ad6184b8aa4d63cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":22,
                  "y":341},
                "size":{
                  "width":128,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ef01d97d156427f97995fad74a1db4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":375},
            "size":{
              "width":128,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52bb41577b8944789e75f311ee4eda5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":22,
                  "y":375},
                "size":{
                  "width":128,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16ef7a43bc1241a6858352e64598bbcb",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":335},
            "size":{
              "width":175,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"eeda4c1ae52d4d148b063f56a82ed91d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":370},
            "size":{
              "width":175,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "17bcfc90795f4a429c0755b113dbaaa4":{
      "scriptId":"u0"},
    "bc6afeeb552f4a9e98ec8b63f863f493":{
      "scriptId":"u1"},
    "72f58ea4fef1493ebd14e0249a22548e":{
      "scriptId":"u2"},
    "d92dd9051e654e7bbeda3694075e411e":{
      "scriptId":"u3"},
    "2098b783ae1d4b12bc76b8e3e8779cfc":{
      "scriptId":"u4"},
    "f907d6fde23442999d2952c0bd660ff2":{
      "scriptId":"u5"},
    "68dd2bdd6a22427e961a2dd4400a2e92":{
      "scriptId":"u6"},
    "a4d9b0735d284c57847e55b164a5e56c":{
      "scriptId":"u7"},
    "ca4670252a904a4994b97b8c4d2f7e87":{
      "scriptId":"u8"},
    "8d71815bbb4b406e9a055b857f90823d":{
      "scriptId":"u9"},
    "c719b6dcdbdb4c59a213ce9a2f5b50d5":{
      "scriptId":"u10"},
    "83e11170ed414cf98bf420b746efc383":{
      "scriptId":"u11"},
    "087c16c94fd7453b93476ac313e14122":{
      "scriptId":"u12"},
    "f7fb3d392a04497f9a911d74861054e6":{
      "scriptId":"u13"},
    "3bbdb635bee5478bbf02462dcd56db37":{
      "scriptId":"u14"},
    "1778be7aac3447bcba5cbdc872052f4f":{
      "scriptId":"u15"},
    "58f8b0e8f20049628301cce2db4f0036":{
      "scriptId":"u16"},
    "3238aefc506543f59a66dbd96d186f54":{
      "scriptId":"u17"},
    "12df297bb37041f08cfdcdb40354b7ef":{
      "scriptId":"u18"},
    "b4539b1bb4344f538906e6af5dff90a7":{
      "scriptId":"u19"},
    "d882cf1d99e24e81921ea6b0529909cd":{
      "scriptId":"u20"},
    "1507408c79004aeda9244022f949dbd3":{
      "scriptId":"u21"},
    "3225dc49facb4e51936f40500065cb6a":{
      "scriptId":"u22"},
    "7f4a1ede7eb540b6839785cf1dc34c33":{
      "scriptId":"u23"},
    "3c495fa5c2ef46958eb0920b9ba82284":{
      "scriptId":"u24"},
    "d819bd221817474583dbdbbc97a70852":{
      "scriptId":"u25"},
    "495e91b1b6ee4dcbb723a59d5730085c":{
      "scriptId":"u26"},
    "be4087a81c1743f495fedc24de87d067":{
      "scriptId":"u27"},
    "23034bb1e59c4142a2e3fabe4a6534bd":{
      "scriptId":"u28"},
    "429ee75f75654eccb4017fded8c90a22":{
      "scriptId":"u29"},
    "49c4d90251e84641b790d8f77ec4d638":{
      "scriptId":"u30"},
    "77afcd266bb34b3791fd954550a41115":{
      "scriptId":"u31"},
    "90b30f977ad6400d92ca6e79b0ecc39e":{
      "scriptId":"u32"},
    "b39c6995b40d4d239cdbe131d6d3554e":{
      "scriptId":"u33"},
    "5ce1e92f9ac443089f2f3b728e126c90":{
      "scriptId":"u34"},
    "d7fbde3476b5456da8069f97a1959d3e":{
      "scriptId":"u35"},
    "ec3794309ab243c3ad9e51510562288c":{
      "scriptId":"u36"},
    "bd53cf7942de449093472973cfda1226":{
      "scriptId":"u37"},
    "f2a272a3cc994a41a9ef9ba9f59a5bef":{
      "scriptId":"u38"},
    "cb872a22f1cd4e0aae8e39824b02f4b4":{
      "scriptId":"u39"},
    "fa4986cae9c1463696a9577da572b80a":{
      "scriptId":"u40"},
    "622a26cd77d24e8185548f7709ee0455":{
      "scriptId":"u41"},
    "952623bde9db4242afcd1b75e32dd384":{
      "scriptId":"u42"},
    "2fae7b43e1a54183824e6060a56cae77":{
      "scriptId":"u43"},
    "3be555293e864ecfbf17adcb2022c10f":{
      "scriptId":"u44"},
    "3bf76715ab804273b93f02f03f008fca":{
      "scriptId":"u45"},
    "46c43dac3e724ff1ad6184b8aa4d63cd":{
      "scriptId":"u46"},
    "5ef01d97d156427f97995fad74a1db4e":{
      "scriptId":"u47"},
    "52bb41577b8944789e75f311ee4eda5e":{
      "scriptId":"u48"},
    "16ef7a43bc1241a6858352e64598bbcb":{
      "scriptId":"u49"},
    "eeda4c1ae52d4d148b063f56a82ed91d":{
      "scriptId":"u50"}}});