$axure.loadCurrentPage({
  "url":"应急移库策略---3月新增未完成.html",
  "generationDate":new Date(1554888123093.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"a6ee3b057b884a11a80500b6e5070b87",
    "type":"Axure:Page",
    "name":"应急移库策略---3月新增未完成",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f69ce9b49b4546339896ee7b015ad936",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":59},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c75774493d32448a812647bd53bc1fa7",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":59},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"70518285524a4214baf5ba88c8bd6bf6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":17,
              "y":19},
            "size":{
              "width":950,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f1c6e9c5dba46179f13c8ddc3147b4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":17,
                  "y":19},
                "size":{
                  "width":950,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库信息/u144.png"}},
{
          "id":"b7cbe687d064412697098487d7260ff7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":23,
              "y":24},
            "size":{
              "width":122,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a57405d982814cf6a8fc5f84319c9f99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":23,
                  "y":24},
                "size":{
                  "width":122,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b20def006f9e46beac3f411730d91d83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":128,
              "y":26},
            "size":{
              "width":62,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb2dc19ca640452c827fba754f5e1b4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":128,
                  "y":26},
                "size":{
                  "width":62,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb9877f855f54f33983c5251c278fcd6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":190,
              "y":26},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a26e0ea39b14e81b9d02f9d8b622466",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":26},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9beee9b90b3648188a56206beca2bc18",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":304,
              "y":26},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d501fd89e8b84ce594a6cfb88bf0c562",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":304,
                  "y":26},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7eb706615bd2450dbb357eb11fb9515e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":420,
              "y":26},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"718f9b2a2a6e46caaf8f3bccf49420f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":420,
                  "y":26},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff7123fb1f194937b3fa3d0f64263485",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":530,
              "y":26},
            "size":{
              "width":82,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9bf48378d405422881e93588743fdf4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":530,
                  "y":26},
                "size":{
                  "width":82,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b1f9cde24254fd28aef647e82684166",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":641,
              "y":26},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4de46de30104beca9bee289fe495f18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":641,
                  "y":26},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c25c7c0f59f94d07920cb9b1320e4242",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":739,
              "y":26},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cbcbad4643742bda9ea060be5e0bb8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":739,
                  "y":26},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"efa009326a3a4bc2ab164a2221febf33",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":833,
              "y":26},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81223fcad9fe48b0a6f4008ec83f4da7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":833,
                  "y":26},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e1fed8350334c2b8dd7060361f45207",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":22,
              "y":470},
            "size":{
              "width":957,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d663496c5f24873a5d6ef48281c022f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":22,
                  "y":470},
                "size":{
                  "width":957,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库信息/u164.png"}},
{
          "id":"024a8dd046fb46e9a096f65e67fc8daa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":836,
              "y":476},
            "size":{
              "width":134,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4e0bbe967e9401990cfa5189c819414",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":836,
                  "y":476},
                "size":{
                  "width":134,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"032ab18ae9a44326b71ea2ba8c62e832",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCCC},
            "location":{
              "x":20,
              "y":206},
            "size":{
              "width":517,
              "height":257}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44b7dfe2383748b2a37800fc57e83ffb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCCC},
                "location":{
                  "x":20,
                  "y":206},
                "size":{
                  "width":517,
                  "height":257}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应急移库策略---3月新增未完成/u26.png"}},
{
          "id":"b9333e3e32714cde80fe7315b6b21b48",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF66FFFF},
            "location":{
              "x":29,
              "y":108},
            "size":{
              "width":31,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c43b74d625c7403aa8f0f0b73150d15a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF66FFFF},
                "location":{
                  "x":29,
                  "y":108},
                "size":{
                  "width":31,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应急移库策略---3月新增未完成/u28.png"}},
{
          "id":"62cd48aa86f74f4c9e22a1558b1e8c7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":138},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12f38d315a3947b7ab4c219a526fcbd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":138},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89373f3a65904f18a3b5793379f2fb6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":170},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57893ab6d6974d79bf02c3732e3f3621",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":170},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50441a3ab973474c8e781d283f21f67e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "fill":{
              "fillType":"solid",
              "color":0xFF66FFFF},
            "location":{
              "x":324,
              "y":108},
            "size":{
              "width":116,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b5b0e65c43243d2b1faa776128afce3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF66FFFF},
                "location":{
                  "x":324,
                  "y":108},
                "size":{
                  "width":116,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应急移库策略---3月新增未完成/u34.png"}},
{
          "id":"9502149b6abb43ff9acfb34fc90ac813",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":304,
              "y":138},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3171cc7e6123495ea84339593e3f8f53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":304,
                  "y":138},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd835903eb1a4bec9fd692f66a1530a4",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":418,
              "y":137},
            "size":{
              "width":44,
              "height":17}},
          "adaptiveStyles":{
}},
{
          "id":"db04f5f58eab4c77aa7651d004ec3026",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "fill":{
              "fillType":"solid",
              "color":0xFF66FFFF},
            "location":{
              "x":113,
              "y":108},
            "size":{
              "width":30,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddfdcd39994c4dcfb91bc0736ca2c99b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF66FFFF},
                "location":{
                  "x":113,
                  "y":108},
                "size":{
                  "width":30,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应急移库策略---3月新增未完成/u39.png"}},
{
          "id":"c0eaab9b021c444b863152300d634a8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "fill":{
              "fillType":"solid",
              "color":0xFF66FFFF},
            "location":{
              "x":180,
              "y":108},
            "size":{
              "width":101,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5dd5d8e0e0f46ed90ca8292f7de45b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF66FFFF},
                "location":{
                  "x":180,
                  "y":108},
                "size":{
                  "width":101,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应急移库策略---3月新增未完成/u41.png"}},
{
          "id":"3e1a40b09c4348e184553c538f059ff5",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":103,
              "y":138},
            "size":{
              "width":57,
              "height":17}},
          "adaptiveStyles":{
}},
{
          "id":"81f3eda368cf42d9bc350795888d6d94",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":103,
              "y":169},
            "size":{
              "width":57,
              "height":17}},
          "adaptiveStyles":{
}},
{
          "id":"fef44f5112a843688092d5585439374c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":198,
              "y":136},
            "size":{
              "width":70,
              "height":21}},
          "adaptiveStyles":{
}},
{
          "id":"3d6d28e2dcc14b4f8c82e646c824f156",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":198,
              "y":167},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "f69ce9b49b4546339896ee7b015ad936":{
      "scriptId":"u0"},
    "c75774493d32448a812647bd53bc1fa7":{
      "scriptId":"u1"},
    "70518285524a4214baf5ba88c8bd6bf6":{
      "scriptId":"u2"},
    "5f1c6e9c5dba46179f13c8ddc3147b4b":{
      "scriptId":"u3"},
    "b7cbe687d064412697098487d7260ff7":{
      "scriptId":"u4"},
    "a57405d982814cf6a8fc5f84319c9f99":{
      "scriptId":"u5"},
    "b20def006f9e46beac3f411730d91d83":{
      "scriptId":"u6"},
    "fb2dc19ca640452c827fba754f5e1b4d":{
      "scriptId":"u7"},
    "bb9877f855f54f33983c5251c278fcd6":{
      "scriptId":"u8"},
    "5a26e0ea39b14e81b9d02f9d8b622466":{
      "scriptId":"u9"},
    "9beee9b90b3648188a56206beca2bc18":{
      "scriptId":"u10"},
    "d501fd89e8b84ce594a6cfb88bf0c562":{
      "scriptId":"u11"},
    "7eb706615bd2450dbb357eb11fb9515e":{
      "scriptId":"u12"},
    "718f9b2a2a6e46caaf8f3bccf49420f3":{
      "scriptId":"u13"},
    "ff7123fb1f194937b3fa3d0f64263485":{
      "scriptId":"u14"},
    "9bf48378d405422881e93588743fdf4a":{
      "scriptId":"u15"},
    "5b1f9cde24254fd28aef647e82684166":{
      "scriptId":"u16"},
    "c4de46de30104beca9bee289fe495f18":{
      "scriptId":"u17"},
    "c25c7c0f59f94d07920cb9b1320e4242":{
      "scriptId":"u18"},
    "4cbcbad4643742bda9ea060be5e0bb8b":{
      "scriptId":"u19"},
    "efa009326a3a4bc2ab164a2221febf33":{
      "scriptId":"u20"},
    "81223fcad9fe48b0a6f4008ec83f4da7":{
      "scriptId":"u21"},
    "9e1fed8350334c2b8dd7060361f45207":{
      "scriptId":"u22"},
    "7d663496c5f24873a5d6ef48281c022f":{
      "scriptId":"u23"},
    "024a8dd046fb46e9a096f65e67fc8daa":{
      "scriptId":"u24"},
    "b4e0bbe967e9401990cfa5189c819414":{
      "scriptId":"u25"},
    "032ab18ae9a44326b71ea2ba8c62e832":{
      "scriptId":"u26"},
    "44b7dfe2383748b2a37800fc57e83ffb":{
      "scriptId":"u27"},
    "b9333e3e32714cde80fe7315b6b21b48":{
      "scriptId":"u28"},
    "c43b74d625c7403aa8f0f0b73150d15a":{
      "scriptId":"u29"},
    "62cd48aa86f74f4c9e22a1558b1e8c7c":{
      "scriptId":"u30"},
    "12f38d315a3947b7ab4c219a526fcbd5":{
      "scriptId":"u31"},
    "89373f3a65904f18a3b5793379f2fb6c":{
      "scriptId":"u32"},
    "57893ab6d6974d79bf02c3732e3f3621":{
      "scriptId":"u33"},
    "50441a3ab973474c8e781d283f21f67e":{
      "scriptId":"u34"},
    "4b5b0e65c43243d2b1faa776128afce3":{
      "scriptId":"u35"},
    "9502149b6abb43ff9acfb34fc90ac813":{
      "scriptId":"u36"},
    "3171cc7e6123495ea84339593e3f8f53":{
      "scriptId":"u37"},
    "fd835903eb1a4bec9fd692f66a1530a4":{
      "scriptId":"u38"},
    "db04f5f58eab4c77aa7651d004ec3026":{
      "scriptId":"u39"},
    "ddfdcd39994c4dcfb91bc0736ca2c99b":{
      "scriptId":"u40"},
    "c0eaab9b021c444b863152300d634a8c":{
      "scriptId":"u41"},
    "e5dd5d8e0e0f46ed90ca8292f7de45b8":{
      "scriptId":"u42"},
    "3e1a40b09c4348e184553c538f059ff5":{
      "scriptId":"u43"},
    "81f3eda368cf42d9bc350795888d6d94":{
      "scriptId":"u44"},
    "fef44f5112a843688092d5585439374c":{
      "scriptId":"u45"},
    "3d6d28e2dcc14b4f8c82e646c824f156":{
      "scriptId":"u46"}}});