$axure.loadCurrentPage({
  "url":"循环盘点扫描.html",
  "generationDate":new Date(1554888136943),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"7d796480506445b5a60fce6034c73c6e",
    "type":"Axure:Page",
    "name":"循环盘点扫描",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8993111dd9ea41ceb6d998c4c9a680a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "size":{
              "width":305,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44f3bd1bff53498a8596dfa71bf3bea1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "size":{
                  "width":305,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u6.png"}},
{
          "id":"9b5a949da7b0475fa4552117d2a64a0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":4,
              "y":5},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bf90abc7b5f46359fe8f45358bbad1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":4,
                  "y":5},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b3dd2721d234b7ebb781a51a5a2bb13",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":124,
              "y":7},
            "size":{
              "width":181,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e94cbbb7b404cb8822c692305acbfce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":124,
                  "y":7},
                "size":{
                  "width":181,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd339d9a68cd4cdeb2fa7f274e0875cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":1,
              "y":451},
            "size":{
              "width":308,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af30ac55b54640b28df4088255c27182",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":1,
                  "y":451},
                "size":{
                  "width":308,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u12.png"}},
{
          "id":"f7233ca6515841d59e3d440c750dd456",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":144,
              "y":457},
            "size":{
              "width":162,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0be6399d7454363b5423b4c310d66a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":144,
                  "y":457},
                "size":{
                  "width":162,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7114da52e6be46dbae6f5fc29c993f8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":49},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e3615a30e9647f0836c3ffa9f3d896d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":49},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb13d0c649484136a77860c642165b56",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCCC},
            "location":{
              "x":330,
              "y":40},
            "size":{
              "width":415,
              "height":416}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a45dc4606aef4c5091e5b61e991ba57d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCCC},
                "location":{
                  "x":330,
                  "y":40},
                "size":{
                  "width":415,
                  "height":416}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pod盘点_1/u15.png"}},
{
          "id":"16db5c47e5a443c1a26037e331b3e9be",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":50},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"34bd0d064da949ac9e2bb6ed4a80d788",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":16,
              "y":381},
            "size":{
              "width":272,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c057972df3440f0b428415aa9295001",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":16,
                  "y":381},
                "size":{
                  "width":272,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (提交按钮)",
                      "objectsToFades":[{
                          "objectPath":["181cad5fdd224791996883366cec4e25"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"181cad5fdd224791996883366cec4e25",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":false,
          "style":{
            "location":{
              "x":106,
              "y":421},
            "size":{
              "width":91,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"61f379b278b8453488df23372d99edc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":165},
            "size":{
              "width":92,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49ecf2a0ad234a079a1bdb8fd7bd4b3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":165},
                "size":{
                  "width":92,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2e3cacd0e984371942f8f97ddb7ec0f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":165},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1034fcb229904487b150177c8f14566b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":200},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6cf17bcf58244e2ab187301aed6fee0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":199},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f4ae8bc00c8474f897d5264883fa343",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":199},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6cd4c3f7c5945d2880943f7c0de6f05",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":233},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1d1647498c5b48e882e5d85927b1dffc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":233},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e305503910b4125a5a2e89509de1982",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":233},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cdbc9095539340149f884b9fc7a48257",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":101},
            "size":{
              "width":92,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75d92462740942aa886ebd57bf00e8cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":101},
                "size":{
                  "width":92,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5fd496a5e0544e98913ed6c13ace28da",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":101},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"51921455a2274a7fa82e84b8abda171a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":132},
            "size":{
              "width":92,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"887fcd8298c34f43ac474ac9f0084b8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":132},
                "size":{
                  "width":92,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d24e8e3c2bf4ef0892e94b9f05d9546",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":132},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9b0c2886d06c47008b786e37d3f0728e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":275},
            "size":{
              "width":122,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (形状)",
                      "objectsToFades":[{
                          "objectPath":["ab6760345aa848b3a30c5b852c332edb"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"ab6760345aa848b3a30c5b852c332edb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":130,
              "y":273},
            "size":{
              "width":158,
              "height":24},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"533b02535d904b53928173bca0a78519",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":130,
                  "y":273},
                "size":{
                  "width":158,
                  "height":24},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6fb170fb92d54f758ffdc83b0a970485",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":330},
            "size":{
              "width":122,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5e5edb2c674a44dbadd6f11d7e871c47",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":164,
              "y":330},
            "size":{
              "width":122,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "8993111dd9ea41ceb6d998c4c9a680a0":{
      "scriptId":"u0"},
    "44f3bd1bff53498a8596dfa71bf3bea1":{
      "scriptId":"u1"},
    "9b5a949da7b0475fa4552117d2a64a0c":{
      "scriptId":"u2"},
    "3bf90abc7b5f46359fe8f45358bbad1e":{
      "scriptId":"u3"},
    "4b3dd2721d234b7ebb781a51a5a2bb13":{
      "scriptId":"u4"},
    "3e94cbbb7b404cb8822c692305acbfce":{
      "scriptId":"u5"},
    "dd339d9a68cd4cdeb2fa7f274e0875cb":{
      "scriptId":"u6"},
    "af30ac55b54640b28df4088255c27182":{
      "scriptId":"u7"},
    "f7233ca6515841d59e3d440c750dd456":{
      "scriptId":"u8"},
    "a0be6399d7454363b5423b4c310d66a5":{
      "scriptId":"u9"},
    "7114da52e6be46dbae6f5fc29c993f8e":{
      "scriptId":"u10"},
    "1e3615a30e9647f0836c3ffa9f3d896d":{
      "scriptId":"u11"},
    "fb13d0c649484136a77860c642165b56":{
      "scriptId":"u12"},
    "a45dc4606aef4c5091e5b61e991ba57d":{
      "scriptId":"u13"},
    "16db5c47e5a443c1a26037e331b3e9be":{
      "scriptId":"u14"},
    "34bd0d064da949ac9e2bb6ed4a80d788":{
      "scriptId":"u15"},
    "3c057972df3440f0b428415aa9295001":{
      "scriptId":"u16"},
    "181cad5fdd224791996883366cec4e25":{
      "scriptId":"u17"},
    "61f379b278b8453488df23372d99edc8":{
      "scriptId":"u18"},
    "49ecf2a0ad234a079a1bdb8fd7bd4b3a":{
      "scriptId":"u19"},
    "b2e3cacd0e984371942f8f97ddb7ec0f":{
      "scriptId":"u20"},
    "1034fcb229904487b150177c8f14566b":{
      "scriptId":"u21"},
    "6cf17bcf58244e2ab187301aed6fee0f":{
      "scriptId":"u22"},
    "2f4ae8bc00c8474f897d5264883fa343":{
      "scriptId":"u23"},
    "d6cd4c3f7c5945d2880943f7c0de6f05":{
      "scriptId":"u24"},
    "1d1647498c5b48e882e5d85927b1dffc":{
      "scriptId":"u25"},
    "3e305503910b4125a5a2e89509de1982":{
      "scriptId":"u26"},
    "cdbc9095539340149f884b9fc7a48257":{
      "scriptId":"u27"},
    "75d92462740942aa886ebd57bf00e8cb":{
      "scriptId":"u28"},
    "5fd496a5e0544e98913ed6c13ace28da":{
      "scriptId":"u29"},
    "51921455a2274a7fa82e84b8abda171a":{
      "scriptId":"u30"},
    "887fcd8298c34f43ac474ac9f0084b8e":{
      "scriptId":"u31"},
    "1d24e8e3c2bf4ef0892e94b9f05d9546":{
      "scriptId":"u32"},
    "9b0c2886d06c47008b786e37d3f0728e":{
      "scriptId":"u33"},
    "ab6760345aa848b3a30c5b852c332edb":{
      "scriptId":"u34"},
    "533b02535d904b53928173bca0a78519":{
      "scriptId":"u35"},
    "6fb170fb92d54f758ffdc83b0a970485":{
      "scriptId":"u36"},
    "5e5edb2c674a44dbadd6f11d7e871c47":{
      "scriptId":"u37"}}});