$axure.loadCurrentPage({
  "url":"异动盘点扫描.html",
  "generationDate":new Date(1554888137100.58),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"51d06c5301c7454bb206992df9e4c625",
    "type":"Axure:Page",
    "name":"异动盘点扫描",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"06eeb1e75cd44c73870603de40360a5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "size":{
              "width":305,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48b112537eab4fa0b69ef6389cb0907c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "size":{
                  "width":305,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u6.png"}},
{
          "id":"d201d28b77654753935a72114f5eabff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":4,
              "y":5},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d0dcacfed1740bdbabe347df5b0b726",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":4,
                  "y":5},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bfedff0643bd4b2486934eb6a3f16230",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":124,
              "y":7},
            "size":{
              "width":181,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a7995577b0443978b2b97d57d61ede9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":124,
                  "y":7},
                "size":{
                  "width":181,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25a086a626164aca92e00f39d2173f23",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":1,
              "y":451},
            "size":{
              "width":308,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3372e4c6e5cd4f739a9ec1e4979707a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":1,
                  "y":451},
                "size":{
                  "width":308,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u12.png"}},
{
          "id":"94699f1b35094e328c63dec0530188fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":144,
              "y":457},
            "size":{
              "width":162,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cb2ce6dc29843bf87e2ee42000ec76c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":144,
                  "y":457},
                "size":{
                  "width":162,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce8f48e1ea364e9cac5f4c23d4f5bd83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":49},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86dd7e35c5b94a7f850fd09008fd9e3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":49},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5b2505c48af48ae8f375e414d40dd92",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCCC},
            "location":{
              "x":330,
              "y":40},
            "size":{
              "width":415,
              "height":416}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c4257923ee44f2fa9d79c03bbeb5b62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCCC},
                "location":{
                  "x":330,
                  "y":40},
                "size":{
                  "width":415,
                  "height":416}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pod盘点_1/u15.png"}},
{
          "id":"07ee7271b9f742778da3b6b4871c5d94",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":50},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"da47dd26bea947aaa18bcd81fa7c132f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":16,
              "y":377},
            "size":{
              "width":272,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2173b6de953445d8ba6bc3c2e95648d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":16,
                  "y":377},
                "size":{
                  "width":272,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (提交按钮)",
                      "objectsToFades":[{
                          "objectPath":["48084f7e663146bfb05271142791e765"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48084f7e663146bfb05271142791e765",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":false,
          "style":{
            "location":{
              "x":106,
              "y":417},
            "size":{
              "width":91,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"ecd63c7d33b541c2b3532d331a31d208",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":165},
            "size":{
              "width":92,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a859060db9b46b292df6c43dd8dc358",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":165},
                "size":{
                  "width":92,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2c07d7ca96d406489d098cbd86502a0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":165},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d553301ec58649b5b95617c503382311",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":200},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9eaab7f254a14b96b6f62967b5e69ab9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":199},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5251479b61b14d81b35756aabc7a4ad8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":199},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d3627b686784d79ad17767749b7a013",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":233},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3abe729a3ad84924adc2596619e64a34",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":233},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67c7aadeb61f45ef88060ba96df5351e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":233},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed5383f091ad4f10bf492af025341cdd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":101},
            "size":{
              "width":92,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"365d73ce2cc042ddb4ba6e90853162ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":101},
                "size":{
                  "width":92,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ea07c5030d24dc8a9c5848aae14991b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":101},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a1050218b4264d3a8427ba552cc4178c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":18,
              "y":132},
            "size":{
              "width":92,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3701ee25218f4e90b6ffb5421cdc3c00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":18,
                  "y":132},
                "size":{
                  "width":92,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9edf45817fa4d8088be21efb9c0714b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":132},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c57acc1a90c04a2692dcc2843a5bff15",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":275},
            "size":{
              "width":122,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (形状)",
                      "objectsToFades":[{
                          "objectPath":["1118051a348e43c88ecd12e1521fb712"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"1118051a348e43c88ecd12e1521fb712",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":130,
              "y":273},
            "size":{
              "width":158,
              "height":24},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"989badf15d1944d399b98dd0595de686",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":130,
                  "y":273},
                "size":{
                  "width":158,
                  "height":24},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4f1f1f0ba614f1e88fd84d74167a182",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":330},
            "size":{
              "width":122,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"485ab25b7bbf47d997b19bd44e575f0b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":164,
              "y":330},
            "size":{
              "width":122,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "06eeb1e75cd44c73870603de40360a5d":{
      "scriptId":"u0"},
    "48b112537eab4fa0b69ef6389cb0907c":{
      "scriptId":"u1"},
    "d201d28b77654753935a72114f5eabff":{
      "scriptId":"u2"},
    "1d0dcacfed1740bdbabe347df5b0b726":{
      "scriptId":"u3"},
    "bfedff0643bd4b2486934eb6a3f16230":{
      "scriptId":"u4"},
    "2a7995577b0443978b2b97d57d61ede9":{
      "scriptId":"u5"},
    "25a086a626164aca92e00f39d2173f23":{
      "scriptId":"u6"},
    "3372e4c6e5cd4f739a9ec1e4979707a5":{
      "scriptId":"u7"},
    "94699f1b35094e328c63dec0530188fd":{
      "scriptId":"u8"},
    "4cb2ce6dc29843bf87e2ee42000ec76c":{
      "scriptId":"u9"},
    "ce8f48e1ea364e9cac5f4c23d4f5bd83":{
      "scriptId":"u10"},
    "86dd7e35c5b94a7f850fd09008fd9e3b":{
      "scriptId":"u11"},
    "b5b2505c48af48ae8f375e414d40dd92":{
      "scriptId":"u12"},
    "5c4257923ee44f2fa9d79c03bbeb5b62":{
      "scriptId":"u13"},
    "07ee7271b9f742778da3b6b4871c5d94":{
      "scriptId":"u14"},
    "da47dd26bea947aaa18bcd81fa7c132f":{
      "scriptId":"u15"},
    "2173b6de953445d8ba6bc3c2e95648d1":{
      "scriptId":"u16"},
    "48084f7e663146bfb05271142791e765":{
      "scriptId":"u17"},
    "ecd63c7d33b541c2b3532d331a31d208":{
      "scriptId":"u18"},
    "6a859060db9b46b292df6c43dd8dc358":{
      "scriptId":"u19"},
    "c2c07d7ca96d406489d098cbd86502a0":{
      "scriptId":"u20"},
    "d553301ec58649b5b95617c503382311":{
      "scriptId":"u21"},
    "9eaab7f254a14b96b6f62967b5e69ab9":{
      "scriptId":"u22"},
    "5251479b61b14d81b35756aabc7a4ad8":{
      "scriptId":"u23"},
    "5d3627b686784d79ad17767749b7a013":{
      "scriptId":"u24"},
    "3abe729a3ad84924adc2596619e64a34":{
      "scriptId":"u25"},
    "67c7aadeb61f45ef88060ba96df5351e":{
      "scriptId":"u26"},
    "ed5383f091ad4f10bf492af025341cdd":{
      "scriptId":"u27"},
    "365d73ce2cc042ddb4ba6e90853162ed":{
      "scriptId":"u28"},
    "9ea07c5030d24dc8a9c5848aae14991b":{
      "scriptId":"u29"},
    "a1050218b4264d3a8427ba552cc4178c":{
      "scriptId":"u30"},
    "3701ee25218f4e90b6ffb5421cdc3c00":{
      "scriptId":"u31"},
    "c9edf45817fa4d8088be21efb9c0714b":{
      "scriptId":"u32"},
    "c57acc1a90c04a2692dcc2843a5bff15":{
      "scriptId":"u33"},
    "1118051a348e43c88ecd12e1521fb712":{
      "scriptId":"u34"},
    "989badf15d1944d399b98dd0595de686":{
      "scriptId":"u35"},
    "d4f1f1f0ba614f1e88fd84d74167a182":{
      "scriptId":"u36"},
    "485ab25b7bbf47d997b19bd44e575f0b":{
      "scriptId":"u37"}}});