$axure.loadCurrentPage({
  "url":"拣货汇总.html",
  "generationDate":new Date(1554888137577.3),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"f29b4d5870cd4b8a8cc25f5121d4ee8b",
    "type":"Axure:Page",
    "name":"拣货汇总",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4fcbc841d27d40e3922704b97aef8c52",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":130},
            "size":{
              "width":300,
              "height":280}},
          "adaptiveStyles":{
}},
{
          "id":"2560f06445a442e0b96bf0e5bd78aff3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "size":{
              "width":305,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edf50a8b8bdd4b3791dfb8df8bf0ee65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "size":{
                  "width":305,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u6.png"}},
{
          "id":"f756fccc49e44bfea4471999334ec89d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":4,
              "y":5},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3833cb99167c4e5faffb2df2337b9272",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":4,
                  "y":5},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9fbb0ef7e3224b5bb2ab7aedc308cd29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":136,
              "y":7},
            "size":{
              "width":164,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"195946c9360141368346f1f19a735821",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":136,
                  "y":7},
                "size":{
                  "width":164,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ffa33ad286f247aab831b98df1dda1b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":1,
              "y":451},
            "size":{
              "width":308,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8799c07d3a14ba49ced670997b91939",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":1,
                  "y":451},
                "size":{
                  "width":308,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分拣位绑板-rf/u12.png"}},
{
          "id":"8d06164a704046e8933c0fbe76eea1b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Oblique', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"900",
            "fontStyle":"oblique",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":144,
              "y":457},
            "size":{
              "width":162,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3964f51a91d40f9be4249e98d9334bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Oblique', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"900",
                "fontStyle":"oblique",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":144,
                  "y":457},
                "size":{
                  "width":162,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8639e4e678e240509db18fe51a972eeb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":22,
              "y":55},
            "size":{
              "width":83,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3814079e82d7441b829e061547c6fb6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":55},
                "size":{
                  "width":83,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13e8a98ee8a1461b9bec2c7e4b5c1d14",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":112,
              "y":54},
            "size":{
              "width":178,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"fab3d8d484924c519d8a54fabfbccdb8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":112,
              "y":416},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b89a1356dafd4756b79c17f7b1109d1a",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":130},
            "size":{
              "width":355,
              "height":154}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fe817e33638470e9568b31b23db6d2b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":113,
                  "y":0},
                "size":{
                  "width":53,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"55b53005584a452fadb5e3624f58c7b1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":113,
                      "y":0},
                    "size":{
                      "width":53,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拣货汇总/u18.png"}},
{
              "id":"a56975b10bf94c888f94747bf8c80e7d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":229,
                  "y":0},
                "size":{
                  "width":55,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"903ff49ebf9641e09fe95c241b021e73",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":229,
                      "y":0},
                    "size":{
                      "width":55,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拣货汇总/u22.png"}},
{
              "id":"6be3a7d455c940099521c5063b433189",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":284,
                  "y":0},
                "size":{
                  "width":71,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"81207188ff6844269476fff22b411dcd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":284,
                      "y":0},
                    "size":{
                      "width":71,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拣货汇总/u24.png"}},
{
              "id":"3b6ae15bbd3845bab01edd2ff5ecea89",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":113,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5c8a777f7ba144ab917085565205812e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":113,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拣货汇总/u16.png"}},
{
              "id":"85d67a64a94a4cd183cb6ea8769f274b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":134},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"233a285850414ba585eddfd34363d511",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":134},
                    "size":{
                      "width":113,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拣货汇总/u76.png"}},
{
              "id":"5e1d895729084197b11d3087a0e40784",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":113,
                  "y":134},
                "size":{
                  "width":53,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"767228e03f3d4e13843e456776293de5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":113,
                      "y":134},
                    "size":{
                      "width":53,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库存查询/u340.png"}},
{
              "id":"69c0a11e0fa54986bcdf642347e1f664",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":229,
                  "y":134},
                "size":{
                  "width":55,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"99f2a5d990de481095d5e5bbf863bf5a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":229,
                      "y":134},
                    "size":{
                      "width":55,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/人工上架/u83.png"}},
{
              "id":"309069b699894e79ad7e9b06bbe3844d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":284,
                  "y":134},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e2366f01c74d40fa88941f06008d6519",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":284,
                      "y":134},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拣货汇总/u84.png"}},
{
              "id":"b06173f97b6f4da78d5b1ab4db6262c6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":94},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2c79657b303e48c8b093762c3c093341",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":94},
                    "size":{
                      "width":113,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/变更日志/u27.png"}},
{
              "id":"ff647f54f2444a2e9c8cbd59e4feb0e7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":113,
                  "y":94},
                "size":{
                  "width":53,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"94bef37e1909480ca8bb0922b92486ac",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":113,
                      "y":94},
                    "size":{
                      "width":53,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库存查询/u43.png"}},
{
              "id":"61c6e215b0234bfea785a3c4a014fd56",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":229,
                  "y":94},
                "size":{
                  "width":55,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1c3f5146acaa4f38bbe25b228a758f70",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":229,
                      "y":94},
                    "size":{
                      "width":55,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/人工下架/u47.png"}},
{
              "id":"6dd76ed6d5fc4690b58a6782570d24c9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":284,
                  "y":94},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0260aa1d42954912ad7ea0c21f0bdbe6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":284,
                      "y":94},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拣货汇总/u34.png"}},
{
              "id":"6b0066617ad648ef9aa69c537b3da1b4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":74},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ca5778e2096943e5832033aa86e9852e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":74},
                    "size":{
                      "width":113,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/变更日志/u27.png"}},
{
              "id":"fb9e7f8e4244463eb997a729443c65ac",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":113,
                  "y":74},
                "size":{
                  "width":53,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c15dfba1e177474baeaba8921f6ac359",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":113,
                      "y":74},
                    "size":{
                      "width":53,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库存查询/u43.png"}},
{
              "id":"de4ab89c439144499bb077369f240f2e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":229,
                  "y":74},
                "size":{
                  "width":55,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6609ee5cebb84de0bfbfe33f185f1b48",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":229,
                      "y":74},
                    "size":{
                      "width":55,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/人工下架/u47.png"}},
{
              "id":"a13ee6cd5e834828b3c8b87e5146fcaf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":284,
                  "y":74},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e7239fe385f84c658037ebe56b95e87b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":284,
                      "y":74},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拣货汇总/u34.png"}},
{
              "id":"fbf09d9bfd544b5789e11913c89656e1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":54},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8c0e2a2bf999420f93475c9b63eec6ac",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":54},
                    "size":{
                      "width":113,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/变更日志/u27.png"}},
{
              "id":"e800fa452c27453bbd17421268c57192",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":113,
                  "y":54},
                "size":{
                  "width":53,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cdc2ade960764b86aa4c3507c5fe2725",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":113,
                      "y":54},
                    "size":{
                      "width":53,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库存查询/u43.png"}},
{
              "id":"924ef22dae2447ed8bf423c80c7798ee",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":229,
                  "y":54},
                "size":{
                  "width":55,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"be718d7748034066957a7a1c5bbc9bda",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":229,
                      "y":54},
                    "size":{
                      "width":55,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/人工下架/u47.png"}},
{
              "id":"4ae32ccafb1e470cb12b5cb07a4c9d39",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":284,
                  "y":54},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"07d7840ad8164800b47e343c12b4b95a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":284,
                      "y":54},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拣货汇总/u34.png"}},
{
              "id":"e6d83086c0574cc9821b9c1d833fe872",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":114},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6d12930412e549a1af8256c434c2a779",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":114},
                    "size":{
                      "width":113,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/变更日志/u27.png"}},
{
              "id":"e702f61d4eb84471bfc0aad234c89a0e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":113,
                  "y":114},
                "size":{
                  "width":53,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a867105cc9e74b608ddfb87e9f8f305d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":113,
                      "y":114},
                    "size":{
                      "width":53,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库存查询/u43.png"}},
{
              "id":"fb9b1c8f52724358bec2106924f80ea6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":229,
                  "y":114},
                "size":{
                  "width":55,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1c74ffccf0a44645b2c813e262a19b4e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":229,
                      "y":114},
                    "size":{
                      "width":55,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/人工下架/u47.png"}},
{
              "id":"2a6396f0da584c4aaa39927cbc3e3e36",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":284,
                  "y":114},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f18bbc01136a4797ab1f26dabc7867e3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":284,
                      "y":114},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拣货汇总/u34.png"}},
{
              "id":"5dd5944be3574f34a39ec508a351f9f8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":34},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c72b53d49e2048d382b4957504020dec",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":34},
                    "size":{
                      "width":113,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/变更日志/u27.png"}},
{
              "id":"5d7b2a36b07f4520bb6c18df7e2c495a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":113,
                  "y":34},
                "size":{
                  "width":53,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"04b4fd50df80489aa635085d574a2007",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":113,
                      "y":34},
                    "size":{
                      "width":53,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/库存查询/u43.png"}},
{
              "id":"b64bfdbc12f444a9a9b4d956960e3e1d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":229,
                  "y":34},
                "size":{
                  "width":55,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"272106fc07974bf1a5255a52432bd25a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":229,
                      "y":34},
                    "size":{
                      "width":55,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/人工下架/u47.png"}},
{
              "id":"2a24449c8d684265ad476ff3da8f6630",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":284,
                  "y":34},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1cff04c663044151a52421c9f95783e2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":284,
                      "y":34},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拣货汇总/u34.png"}},
{
              "id":"3dc57662dc38491c800b874e3bb11078",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":166,
                  "y":0},
                "size":{
                  "width":63,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cc11b12f2e13488e82746dee6e3c04b6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":166,
                      "y":0},
                    "size":{
                      "width":63,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点调整单/u62.png"}},
{
              "id":"bb21c51a889843ea9ea0557c0e20fbd3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":166,
                  "y":34},
                "size":{
                  "width":63,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"39fac5071a944feaaaadc366bb1c2111",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":166,
                      "y":34},
                    "size":{
                      "width":63,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u74.png"}},
{
              "id":"7901dfa176dd4e7f8a84c6c4c4568ad1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":166,
                  "y":54},
                "size":{
                  "width":63,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4668cafbf9b048ed95536ae26860a164",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":166,
                      "y":54},
                    "size":{
                      "width":63,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u74.png"}},
{
              "id":"f973ab1893ff4f01ba898cf9c2a4a161",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":166,
                  "y":74},
                "size":{
                  "width":63,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"253c41b0569c45fd8cc238291d1a7fe0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":166,
                      "y":74},
                    "size":{
                      "width":63,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u74.png"}},
{
              "id":"73530815334f4a52bd31b3b2c73ef0fc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":166,
                  "y":94},
                "size":{
                  "width":63,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"74b3ea29b1734ac594c09b1153d5025b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":166,
                      "y":94},
                    "size":{
                      "width":63,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u74.png"}},
{
              "id":"cd700a9b907d45b295c3dd518b655f31",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":166,
                  "y":114},
                "size":{
                  "width":63,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"81192119fc8f4e9ba6422c0af0601b00",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":166,
                      "y":114},
                    "size":{
                      "width":63,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u74.png"}},
{
              "id":"2b26a320179a4b2b8694c15b6cf1d94e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":166,
                  "y":134},
                "size":{
                  "width":63,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"76037599a5a04a0fbaa1365c07c30770",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":166,
                      "y":134},
                    "size":{
                      "width":63,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/待上架查询/u256.png"}}]},
{
          "id":"c7be0159dd1043de8dedee1669fecd7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":22,
              "y":85},
            "size":{
              "width":83,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9e5cbd0948846c0a10d77b2d8f5dc5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":85},
                "size":{
                  "width":83,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab22933e1da5400a86cb5201bb216be2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":112,
              "y":86},
            "size":{
              "width":178,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2020a1fa7d844386929a39c1575c4056",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":22,
              "y":310},
            "size":{
              "width":52,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1febb584c6a4a23b2a0fbc174525344",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":22,
                  "y":310},
                "size":{
                  "width":52,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0c5754a9cea444e879ac95f9f67e87e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":142,
              "y":310},
            "size":{
              "width":52,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"681caff976e147a0aa550d1e03db85d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":142,
                  "y":310},
                "size":{
                  "width":52,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0743174a9bb54ec6a21fa76328f22b64",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":310},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6b1c66dcf5b7422eaff8e1f7421398ba",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":310},
            "size":{
              "width":43,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0f13f718e41f43d7874995c142fd9036",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":22,
              "y":345},
            "size":{
              "width":52,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"022df32d73994beeb5e90c1740cf23fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":22,
                  "y":345},
                "size":{
                  "width":52,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dff87690bb294ae99dfc8ed93c2f480d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "location":{
              "x":142,
              "y":345},
            "size":{
              "width":52,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81ef4f6348b4460bab56b353685f55f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "location":{
                  "x":142,
                  "y":345},
                "size":{
                  "width":52,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4a74d31db234c9da2089048a26b1475",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":345},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"dcff0f7a1fb141efade2a1817ed5a8d6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":345},
            "size":{
              "width":43,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d58d2221f8fe41e9ba32cf0c13b8d268",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCCC},
            "location":{
              "x":423,
              "y":156},
            "size":{
              "width":367,
              "height":101}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"489266d72c2041e3b4b848183f61e696",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCCC},
                "location":{
                  "x":423,
                  "y":156},
                "size":{
                  "width":367,
                  "height":101}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拣货汇总/u101.png"}},
{
          "id":"840a1da98e9a47a9a9b74d9b43e70bdf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCCC},
            "location":{
              "x":423,
              "y":300},
            "size":{
              "width":347,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85f0b601e2f44e41aa5530b637f7e473",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCCC},
                "location":{
                  "x":423,
                  "y":300},
                "size":{
                  "width":347,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拣货汇总/u103.png"}},
{
          "id":"af826bcce538491bb8f83b7b59bf2fdd",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":210},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"732f3be20a4b4d168c8ce5f36b09de33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":210},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}]},
{
          "id":"ac68a20ac90646b79990ce3e51e72d9c",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":340},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"034353bafb10473b82b66b2d69b7c2cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":340},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "4fcbc841d27d40e3922704b97aef8c52":{
      "scriptId":"u0"},
    "2560f06445a442e0b96bf0e5bd78aff3":{
      "scriptId":"u1"},
    "edf50a8b8bdd4b3791dfb8df8bf0ee65":{
      "scriptId":"u2"},
    "f756fccc49e44bfea4471999334ec89d":{
      "scriptId":"u3"},
    "3833cb99167c4e5faffb2df2337b9272":{
      "scriptId":"u4"},
    "9fbb0ef7e3224b5bb2ab7aedc308cd29":{
      "scriptId":"u5"},
    "195946c9360141368346f1f19a735821":{
      "scriptId":"u6"},
    "ffa33ad286f247aab831b98df1dda1b1":{
      "scriptId":"u7"},
    "d8799c07d3a14ba49ced670997b91939":{
      "scriptId":"u8"},
    "8d06164a704046e8933c0fbe76eea1b9":{
      "scriptId":"u9"},
    "d3964f51a91d40f9be4249e98d9334bd":{
      "scriptId":"u10"},
    "8639e4e678e240509db18fe51a972eeb":{
      "scriptId":"u11"},
    "3814079e82d7441b829e061547c6fb6e":{
      "scriptId":"u12"},
    "13e8a98ee8a1461b9bec2c7e4b5c1d14":{
      "scriptId":"u13"},
    "fab3d8d484924c519d8a54fabfbccdb8":{
      "scriptId":"u14"},
    "b89a1356dafd4756b79c17f7b1109d1a":{
      "scriptId":"u15"},
    "3b6ae15bbd3845bab01edd2ff5ecea89":{
      "scriptId":"u16"},
    "5c8a777f7ba144ab917085565205812e":{
      "scriptId":"u17"},
    "4fe817e33638470e9568b31b23db6d2b":{
      "scriptId":"u18"},
    "55b53005584a452fadb5e3624f58c7b1":{
      "scriptId":"u19"},
    "3dc57662dc38491c800b874e3bb11078":{
      "scriptId":"u20"},
    "cc11b12f2e13488e82746dee6e3c04b6":{
      "scriptId":"u21"},
    "a56975b10bf94c888f94747bf8c80e7d":{
      "scriptId":"u22"},
    "903ff49ebf9641e09fe95c241b021e73":{
      "scriptId":"u23"},
    "6be3a7d455c940099521c5063b433189":{
      "scriptId":"u24"},
    "81207188ff6844269476fff22b411dcd":{
      "scriptId":"u25"},
    "5dd5944be3574f34a39ec508a351f9f8":{
      "scriptId":"u26"},
    "c72b53d49e2048d382b4957504020dec":{
      "scriptId":"u27"},
    "5d7b2a36b07f4520bb6c18df7e2c495a":{
      "scriptId":"u28"},
    "04b4fd50df80489aa635085d574a2007":{
      "scriptId":"u29"},
    "bb21c51a889843ea9ea0557c0e20fbd3":{
      "scriptId":"u30"},
    "39fac5071a944feaaaadc366bb1c2111":{
      "scriptId":"u31"},
    "b64bfdbc12f444a9a9b4d956960e3e1d":{
      "scriptId":"u32"},
    "272106fc07974bf1a5255a52432bd25a":{
      "scriptId":"u33"},
    "2a24449c8d684265ad476ff3da8f6630":{
      "scriptId":"u34"},
    "1cff04c663044151a52421c9f95783e2":{
      "scriptId":"u35"},
    "fbf09d9bfd544b5789e11913c89656e1":{
      "scriptId":"u36"},
    "8c0e2a2bf999420f93475c9b63eec6ac":{
      "scriptId":"u37"},
    "e800fa452c27453bbd17421268c57192":{
      "scriptId":"u38"},
    "cdc2ade960764b86aa4c3507c5fe2725":{
      "scriptId":"u39"},
    "7901dfa176dd4e7f8a84c6c4c4568ad1":{
      "scriptId":"u40"},
    "4668cafbf9b048ed95536ae26860a164":{
      "scriptId":"u41"},
    "924ef22dae2447ed8bf423c80c7798ee":{
      "scriptId":"u42"},
    "be718d7748034066957a7a1c5bbc9bda":{
      "scriptId":"u43"},
    "4ae32ccafb1e470cb12b5cb07a4c9d39":{
      "scriptId":"u44"},
    "07d7840ad8164800b47e343c12b4b95a":{
      "scriptId":"u45"},
    "6b0066617ad648ef9aa69c537b3da1b4":{
      "scriptId":"u46"},
    "ca5778e2096943e5832033aa86e9852e":{
      "scriptId":"u47"},
    "fb9e7f8e4244463eb997a729443c65ac":{
      "scriptId":"u48"},
    "c15dfba1e177474baeaba8921f6ac359":{
      "scriptId":"u49"},
    "f973ab1893ff4f01ba898cf9c2a4a161":{
      "scriptId":"u50"},
    "253c41b0569c45fd8cc238291d1a7fe0":{
      "scriptId":"u51"},
    "de4ab89c439144499bb077369f240f2e":{
      "scriptId":"u52"},
    "6609ee5cebb84de0bfbfe33f185f1b48":{
      "scriptId":"u53"},
    "a13ee6cd5e834828b3c8b87e5146fcaf":{
      "scriptId":"u54"},
    "e7239fe385f84c658037ebe56b95e87b":{
      "scriptId":"u55"},
    "b06173f97b6f4da78d5b1ab4db6262c6":{
      "scriptId":"u56"},
    "2c79657b303e48c8b093762c3c093341":{
      "scriptId":"u57"},
    "ff647f54f2444a2e9c8cbd59e4feb0e7":{
      "scriptId":"u58"},
    "94bef37e1909480ca8bb0922b92486ac":{
      "scriptId":"u59"},
    "73530815334f4a52bd31b3b2c73ef0fc":{
      "scriptId":"u60"},
    "74b3ea29b1734ac594c09b1153d5025b":{
      "scriptId":"u61"},
    "61c6e215b0234bfea785a3c4a014fd56":{
      "scriptId":"u62"},
    "1c3f5146acaa4f38bbe25b228a758f70":{
      "scriptId":"u63"},
    "6dd76ed6d5fc4690b58a6782570d24c9":{
      "scriptId":"u64"},
    "0260aa1d42954912ad7ea0c21f0bdbe6":{
      "scriptId":"u65"},
    "e6d83086c0574cc9821b9c1d833fe872":{
      "scriptId":"u66"},
    "6d12930412e549a1af8256c434c2a779":{
      "scriptId":"u67"},
    "e702f61d4eb84471bfc0aad234c89a0e":{
      "scriptId":"u68"},
    "a867105cc9e74b608ddfb87e9f8f305d":{
      "scriptId":"u69"},
    "cd700a9b907d45b295c3dd518b655f31":{
      "scriptId":"u70"},
    "81192119fc8f4e9ba6422c0af0601b00":{
      "scriptId":"u71"},
    "fb9b1c8f52724358bec2106924f80ea6":{
      "scriptId":"u72"},
    "1c74ffccf0a44645b2c813e262a19b4e":{
      "scriptId":"u73"},
    "2a6396f0da584c4aaa39927cbc3e3e36":{
      "scriptId":"u74"},
    "f18bbc01136a4797ab1f26dabc7867e3":{
      "scriptId":"u75"},
    "85d67a64a94a4cd183cb6ea8769f274b":{
      "scriptId":"u76"},
    "233a285850414ba585eddfd34363d511":{
      "scriptId":"u77"},
    "5e1d895729084197b11d3087a0e40784":{
      "scriptId":"u78"},
    "767228e03f3d4e13843e456776293de5":{
      "scriptId":"u79"},
    "2b26a320179a4b2b8694c15b6cf1d94e":{
      "scriptId":"u80"},
    "76037599a5a04a0fbaa1365c07c30770":{
      "scriptId":"u81"},
    "69c0a11e0fa54986bcdf642347e1f664":{
      "scriptId":"u82"},
    "99f2a5d990de481095d5e5bbf863bf5a":{
      "scriptId":"u83"},
    "309069b699894e79ad7e9b06bbe3844d":{
      "scriptId":"u84"},
    "e2366f01c74d40fa88941f06008d6519":{
      "scriptId":"u85"},
    "c7be0159dd1043de8dedee1669fecd7e":{
      "scriptId":"u86"},
    "d9e5cbd0948846c0a10d77b2d8f5dc5e":{
      "scriptId":"u87"},
    "ab22933e1da5400a86cb5201bb216be2":{
      "scriptId":"u88"},
    "2020a1fa7d844386929a39c1575c4056":{
      "scriptId":"u89"},
    "c1febb584c6a4a23b2a0fbc174525344":{
      "scriptId":"u90"},
    "b0c5754a9cea444e879ac95f9f67e87e":{
      "scriptId":"u91"},
    "681caff976e147a0aa550d1e03db85d3":{
      "scriptId":"u92"},
    "0743174a9bb54ec6a21fa76328f22b64":{
      "scriptId":"u93"},
    "6b1c66dcf5b7422eaff8e1f7421398ba":{
      "scriptId":"u94"},
    "0f13f718e41f43d7874995c142fd9036":{
      "scriptId":"u95"},
    "022df32d73994beeb5e90c1740cf23fa":{
      "scriptId":"u96"},
    "dff87690bb294ae99dfc8ed93c2f480d":{
      "scriptId":"u97"},
    "81ef4f6348b4460bab56b353685f55f3":{
      "scriptId":"u98"},
    "c4a74d31db234c9da2089048a26b1475":{
      "scriptId":"u99"},
    "dcff0f7a1fb141efade2a1817ed5a8d6":{
      "scriptId":"u100"},
    "d58d2221f8fe41e9ba32cf0c13b8d268":{
      "scriptId":"u101"},
    "489266d72c2041e3b4b848183f61e696":{
      "scriptId":"u102"},
    "840a1da98e9a47a9a9b74d9b43e70bdf":{
      "scriptId":"u103"},
    "85f0b601e2f44e41aa5530b637f7e473":{
      "scriptId":"u104"},
    "af826bcce538491bb8f83b7b59bf2fdd":{
      "scriptId":"u105"},
    "732f3be20a4b4d168c8ce5f36b09de33":{
      "scriptId":"u106"},
    "ac68a20ac90646b79990ce3e51e72d9c":{
      "scriptId":"u107"},
    "034353bafb10473b82b66b2d69b7c2cc":{
      "scriptId":"u108"}}});